# -*- coding: utf-8 -*-
"""Structured source for the Auckland medicinal-cannabis IPM blueprint.

The supplied IPM Book V15 is used as a coverage benchmark only. Wording, branded
programmes and artwork are not reproduced. New Zealand official sources and primary
literature control legal and technical claims.
"""

SLUG = "auckland-ipm-blueprint"
TITLE = "Integrated pest management blueprint for indoor medicinal cannabis in Auckland"
EYEBROW = "Plant health · Auckland medicinal cannabis"
SUB = (
    "A working system for keeping pests and diseases out of an indoor medicinal-cannabis facility: "
    "clean starting material, confident identification, control choices that are lawful in New Zealand, "
    "monitoring through the crop cycle, and a written trail from the first finding through corrective "
    "action to batch hold or release."
)
META = [
    ("shield", "Plant health"),
    ("image", "23 generated photo plates"),
    ("quote", "Official NZ + primary sources"),
    ("clock", "~55 min read"),
]
RELATED = ["ipm-sop", "pest-id", "mould-risk", "pppe", "tissue-culture"]

REF_IDS = [
    "moh-nz-pesticide-use-2024",
    "moh-nz-mqs-2026",
    "mpi-nz-acvm-exempt",
    "mpi-nz-invertebrate-import",
    "epa-nz-hsno-approvals",
    "worksafe-nz-rei",
    "worksafe-nz-hs-training",
    "watercare-nz-trade-waste",
    "auckland-unitary-plan-e33",
    "athena-ipm-book-v15",
    "ahmed-2024-hemp-pests-florida-jipm",
    "pulkoski-burrack-2023-piercing-sucking-hemp",
    "cranshaw-2018-phorodon-cannabis-north-america",
    "cranshaw-wainwright-2020-rice-root-aphid-cannabis",
    "lopez-2023-amblyseius-swirskii-review-jipm",
    "vanmaanen-2010-broad-mite-swirskii-biocontrol",
    "cloyd-2015-fungus-gnat-ecology-management",
    "cloyd-2024-biopesticides-cannabis-oregon",
    "punja-2021-emerging-diseases-cannabis",
    "scott-punja-2021-powdery-mildew-management",
    "mahmoud-2023-botrytis-budrot",
    "punja-2023-fusarium-pythium-biocontrol",
    "sutton-2006-pythium-hydroponic-etiology",
    "hlvd_threat2023",
    "hlvd_mgmt2025",
    "hlvd-transmission-2025",
    "rahnama-2021-septoria-cannabis",
    "ujata-2024-septoria-cannabicola",
]


LEGAL_GATES = [
    (
        "1. Intended end use",
        "Decide first whether any part of this lot could end up as flower that a patient inhales. If it "
        "could, keep it on the inhalation-capable pathway from the beginning. The rules covering products "
        "that are not inhaled are wider, and it is easy to drift into them without noticing. They are not "
        "available to a lot that may be inhaled.",
    ),
    (
        "2. Medicinal-cannabis pathway",
        "Confirm that the active substance or product has a route specifically accepted for medicinal "
        "cannabis, such as Regulation 18. Regulation 7 covers residues a laboratory measures in the "
        "finished product. A substance appearing there as something to be measured is not permission to "
        "apply it to the crop.",
    ),
    (
        "3. ACVM authority",
        "Confirm the product is registered, or that a documented exemption covers it and every condition "
        "attached to that exemption is met. Not finding a product on a register tells you nothing either "
        "way; absence is not evidence of an exemption.",
    ),
    (
        "4. HSNO approval",
        "Confirm the substance holds an EPA approval, and read the controls attached to it. The safety "
        "data sheet (SDS) is the supplier's hazard document for a product; check section 15 of the current "
        "New Zealand version, then verify what it says against the EPA database rather than trusting the "
        "sheet on its own.",
    ),
    (
        "5. Worker controls",
        "Read the current label and safety data sheet for the personal protective equipment (PPE) "
        "required, the controls on how the product is applied, and the re-entry rules. A freshly painted "
        "room looks finished long before it is comfortable to sit in, and the wait is set by the paint "
        "rather than by how the walls look. A treated crop area works the same way, and that wait has a "
        "name: the restricted entry interval, or REI, is the period after an application when nobody may "
        "enter unless the specified PPE and conditions are in place. An indoor area under an REI needs "
        "signage and controlled access.",
    ),
    (
        "6. Analytical route",
        "Before a product joins the approved-input register, settle four things: which residues must be "
        "tested, the limit the batch has to meet to be released, whether the laboratory's accreditation "
        "actually covers that test, and whether the method can measure low enough. That last point is the "
        "limit of quantification, or LOQ: the lowest concentration a method can report with acceptable "
        "confidence. A method whose LOQ sits above the release limit cannot show that the batch passes.",
    ),
    (
        "7. Biological compatibility",
        "Check the current side-effect data for every beneficial organism already working in the room: "
        "predatory mites and insects, parasitoids, nematodes and microbial products. Side-effect data "
        "records how a product affects those organisms and how long the effect lasts. A spray can be "
        "entirely lawful and still wipe out a biological programme that took weeks to establish.",
    ),
    (
        "8. Environmental route",
        "Decide in advance where unused mix, rinse water, contaminated PPE and spills will go, and how "
        "each is contained. Nothing goes to stormwater. Whether anything may be discharged to the sewer "
        "as trade waste depends on the position Watercare holds for the site.",
    ),
]


CONTROL_LAYERS = [
    ("Cultural", "Keep the problem out, quarantine what arrives, clean surfaces and tools, control how people and plants move, remove the debris and weeds that shelter pests, and scout on a fixed route with a written record."),
    ("Environmental", "Take away the temperature, moisture, airflow and root-zone conditions that favour the problem."),
    ("Biological", "Establish the right predator, parasitoid, nematode or antagonist before pest pressure outruns it. A slow-cooked meal cannot be started at six and eaten at half past; predator numbers build on their own schedule too, so the release date is set by that build-up rather than by the day the problem became obvious."),
    ("Chemical / reduced-risk", "Use only after the legal gate is passed, aimed at the life stage that is actually vulnerable, and followed by a recheck on a date you set in advance."),
]


SEVERITY = [
    ("0", "Not found", "No confirmed organism and no damage. Keep to the planned monitoring frequency; nothing changes."),
    ("1", "Trace", "One confirmed individual, colony or lesion at one mapped point, with no sign of spread."),
    ("2", "Local", "More than one finding within a single zone, or a trap count climbing over successive reads, without room-wide spread."),
    ("3", "Established", "Several zones affected, more than one life stage recurring, disease incidence rising, or the biological programme losing ground."),
    ("4", "Systemic", "Spread across the room or into linked rooms, clean stock involved, crop quality at risk, or shared infrastructure contaminated."),
]


ATLAS = [
    {
        "kind": "arthropod",
        "name": "Rice root aphid",
        "scientific": "Rhopalosiphum rufiabdominale",
        "image": "assets/img/ipm-blueprint/01-rice-root-aphid.webp",
        "alt": "AI-generated educational reconstruction of rice root aphids colonising cannabis roots",
        "scale": "The plate is not to scale. Colonies can be seen with the naked eye on an exposed root ball, but confirming the animal takes about 30x-60x with a hand lens or microscope: enough to resolve the antennae, the paired tubes near the rear called cornicles, and the body shape of a winged adult.",
        "identify": "Soft, pear-shaped aphids living in the root zone, in cream, amber or brown colonies, often with a waxy residue around them. Winged individuals turn up on sticky cards set low, just above the media. The paired cornicles and the plump aphid body separate them from fungus gnats, which are slender flies.",
        "signs": "Yellowing you cannot explain, stunting, a weak response to watering, sticky or waxy material at the root crown, and colonies on the roots or the base of the pot. Everything visible above the media could equally be several other problems.",
        "biology": "Wingless colonies feed below ground. When a colony gets crowded it produces winged individuals that leave and start new ones. They travel in rooted cuttings, loose media, pots, runoff water, and on the hands and tools that handle all of those.",
        "inspect": "Lift whatever covers the root zone and look at the crown, the outer edge of the root ball, the drainage holes and the debris under the bench. Set yellow cards just above the media surface, and keep any winged specimen you cannot name.",
        "confirm": "Microscopy, or identification by a specialist. Compare the antennae, the cornicles and the body shape against an adult fungus gnat before choosing a control.",
        "lookalikes": "Adult fungus gnats, root-zone or nutrient stress, Pythium root rot, and simple overwatering.",
        "threshold": "Zero tolerance in quarantine, foundation mothers, production mothers and clone rooms. One confirmed colony in production triggers containment and inspection of every lot linked to it.",
        "response": "Isolate the zone. Bag the worst plants. Stop pots and media moving anywhere. Inspect the mothers and clone lots connected to this one. Clear standing water and algae without drying the roots into stress. Choose only root-zone biological agents or inputs that currently pass the New Zealand legal gate, then recheck the roots and the low cards on the approved interval.",
        "development": "Under root-zone conditions that suit them, a full generation may take roughly 10-14 days; the plant, the temperature and the media all shift that window. Survey for all three forms: the live-born young, the wingless adults, and the winged dispersers.",
        "controls": "Cultural: refuse infested stock and media, keep pots segregated, and clean up spills. Environmental: remove standing water and algae without stressing the roots. Biological: consider lawful root-zone predators or nematodes matched to the stage you are targeting. Approved input: only a registered product, or a documented exempt root-zone use, that passes the New Zealand legal gate.",
        "targeting": "Aim at the exposed colonies and the moving young stages on the roots and crown, and watch for winged adults on the cards just above the media. Spraying the canopy does not reach a colony living underground.",
        "constraints": "Quarantine and mother stock stay at zero tolerance. Before treating, confirm the organism or product's legal status, that root-zone use is covered, and that beneficials already present will survive it, then check crop stage, the PPE and REI on the label, and what the residue means for testing.",
        "specimen": "Bag a labelled root or crown sample with some live colony still on it, and keep winged specimens from the low cards separately. Record the plant, lot, room, root zone and collection time, and keep the chain of custody intact: an unbroken written record of who held the sample and when.",
        "recheck": "Reinspect the mapped roots and the low cards after the approved interval, then again once a full generation has had time to pass. Success means no live colony, no new winged adults, and no spread to linked plants.",
        "capa": "Trace the source genetics, the media and pot lots, the irrigation and runoff connections, the benches, the tools, and the way staff moved between them. Hold linked clone lots until you know where it came from and how far it went.",
        "refs": ["cranshaw-wainwright-2020-rice-root-aphid-cannabis", "ahmed-2024-hemp-pests-florida-jipm"],
    },
    {
        "kind": "arthropod",
        "name": "Fungus gnats",
        "scientific": "Bradysia species",
        "image": "assets/img/ipm-blueprint/02-fungus-gnat.webp",
        "alt": "AI-generated educational reconstruction of fungus gnat adult and larva at cannabis media",
        "scale": "The plate is not to scale. Adults are roughly 2-4 mm (0.08-0.16 in) long and easy to see over the media. Confirming them takes about 30x-60x: enough to see the shiny black head on a larva, or the wing veins and body shape of an adult.",
        "identify": "Adults are delicate dark flies with long legs and long antennae. Larvae are translucent, legless and wormlike, with one obvious shiny black head capsule at the front.",
        "signs": "Adults run or fly weakly over wet media. Larvae live where algae, dying roots and slime films are. Feeding on root hairs slows young plants, and the wounds left behind can interact with root disease.",
        "biology": "Eggs and larvae are in the growing medium. The larva becomes a pupa there, and only the adult flies. Anything sprayed on the canopy misses most of the population.",
        "inspect": "Read the yellow cards set low near the media, put down potato slices or take media samples to find larvae, and check irrigation uniformity, standing water, algae and organic debris.",
        "confirm": "Wing veins and body shape on an adult, or the black head capsule on a larva, under a loupe or microscope. Keep the specimens if winged root aphids are a possibility.",
        "lookalikes": "Winged root aphids, shore flies, harmless small flies, and the poor rooting caused by Pythium.",
        "threshold": "Any larvae in propagation deserve action. Elsewhere, set a trend threshold for the site: a count rising across several cards matters far more than one adult on one card.",
        "response": "Dry the media surface as far as the crop allows, remove algae and repair leaks, clean the drains, target the larvae with an approved root-zone biological programme, and use the cards to confirm adults declining over the next life cycle.",
        "development": "Egg to adult commonly runs about 18-28 days, with temperature, moisture, substrate and available food all moving that figure. Track eggs, larvae, pupae and adults separately, because a card count measures adults only, not the population.",
        "controls": "Cultural: remove algae, debris and standing reservoirs, and repair leaks. Environmental: let the surface dry back as far as the crop safely permits, and correct poor drainage. Biological: use lawful nematodes or media-dwelling predators against the larvae. Approved input: keep any drench or surface treatment inside its authorised use and aimed at the stage it actually affects.",
        "targeting": "The damaging stage is the larva in the upper moist substrate and root zone. Cards tell you what the adults are doing; they do not control anything. Watch media and cards together across one full cycle.",
        "constraints": "Do not push dryback past what the crop tolerates. Before any input, check that root-zone biologicals will survive it, what it does to the irrigation system, the crop stage, the PPE and REI on the label, and the residue route.",
        "specimen": "Seal labelled adults or card sections in one container and a media or root sample containing larvae in another. Record the plant, zone, trap height and how wet the media was, and send anything unidentified for microscopy.",
        "recheck": "Count live larvae at the same media points and adults on the same mapped cards at the site interval, through one full generation. Success is a falling trend that holds, with no root injury in propagation.",
        "capa": "Look at irrigation uniformity, leaks, algae and slime films, drains, incoming media, propagation hygiene, and any root disease appearing at the same time.",
        "refs": ["cloyd-2015-fungus-gnat-ecology-management", "ahmed-2024-hemp-pests-florida-jipm"],
    },
    {
        "kind": "arthropod",
        "name": "Thrips",
        "scientific": "Frankliniella occidentalis and other thrips species",
        "image": "assets/img/ipm-blueprint/03-thrips.webp",
        "alt": "AI-generated educational reconstruction of thrips and feeding injury on cannabis",
        "scale": "The plate is not to scale. Adults and larvae are found by inspecting plant parts closely; about 30x-60x resolves the pale larvae, the fringe on the adult wings, and the detail needed to separate species or find eggs pushed into the tissue.",
        "identify": "Adults are slender, with narrow wings fringed in fine hairs. The larvae are smaller and pale. Feeding scrapes cells empty and leaves silvery streaks or patches, usually with small black dots of frass, the term for insect droppings.",
        "signs": "Silvering, distorted young leaves, scarring on flowers, and dark specks. Adults and larvae hide in folds and inside flowers. The stages between larva and adult often sit in the media or in debris rather than on the plant.",
        "biology": "Eggs are pushed into plant tissue, where a spray cannot reach them. Larvae feed on the plant. The next stages do not feed and shelter in protected places, and then the adults return to the canopy.",
        "inspect": "Blue or yellow cards, tapping flowers over white paper, close inspection of young folded leaves and flowers, and samples of the media and debris where they pupate.",
        "confirm": "A loupe or microscope. Getting to species matters when you are choosing a specialist biological control, or judging the risk of the thrips carrying a virus.",
        "lookalikes": "Mechanical abrasion, wind burn, oedema, and injury from an earlier spray.",
        "threshold": "Zero tolerance in quarantine and clean stock. In production, one confirmed hotspot or a card count rising across repeated reads triggers the site response level.",
        "response": "Contain the hotspot. Remove badly damaged tissue carefully, so you do not shake insects loose across the room. Treat both the canopy and the sheltered stages off the plant. Confirm the beneficials in the room will tolerate whatever you use, then re-read the mapped cards after the recheck window closes.",
        "development": "A generation often runs about 14-21 days in warm indoor conditions, though species and temperature both matter. Eggs sit inside plant tissue, larvae feed on the crop, the non-feeding stages hide in sheltered places, and adults disperse.",
        "controls": "Cultural: refuse infested stock, bag hotspots, and clear debris. Environmental: remove sheltering weeds and debris and correct canopy conditions that suit them. Biological: use lawful predators or parasitoids matched to the species and the stage. Approved input: choose a lawful contact or microbial option that reaches the target without collapsing the beneficials.",
        "targeting": "Aim at the feeding larvae on young leaves and flowers, and at the sheltered stages off the plant. Adults move and eggs sit inside tissue, so one contact pass is never the whole job; plan the monitoring and the repeat timing around that.",
        "constraints": "Which species you have can decide which biological agent works. Flower contact, residues that harm beneficials, crop-stage quality, the PPE and REI on the label, and what the residue means at testing all narrow the choice.",
        "specimen": "Collect larvae and adults from a mapped hotspot into labelled sealed vials, and keep a symptomatic leaf or flower separately. Record which card and which plant part they came from, so the identifier has the context.",
        "recheck": "Repeat the tap tests, the plant inspection and the mapped card counts at the approved interval through one full generation. Success is no feeding larvae, a falling adult count, and nothing spreading beyond the original hotspot.",
        "capa": "Trace incoming plants, cut flowers and packaging, doors and screens, weeds, tools, the order staff move through rooms, and debris in the substrate. Identify the species if control is underperforming, or if the virus risk differs between them.",
        "refs": ["pulkoski-burrack-2023-piercing-sucking-hemp", "ahmed-2024-hemp-pests-florida-jipm"],
    },
    {
        "kind": "arthropod",
        "name": "Two-spotted spider mite",
        "scientific": "Tetranychus urticae",
        "image": "assets/img/ipm-blueprint/04-two-spotted-spider-mite.webp",
        "alt": "AI-generated educational reconstruction of two-spotted spider mites, eggs and webbing on cannabis",
        "scale": "The plate is not to scale. Work leaf by leaf on the undersides with a 10x-30x loupe, and move to a microscope wherever the two-spot pattern, the eggs, or the difference from a beneficial mite is uncertain.",
        "identify": "Oval mites with two dark patches on the back, round translucent eggs, and colonies on the undersides of leaves. Fine silk webbing appears as numbers rise.",
        "signs": "Fine pale stippling first, then bronzing, leaf decline, and webbing across petioles, shoots and flowers. Hot, dry pockets in the canopy usually show it first.",
        "biology": "Egg, a six-legged larva, two nymph stages and the adult, often all present at once. Development speeds up sharply with warmth, so a small patch can change character in days.",
        "inspect": "Map the hot, dry zones first. Check leaf undersides with a 10x-30x loupe, tap foliage over white paper, and follow any webbing back to the live colony that made it.",
        "confirm": "Microscopy for the two-spot pattern and the life stages. Separate them from beneficial mites before treating anything.",
        "lookalikes": "Spray stipple, nutrient flecking, dust, and beneficial mites.",
        "threshold": "Any confirmed colony in quarantine or on mothers. In veg and flower, one colony that is reproducing is enough to trigger containment; do not wait for webbing.",
        "response": "Flag and isolate the hotspot, restrict staff and tools moving through it, bag the worst leaves, and correct extreme hot, dry pockets. Release the approved predator programme, or another lawful compatible control. Judge the result on live mites, not on leaf damage, which cannot heal.",
        "development": "Egg to adult may take roughly 7-14 days, faster as canopy temperature rises. Survey eggs, the six-legged larva, both nymph stages and adults, because indoors they overlap as a matter of course.",
        "controls": "Cultural: refuse infested stock, bag hotspot leaves, and stop spread by contact. Environmental: fix extreme hot, dry pockets without creating a humid one that invites disease. Biological: deploy a currently lawful predatory-mite programme early. Approved input: only a compatible lawful contact or microbial option that can actually reach leaf undersides.",
        "targeting": "Live mites and eggs on leaf undersides, and the leading edge of the hotspot. Colonies inside webbed flowers are both harder to reach and more costly to the batch.",
        "constraints": "Old stippling does not measure whether a treatment worked. Check residues against the predators, flower contact, crop stage, the label PPE and REI, the residue route, and the risk of leaf burn before any input.",
        "specimen": "Bag labelled leaves from the leading edge with live mites on them, keep the samples cool and intact, and prepare a slide or tape mount separately if the laboratory asks for one. Note the hotspot temperature and where the plant sits.",
        "recheck": "Recount live mites and eggs on the same mapped leaves and at the hotspot edge after the approved interval, and again before one full generation closes. Success is no outward spread and a decline in live stages that holds.",
        "capa": "Trace plant-to-plant contact, staff and tools, carts, incoming stock, and hot dry dead zones. Review why detection was late, and whether an incompatible residue stopped the predators establishing.",
        "refs": ["pulkoski-burrack-2023-piercing-sucking-hemp", "ahmed-2024-hemp-pests-florida-jipm"],
    },
    {
        "kind": "arthropod",
        "name": "Broad mite",
        "scientific": "Polyphagotarsonemus latus",
        "image": "assets/img/ipm-blueprint/05-broad-mite.webp",
        "alt": "AI-generated educational reconstruction of broad mites and ridged eggs on cannabis meristem",
        "scale": "The plate is not to scale. Adults are under about 0.2 mm (0.008 in), which is below what the eye can resolve. Inspect intact shoot tips and the distinctive eggs at roughly 20x-60x, and go to a compound microscope to confirm.",
        "identify": "Microscopic pale mites on the softest, newest tissue. The eggs are the useful diagnostic: oval, and decorated with pale raised dots or ridges.",
        "signs": "New growth that is hardened, blistered, glossy or twisted, short internodes, and damaged shoot tips. The symptoms stay behind after the mites have gone.",
        "biology": "They concentrate on the protected new growth, and travel on plant material, on workers and on equipment. At their size, looking for them without magnification is not a reliable way to find them.",
        "inspect": "Sample the youngest distorted tissue, the bases of petioles, and the shoot tips. Mount tape or pieces of leaf for a dissecting or compound microscope.",
        "confirm": "Mites under the microscope plus the characteristic eggs. Confirm before changing the feed or reaching for a rescue treatment, because the symptoms have several other causes.",
        "lookalikes": "Leaf edges curling from heat or light, herbicide or spray injury, nutrient toxicity, stunting caused by a virus or viroid, and fasciation, a genetic distortion of the growing point.",
        "threshold": "Zero tolerance in quarantine, mothers and propagation. Any confirmed find in production is serious, because by the time you can see it the infestation is old.",
        "response": "Isolate, and usually remove, confirmed clean-stock plants. Trace the clones and the movements. Sample tips more intensively. Choose a control that is currently lawful and fits the crop stage. Judge the result on new growth and microscopy, not on old distorted leaves.",
        "development": "In a warm, humid crop a generation can close in roughly 4-7 days. When timing controls, account for the ornamented egg, the six-legged larva, the still and sheltered stage between larva and adult, and the microscopic adult.",
        "controls": "Cultural: reject infested stock, isolate the tips, and remove confirmed clean-stock plants. Environmental: correct excess heat and humidity, without pretending one setpoint suits every room. Biological: use a currently lawful predator with evidence against broad-mite stages. Approved input: limit use to a lawful option that reaches the shoot tip and is compatible with the predators and the crop stage.",
        "targeting": "Eggs and moving mites inside shoot tips, folded leaves and petiole bases. The resting and sheltered stages sit where sprays do not reach, so coverage and repeat timing decide the outcome.",
        "constraints": "Diagnosis needs a microscope, because the symptoms outlast the mites. Protect the beneficials, and settle flower contact, crop stage, label PPE and REI, residues and leaf-burn risk before any input.",
        "specimen": "Collect several intact symptomatic shoot tips from the leading edge into labelled sealed bags, keep them cool, and prepare tape or leaf mounts by the laboratory method without crushing the tip.",
        "recheck": "Put several new tips from the hotspot and its perimeter under the microscope after the approved interval and through one full generation. Success is repeated absence of live mites and eggs, normal new growth, and no expansion of the affected area.",
        "capa": "Trace source plants and clones, worker and tool movement, carts, nearby crops, and any treatment that masked the symptoms. Hold linked propagation material until microscopy clears it.",
        "refs": ["vanmaanen-2010-broad-mite-swirskii-biocontrol", "pulkoski-burrack-2023-piercing-sucking-hemp", "ahmed-2024-hemp-pests-florida-jipm"],
    },
    {
        "kind": "arthropod",
        "name": "Hemp russet mite",
        "scientific": "Aculops cannabicola",
        "image": "assets/img/ipm-blueprint/06-hemp-russet-mite.webp",
        "alt": "AI-generated high-magnification educational reconstruction of hemp russet mites on cannabis",
        "scale": "The plate is not to scale. Adults are under about 0.2 mm (0.008 in) and the eggs may be around 20 micrometres (0.0008 in). Inspect several stem, petiole and flower samples at roughly 60x-100x, or send them to a diagnostic laboratory.",
        "identify": "Extremely small, pale, tapered and wormlike mites with only two pairs of legs, both near the head. High magnification is not optional here.",
        "signs": "Dull bronzing or russeting, brittle petioles, curled leaf margins, weak new growth, and flower quality falling away. The damage tends to climb the plant.",
        "biology": "They gather on stems, petioles, leaf surfaces and flowers, and move on air currents, on people, on tools, and by plant-to-plant contact.",
        "inspect": "Take several samples from the leading edge of the symptoms, including petioles, stems and flowers. Use roughly 60x-100x, or a diagnostic laboratory.",
        "confirm": "Specialist microscopy. One clean sample does not clear a symptomatic plant, because the mites sit in patches rather than evenly.",
        "lookalikes": "Broad-mite injury, leaves curling from heat or light, nutrient problems, drought, and the poor vigour associated with hop latent viroid (HLVd).",
        "threshold": "Zero tolerance in quarantine, mothers and propagation. One confirmed plant in production triggers containment and trace-back.",
        "response": "Stop plant contact and plant movement. Bag confirmed plants as the site procedure directs. Sample the cohorts linked to them. Review airflow and tool routes as carriers. Apply only lawful, compatible measures inside the crop-stage window, and require repeated negative microscopy before closing the event.",
        "development": "A generation may take roughly 7-10 days in warm indoor conditions, with the plant and the environment moving that figure. Track eggs, larvae, nymphs and the tapered adult. Every active stage keeps the two pairs of legs near the head, and populations migrate upward through the plant.",
        "controls": "Cultural: exclude infested stock, stop plant contact, and bag confirmed high-consequence plants. Environmental: review airflow and heat or dryness stress, without treating climate as a way to eradicate them. Biological: use only a lawful predator with evidence against this group of mites. Approved input: choose a lawful tactic, confirmed under high magnification, that suits the crop stage and the biologicals already present.",
        "targeting": "The leading edge of the symptoms on stems, petioles, young leaves and flowers. Sample at several heights, because the mites move upward and sit in patches.",
        "constraints": "Confirmation at high magnification is mandatory. Late flower sharply narrows what may touch the crop; check beneficial compatibility, label PPE and REI, residues, quality and leaf burn.",
        "specimen": "Collect several labelled stem, petiole, leaf and flower pieces from the leading edge, plus material from linked plants that look healthy. Keep them cool and sealed, and submit them intact for specialist microscopy.",
        "recheck": "Repeat the 60x-100x or laboratory counts at the same mapped heights and along the leading edge after the approved interval and across one full generation. Closure requires repeated negative samples and no new upward spread.",
        "capa": "Trace genetics, clone cohorts, plant contact, airflow, staff and tools, and how sensitive the sampling was. Hold linked clean-stock material, and review any clearance that later proved wrong.",
        "refs": ["pulkoski-burrack-2023-piercing-sucking-hemp", "ahmed-2024-hemp-pests-florida-jipm"],
    },
    {
        "kind": "arthropod",
        "name": "Whiteflies",
        "scientific": "Trialeurodes vaporariorum, Bemisia tabaci complex and related species",
        "image": "assets/img/ipm-blueprint/07-whitefly.webp",
        "alt": "AI-generated educational reconstruction of whitefly adults and nymphs on cannabis leaf underside",
        "scale": "The plate is not to scale. Adults are roughly 1-2 mm (0.04-0.08 in) and obvious once disturbed. The eggs, the mobile first-stage crawlers, the fixed nymphs and the red-eyed late stage all sit on the underside and need about 30x-60x; naming the species needs a specialist.",
        "identify": "White, powdery, moth-like adults that lift off the underside of a leaf when it is disturbed. The eggs, the crawlers and the flat scale-like nymphs stay on the underside, and older nymphs may show red eyes.",
        "signs": "General yellowing, sticky honeydew, black sooty mould growing on it, and clouds of adults when foliage is disturbed. The nymph stages are easy to walk past.",
        "biology": "Only the first nymph stage, the crawler, moves any distance; after that the nymphs settle and feed in one place. Species and stage both change how well a parasitoid performs and which control fits.",
        "inspect": "Turn leaves in the lower and mid canopy, count how many carry nymphs, run yellow cards at canopy height, and inspect wherever honeydew or sooty mould has appeared.",
        "confirm": "Microscopy, or specialist species identification whenever the biological programme depends on which species it is.",
        "lookalikes": "Powdery mildew, small moths, cast aphid skins, and harmless white debris.",
        "threshold": "Zero tolerance at entry. In production, any underside colony that is reproducing, or a card count rising over successive reads, triggers action before the adults disperse.",
        "response": "Contain the zone, bag heavily colonised leaves, tighten underside scouting, and deploy only approved biologicals matched to the species, or a compatible lawful input. Verify on both measures: adults on the cards and live nymphs on the leaves.",
        "development": "Egg to adult commonly takes about 21-28 days in warm indoor conditions, with species and temperature changing the range. Account for the egg, the mobile crawler, the fixed scale-like nymph and its red-eyed late stage, and the winged adult.",
        "controls": "Cultural: exclude infested plants, bag colonised leaves, and remove weeds and other reservoirs. Environmental: fix stagnant hot spots without pushing humidity up. Biological: use lawful predators or parasitoids matched to the confirmed species. Approved input: only a lawful option that reaches leaf undersides and leaves the parasitoids and the crop stage intact.",
        "targeting": "Crawlers and young nymphs on the undersides, while yellow cards track the adults. Settled older nymphs and eggs usually need a second pass timed to the stage.",
        "constraints": "The species decides which parasitoid fits. Check flower contamination, honeydew and sooty mould, residues against the beneficials, label PPE and REI, crop stage, and release testing before any input.",
        "specimen": "Bag labelled underside leaves carrying eggs and nymphs, keep representative adults or card sections separate, and record plant height, card position and any honeydew before sending them for identification.",
        "recheck": "Count live nymphs on the same mapped leaves and adults on the same cards at the approved interval through one full generation. Success is no new colonies and both counts declining and staying down.",
        "capa": "Trace incoming plants, weeds, doors, vents and screens, staff and tools, and whether the biological released actually matched the species. Assess the sooty mould and any product surfaces it reached.",
        "refs": ["pulkoski-burrack-2023-piercing-sucking-hemp", "ahmed-2024-hemp-pests-florida-jipm"],
    },
    {
        "kind": "arthropod",
        "name": "Foliar aphids",
        "scientific": "Phorodon cannabis, Myzus persicae, Macrosiphum euphorbiae and others",
        "image": "assets/img/ipm-blueprint/08-cannabis-aphid.webp",
        "alt": "AI-generated educational reconstruction of cannabis aphids on a cannabis shoot",
        "scale": "The plate is not to scale. Colonies and adults are visible on shoots and leaf undersides; about 30x-60x resolves the cornicles, the cast skins, the nymphs, and the characters used to separate species.",
        "identify": "Soft, pear-shaped insects with a pair of tube-like cornicles near the rear. A colony holds nymphs, wingless adults, white cast skins, and sometimes winged adults.",
        "signs": "Clusters on shoots, stems, leaf undersides or flowers; growth curling and distorting; sticky honeydew, and the black sooty mould that follows it.",
        "biology": "Under crop conditions the females give birth to live young without mating, so a colony builds quickly from a single individual. Crowding then produces winged adults that leave and start new colonies.",
        "inspect": "Examine growing tips, leaf undersides, petioles and flowers. Map where the honeydew is. Read yellow cards for winged adults. Learn to tell aphids from the beneficial larvae that hunt them.",
        "confirm": "Identify to species when choosing a specialist parasitoid. Cannabis aphid, green peach aphid and potato aphid are not interchangeable targets.",
        "lookalikes": "Whitefly nymphs and cast skins, scale insects, beneficial larvae, and winged root aphids.",
        "threshold": "Zero tolerance in clean stock. One reproducing colony in production triggers local containment and a survey of the whole room.",
        "response": "Bag badly infested tips. Control any ant activity. Keep honeydew off tools and clothing, so it is not carried around the room. Choose lawful biologicals matched to the species, or a compatible input, and then recheck for living aphids and for new nymphs being born.",
        "development": "In warm indoor conditions a generation may be roughly 7-10 days. Live-born nymphs mature into wingless adults, and crowding or stress produces winged dispersers, with generations overlapping.",
        "controls": "Cultural: exclude stock, bag infested tips, control ants, and remove weeds. Environmental: correct plant stress, but do not expect climate alone to control aphids. Biological: use lawful predators or parasitoids matched to the aphid species. Approved input: choose a lawful contact or microbial option compatible with the beneficials and the crop stage.",
        "targeting": "Exposed nymphs and wingless adults on growing tips, undersides, petioles and flowers. Track winged adults on yellow cards, and repeat, because new nymphs keep arriving.",
        "constraints": "Species identity can decide whether a parasitoid works at all. Honeydew on flowers is a quality risk in its own right. Check residues against the beneficials, the crop stage, label PPE and REI, and what the residue means at testing.",
        "specimen": "Collect live wingless adults, winged adults and nymphs from a mapped colony into labelled sealed vials, keep a symptomatic tip separately, and record which part of the plant they came from.",
        "recheck": "Recount living aphids and newborn nymphs on the same marked tips, plus winged adults on the mapped cards, after the approved interval and across one full generation. Success is the colony gone, or an approved decline that holds without spread.",
        "capa": "Trace incoming stock, weeds, ants, staff and tools, and whether the biological released matched the species. Assess where honeydew landed and which clean-stock lots are linked.",
        "refs": ["cranshaw-2018-phorodon-cannabis-north-america", "pulkoski-burrack-2023-piercing-sucking-hemp"],
    },
    {
        "kind": "arthropod",
        "name": "Budworms and caterpillars",
        "scientific": "Lepidopteran larvae; species confirmation required",
        "image": "assets/img/ipm-blueprint/15-budworm-caterpillar.webp",
        "alt": "AI-generated educational reconstruction of caterpillar damage and frass inside a cannabis flower",
        "scale": "The plate is not to scale. Open the whole flower and work through the interior for larvae, bore holes and pellet-like frass; about 30x-60x is for eggs, very small larvae, or the features used to identify the species.",
        "identify": "A chewing larva in foliage or flowers, with bore holes and pellets of frass. Injury inside a flower opens a wound that Botrytis can enter.",
        "signs": "Missing tissue, bored flowers, frass, browning in one spot, and a single wilted sugar leaf. The damage can stay hidden until the flower is opened.",
        "biology": "Eggs hatch into feeding larvae, and the pupae and adults may be outside the crop entirely. Keeping them out is far more reliable than trying to rescue a flower they have already entered.",
        "inspect": "Check entry points and screens, look for flowers with frass or a wilted leaf, and open flowers destructively where the risk justifies it.",
        "confirm": "Larval features, or specialist identification. Open the damaged flower to separate insect injury from a Botrytis infection that started on its own.",
        "lookalikes": "Botrytis with no insect involved, mechanical flower damage, and broken stems.",
        "threshold": "Zero tolerance in indoor production. Any finding in a flower is a quality event immediately.",
        "response": "Remove and bag the larva with the affected flower, inspect the neighbouring plants, close the route it came in by, assess the flower for secondary rot, and use a lawful crop-stage-appropriate control only where it is justified.",
        "development": "Timing depends on the species and the temperature, so identify the larva before setting any interval. Treat the egg, the feeding larva, the pupa and the adult as four separate things to look for.",
        "controls": "Cultural: maintain exclusion screens, inspect entry points, and bag larvae and damaged flowers. Environmental: reduce host plants and entry pressure outside without compromising ventilation. Biological: consider only a lawful organism appropriate to the species. Approved input: treating a flower late is a legal and quality decision of last resort, not a default.",
        "targeting": "Eggs and small exposed larvae, before they get inside a flower. Once a larva is inside a cola, removing it and assessing the rot that follows beats any attempt at surface coverage.",
        "constraints": "Species confirmation matters. Any flower treatment has to clear crop stage, residues, microbial quality, compatibility with the beneficials, label PPE and REI, and market release.",
        "specimen": "Seal the larva and the damaged flower with its frass in separate labelled containers, photograph the bore site, and keep the specimen intact for identification.",
        "recheck": "Inspect neighbouring flowers and entry points daily through the containment window. Success is no new frass, bore holes, larvae or secondary rot across the risk period the site has set.",
        "capa": "Trace doors, screens, incoming plants and materials, host plants outside, night work, and staff movement. Assess the linked flowers and the Botrytis risk as a quality event.",
        "refs": ["ahmed-2024-hemp-pests-florida-jipm"],
    },
    {
        "kind": "disease",
        "name": "Powdery mildew",
        "scientific": "Golovinomyces and related powdery-mildew fungi on cannabis",
        "image": "assets/img/ipm-blueprint/09-powdery-mildew.webp",
        "alt": "AI-generated educational reconstruction of early powdery mildew colonies on cannabis leaf",
        "scale": "The plate is not to scale. Look over whole leaves, stems and flowers under angled light, then examine a single colony at about 30x-60x. Go to microscopy or a laboratory whenever spray residue or trichomes remain a plausible explanation.",
        "identify": "Raised, patchy white colonies growing on the surface of living leaves, petioles, stems or flowers. Early colonies are separate discrete patches rather than an even dusting.",
        "signs": "Dull pale spots that develop visible surface growth and spores. Colonies expand and release airborne spores that start the next round of infections.",
        "biology": "The fungus grows on the surface and feeds from the cells just beneath it. Dense canopies, susceptible genetics and still air all help it spread, and it does not need free water on the leaf to do so.",
        "inspect": "Use angled light across leaves and stems, work through the lower and inner canopy and the flowers, mark single colonies on the map, and check the finding against recent spray records.",
        "confirm": "A hand lens or microscope to see the fungal structures. Send it to a laboratory when dried spray, mineral residue, trichomes or dust make the call uncertain.",
        "lookalikes": "Dried foliar spray, mineral residue, dust, trichomes, and light reflecting off the leaf.",
        "threshold": "Zero tolerance in quarantine and on mothers, and for any colony on a flower. A single colony on a vegetative plant triggers containment and intensified scouting room-wide.",
        "response": "Bag affected tissue without shaking it, restrict movement through the room, open up canopy density and fix humid dead-air pockets, use only a lawful measure that suits the crop stage, and judge the result on whether new colonies appear rather than on old scarring.",
        "development": "In canopy conditions that suit it, germination begins within hours, and visible colonies producing a new round of spores can develop over several days. Cultivar and local conditions move that interval.",
        "controls": "Cultural: exclude infected stock, bag lesions, and clean the things that carry spores. Environmental: correct dense dead-air zones and humidity or dew-point excursions. Biological: use only a lawful preventive antagonist with evidence against this pathogen. Approved input: choose a lawful crop-contact option suited to the tissue and the growth stage.",
        "targeting": "The first surface colonies and any new spread on leaves and stems. Once a flower is infected it is a quality event, and the room for intervention narrows sharply.",
        "constraints": "Do not mistake residue for infection. Flower contact, visible residues, compatibility with the beneficials, label PPE and REI, crop stage, leaf burn and release testing all constrain the choice of input.",
        "specimen": "Photograph and bag an intact colony together with some adjacent healthy tissue, using clean tools. Keep the recent spray records with it, and submit it dry and cool by the laboratory instruction.",
        "recheck": "Return to the mapped sites with angled light and microscopy after the approved interval, and again inside the window in which a new round of spores would appear. Success is no new colonies and no growth of the existing ones.",
        "capa": "Investigate the source stock, staff and tools, airflow, canopy density, humidity and dew point during lights-off, cultivar susceptibility, and which flowers and batches were affected.",
        "refs": ["scott-punja-2021-powdery-mildew-management", "punja-2021-emerging-diseases-cannabis"],
    },
    {
        "kind": "disease",
        "name": "Botrytis bud rot",
        "scientific": "Botrytis cinerea",
        "image": "assets/img/ipm-blueprint/10-botrytis-bud-rot.webp",
        "alt": "AI-generated educational reconstruction of internal Botrytis bud rot in a cannabis cola",
        "scale": "The plate is not to scale. Diagnose at whole-flower scale and then by opening the flower, looking at the edge of the lesion and any spore growth with a hand lens. Use laboratory microscopy or culture when the species affects what happens to the batch.",
        "identify": "Tissue inside the flower turns tan to brown and collapses, and grey dusty spore growth may follow. A single wilted sugar leaf is often the first thing visible from outside.",
        "signs": "One leaf wilting, soft or dry dead tissue inside a dense flower, grey mould, and rapid spread through tissue that touches in humid conditions.",
        "biology": "Spores enter tissue that is susceptible, wounded or ageing. Dense flowers hold humid air inside them. Sclerotia, the hard survival bodies this fungus forms, and infected debris can carry it from one crop into the next.",
        "inspect": "Check high-risk flowers daily, opening any dense bud that looks suspicious. Track cultivar, zone, irrigation events, night humidity, and any handling injuries.",
        "confirm": "The characteristic internal decay and spore growth. Use a diagnostic laboratory where what happens to the batch depends on confirming the species.",
        "lookalikes": "Caterpillar damage, mechanical bruising, normal senescence, and other flower rots.",
        "threshold": "Any confirmed flower is an immediate containment event with consequences for the batch.",
        "response": "Stop movement, and stop the fans that would carry spores while material is being removed. Bag a generous margin around the affected tissue. Inspect the neighbours. Hold the implicated lot as the site procedure requires. Correct humidity, airflow and canopy density. Open a corrective and preventive action if this is more than an isolated find.",
        "development": "With sustained high humidity and susceptible tissue, an infection may reach visible decay and spore growth in roughly 3-5 days. Temperature, how long the tissue stays wet, wounds, and the shape of the flower all control the pace.",
        "controls": "Cultural: remove ageing and wounded tissue, and bag affected flowers. Environmental: prevent condensation, prolonged wetness, and dense stagnant zones inside the canopy. Biological: use only a lawful preventive antagonist with relevant evidence. Approved input: use in late flower needs explicit legal, quality and residue approval.",
        "targeting": "Stop spores infecting wounded or ageing tissue, and remove the lesions inside the flower. A surface spray cannot bring dead flower tissue back.",
        "constraints": "Any affected flower has consequences for the batch and its microbial quality. Handle material so it does not release spores, and settle crop stage, worker PPE and REI, residues, compatibility and release testing before any input.",
        "specimen": "Stop local airflow, photograph the flower in place, then bag an unopened suspicious flower and the edge of the lesion using clean tools. Keep it cool, and submit it separately from healthy comparison samples.",
        "recheck": "Check mapped flowers daily during containment, and repeat the destructive inspection at the approved interval. Success is no new internal decay or spore growth anywhere in the affected zone.",
        "capa": "Link cultivar and flower structure, injury, canopy density, humidity and dew point during lights-off, airflow, sanitation, staff and tools, and every lot or batch implicated.",
        "refs": ["mahmoud-2023-botrytis-budrot", "punja-2021-emerging-diseases-cannabis"],
    },
    {
        "kind": "disease",
        "name": "Pythium root, crown rot and damping-off",
        "scientific": "Pythium species (oomycetes)",
        "image": "assets/img/ipm-blueprint/11-pythium-root-rot.webp",
        "alt": "AI-generated educational reconstruction of Pythium-like root rot in cannabis roots",
        "scale": "The plate is not to scale. Compare the whole root mass, individual root tips, the outer root layer and the crown against healthy white roots. Identifying what caused it takes a diagnostic laboratory: microscopy, culture or molecular testing.",
        "identify": "Water-soaked tan to brown roots whose outer layer is weak and may slide off, poor root tips, seedlings collapsing, or rot at the crown. Compare against firm, bright white healthy roots.",
        "signs": "Poor rooting, wilting in the middle of the day even though the media is wet, yellowing, slow water uptake, collapse at the stem base, and matching symptoms along a shared water circuit.",
        "biology": "Thick-walled resting spores persist in the system. The organism also produces swimming spores that travel in water. Warm root zones, low dissolved oxygen, saturation and slime films can raise the risk, though species differ.",
        "inspect": "Roots, crown, drain water, slime film in tanks and lines, root-zone temperature, dissolved oxygen, irrigation frequency, standing water, and every cohort sharing the same water.",
        "confirm": "A plant diagnostic laboratory, by microscopy, culture or molecular testing. Root colour on its own does not identify the organism.",
        "lookalikes": "Root death from non-living causes, oxygen starvation without infection, Fusarium, salt injury from nutrients, and the normal browning of old roots.",
        "threshold": "Any cluster of collapsed seedlings, any crown rot, or any pattern following a shared water circuit triggers isolation and an investigation of the water system.",
        "response": "Stop sharing water and material. Remove collapsed plants. Take the samples before sanitising anything, because cleaning destroys the evidence. Correct root-zone oxygen, moisture and temperature faults. Clean slime films under a validated procedure, and use only a lawful approved biological or input programme.",
        "development": "Swimming spores can infect susceptible root tips quickly, and symptoms may build over days in systems that are warm, low in oxygen or saturated. Species, plant age and root-zone conditions all change the course.",
        "controls": "Cultural: start with clean stock and clean media, and isolate affected water circuits. Environmental: correct saturation, heat, low dissolved oxygen, standing water and slime films. Biological: use only a lawful preventive antagonist suited to the reservoir. Approved input: keep the distinction clear between something that touches the crop or roots and a validated cleaning of lines or surfaces.",
        "targeting": "Prevention at the root tips and crowns, and the spores travelling in the water. Sample before sanitation. Roots that are already dead need removing and the system correcting; nothing brings them back.",
        "constraints": "Many sanitisers kill the antagonists you rely on. Confirm root-zone use, the status of the strain or product, crop stage, worker PPE and REI, the residue route, compatibility with the reservoir, and how the discharge is controlled.",
        "specimen": "Collect roots and crown from the edge of the lesion, media, and water from the linked tank and return line, all before cleaning, into separate sterile labelled containers. Keep them cool, and keep the record of which circuit and lot each came from.",
        "recheck": "Reinspect root tips and crowns and the linked cohorts, and repeat the validated water or root test after the approved interval. Success is healthy new white roots, no further collapse, and no spread to linked plants.",
        "capa": "Investigate the propagation source, the water circuit, temperature and dissolved oxygen, saturation and dryback, slime films, hoses and trays, tools, staff, and every connected cohort.",
        "refs": ["sutton-2006-pythium-hydroponic-etiology", "punja-2023-fusarium-pythium-biocontrol", "punja-2021-emerging-diseases-cannabis"],
    },
    {
        "kind": "disease",
        "name": "Fusarium wilt, root and crown disease",
        "scientific": "Fusarium species complexes",
        "image": "assets/img/ipm-blueprint/12-fusarium-wilt.webp",
        "alt": "AI-generated educational reconstruction of Fusarium-like wilt and vascular browning in cannabis",
        "scale": "The plate is not to scale. Look at the whole plant for one-sided decline, then cut the crown or stem lengthwise and inspect the edges of the root lesions. Naming the organism takes laboratory isolation and molecular identification.",
        "identify": "Wilting or yellowing that progresses, often down one side of the plant, with lesions on the crown and roots and brown staining in the water-conducting tissue inside a cut stem or crown.",
        "signs": "Weak rooting, seedlings collapsing, lesions at the stem base, yellowing, wilt that does not recover as it should, and patterns that follow a batch of stock, tools, media or water.",
        "biology": "Different Fusarium species complexes act as root, crown, vascular or flower pathogens. Spores travel in contaminated water, plant tissue and equipment. They germinate at root tips or wounds, the fungus grows upward inside the water-conducting tissue, and chlamydospores, its thick-walled resting spores, persist in plant and media debris.",
        "inspect": "Cut a symptomatic crown or stem lengthwise and compare the internal tissue against a healthy plant. Inspect the roots. Trace the propagation source, the tools, the media lots and the irrigation connections.",
        "confirm": "Laboratory isolation, plus molecular identification where it is needed. What you do next depends on which disease syndrome this is and where it came from.",
        "lookalikes": "Pythium, drought or oxygen starvation, mechanical root injury, nutrient imbalance, and the poor vigour associated with hop latent viroid.",
        "threshold": "Any confirmed case in clean stock or a clonal line is high consequence. Clustered cases in production are treated as systemic until trace-back proves otherwise.",
        "response": "Isolate, bag and destroy as the site procedure directs. Hold the linked clones. Sample before cleaning. Investigate the stock, tools, media and water. Correct the structural faults found. Do not promise a cure for a plant whose internal tissue is already colonised.",
        "development": "Root infection and internal symptoms can develop over days to weeks, depending on the species complex, how much inoculum is present, temperature, moisture and plant stress. The resting spores persist far longer than that.",
        "controls": "Cultural: use tested stock and clean media and tools, and destroy confirmed vascular cases. Environmental: correct root injury, saturation and heat, without implying that climate cures an infection. Biological: use only a lawful preventive antagonist with evidence for that strain. Approved input: keep preventive root use separate from cleaning lines and surfaces.",
        "targeting": "Prevent entry at root tips and wounds, and stop spores moving between plants. Once the fungus is inside the water-conducting tissue there is no credible cure, so the decisions are about confirmed plants and the pathways that supplied them.",
        "constraints": "Confirming the species and the syndrome matters. Resolve sanitiser and antagonist incompatibility, crop stage, root-zone use, label PPE and REI, the residue route and discharge controls before any input.",
        "specimen": "Collect the edges of root and crown lesions, and a lengthwise stem section that includes both brown and healthy internal tissue, using clean tools. Bag them separately, keep them cool, and record the stock, media and water links.",
        "recheck": "Inspect the linked cohorts for new wilt and internal browning, and repeat laboratory testing on the approved schedule. Success is no new cases after removal and correction; an infected plant recovering is not the measure.",
        "capa": "Trace the mother and clone genealogy, the seed or plant source, tools, media lots, water circuits, root injury, staff movement, and every linked cohort or batch.",
        "refs": ["punja-2023-fusarium-pythium-biocontrol", "punja-2021-emerging-diseases-cannabis"],
    },
    {
        "kind": "disease",
        "name": "Hop latent viroid disease",
        "scientific": "Hop latent viroid (HLVd)",
        "image": "assets/img/ipm-blueprint/13-hlvd-syndrome.webp",
        "alt": "AI-generated educational comparison of healthy cannabis and nonspecific HLVd-like symptoms",
        "scale": "The plate is not to scale. Compare whole plants and clonal groups only to decide what to sample. Confirmation happens at the level of a traceable individual plant, or a validated pooled sample, by RT-qPCR or RT-PCR, not by magnification.",
        "identify": "There is no reliable way to diagnose this by eye. Plants may look entirely normal, or may show shortened internodes, weak vigour, poor rooting, fewer trichomes, and small low-quality flowers.",
        "signs": "A clonal line or a linked hydroponic group underperforms with no environmental cause you can find. The visible symptoms fit many other things, and their absence proves nothing at all.",
        "biology": "The viroid travels in infected vegetative material and moves mechanically on contaminated tools. Research also supports transmission through roots and through recirculated hydroponic solution.",
        "inspect": "Run traceable molecular surveillance across quarantine, foundation mothers and production mothers. Which tissue is sampled, and when, must follow the validated laboratory method.",
        "confirm": "RT-qPCR or RT-PCR only, with the appropriate controls and written rules for repeats and inconclusive results. The generated plate is not diagnostic evidence.",
        "lookalikes": "Root disease, irrigation faults, nutrient imbalance, russet or broad mites, genetically weak plants, and other pathogens that move through the whole plant.",
        "threshold": "Zero tolerance in quarantine, foundation mothers, production mothers and clone-source material.",
        "response": "Quarantine the plant and everything linked to it. Stop clones moving. Confirm the result. Destroy positives under the approved procedure. Hold every daughter taken since the last verified negative test. Investigate tools, the path staff walk, and any shared hydroponic system. Verify the corrective action with follow-up testing.",
        "development": "A cold moves through a household for days before anyone coughs, and it spreads during that stretch, when nobody looks ill. That is what latent means, and it is how this viroid behaves: present and transmissible while the plant still looks normal. There is no dependable visual window, so surveillance timing follows the validated molecular method and the risk schedule for that stock.",
        "controls": "Cultural: admit only tested stock, keep genealogy segregated, sanitise tools between defined plant units, and destroy confirmed positives. Environmental: segregate any recirculating solution that has not been validated, because climate does not clear an infection. Biological: nothing established will cure it. Approved input: sanitisers apply only through a validated, lawful process on tools and surfaces.",
        "targeting": "Target the pathways, meaning exclusion, mechanical transmission and root contact, rather than visible symptoms. Monitor quarantine, foundation and production mothers molecularly, and trace every daughter lot.",
        "constraints": "No photograph, vigour score or absence of symptoms releases stock. Sampling tissue and timing, controls, pooling, repeats and inconclusive rules all follow the validated RT-qPCR or RT-PCR method. Review the PPE, REI and residue implications of sanitisers separately.",
        "specimen": "Collect the validated tissue with single-use or decontaminated tools into the laboratory container. Keep the chain of custody complete: accession, plant, mother, clone lot, collector, time and temperature.",
        "recheck": "Repeat positive and inconclusive results, and test the linked material under the approved method. Success is documented destruction or containment plus verified negative surveillance across the defined trace group, never an apparent improvement in symptoms.",
        "capa": "Trace every daughter taken since the last verified negative, the tool and staff path, the integrity of the sampling, root contact, and shared hydroponic circuits. Hold the affected lots until quality assurance closes the investigation.",
        "refs": ["hlvd_threat2023", "hlvd_mgmt2025", "hlvd-transmission-2025"],
    },
    {
        "kind": "disease",
        "name": "Septoria leaf spot",
        "scientific": "Septoria cannabis, S. neocannabina, S. cannabicola and related diagnoses",
        "image": "assets/img/ipm-blueprint/14-septoria-leaf-spot.webp",
        "alt": "AI-generated educational reconstruction of Septoria-like leaf spot on a lower cannabis leaf",
        "scale": "The plate is not to scale. Inspect the whole lower leaf, then the centres of individual lesions at about 30x-60x for the small dark fruiting bodies. Laboratory microscopy, culture or sequencing is required wherever the species matters.",
        "identify": "Discrete tan, grey-brown or brown leaf spots with yellowed margins. Tiny dark pycnidia, the flask-shaped fruiting bodies of the fungus, may sit in the centres. Spots can merge and strip the lower leaves.",
        "signs": "Lower and older leaves usually show it first. Splashing water, wet foliage and infected debris support spread, although how much it matters indoors varies from site to site.",
        "biology": "Septoria species produce their fruiting bodies and spores inside the lesions. The appearance of a lesion is not enough to assign a species name safely.",
        "inspect": "Map the lesions on lower leaves, look for splash and leaf wetness and infected debris, photograph both sides of the leaf, and review the spray and nutrient history.",
        "confirm": "A plant diagnostic laboratory, by microscopy or culture, and by sequence-based methods where the species matters.",
        "lookalikes": "Nutrient deficiency, chemical splash, Cercospora, Bipolaris and other leaf spots, mechanical injury, and normal senescence.",
        "threshold": "Any confirmed case in quarantine or stock triggers exclusion. In production, repeated lesions or a spreading pattern triggers containment and laboratory work.",
        "response": "Bag the infected debris. Stop splashing, and stop leaves staying wet. Improve airflow. Stop wet tools and clothing moving between rooms. Confirm the diagnosis, and intervene only with a lawful, evidence-supported measure, and only where intervention is justified.",
        "development": "Lesions and fruiting bodies develop over days to weeks, depending on the species, the temperature and how long the leaf stays wet. Splash-driven cycles keep repeating while wet debris remains.",
        "controls": "Cultural: exclude infected stock, bag lesions and debris, and stop wet tools moving between rooms. Environmental: stop splash and prolonged leaf wetness, and improve airflow low in the canopy. Biological: use only a lawful antagonist supported for the confirmed diagnosis. Approved input: choose a lawful crop-contact option only after the laboratory result and a review of whether this matters indoors at your site.",
        "targeting": "Infected lower leaves, debris and the splash pathways, before lesions merge. Protect the new foliage; the dead tissue in existing lesions will not recover.",
        "constraints": "Both the indoor importance and the species identity are site-specific. Flower contact, crop stage, compatibility with the beneficials, label PPE and REI, residues, leaf burn, and the lookalike caused by spray injury all constrain treatment.",
        "specimen": "Photograph both leaf surfaces, and collect several dry leaves from the edges of lesions bearing fruiting bodies, plus a healthy comparison leaf, in separate labelled paper or laboratory-approved packaging. Keep the spray and nutrient history with them.",
        "recheck": "Map and recount new lesions on lower leaves and on newly exposed leaves after the approved interval, and after any wetness event. Success is no new lesions and no spread upward through the observation window.",
        "capa": "Investigate incoming stock, infected debris, overhead splash and irrigation, condensation and leaf wetness, tools and clothing, nutrient or chemical injury, and linked rooms.",
        "refs": ["rahnama-2021-septoria-cannabis", "ujata-2024-septoria-cannabicola", "punja-2021-emerging-diseases-cannabis"],
    },
]


REFERENCE_PLATES = [
    ("Healthy leaf underside", "assets/img/ipm-blueprint/16-healthy-leaf-underside.webp"),
    ("Healthy white roots", "assets/img/ipm-blueprint/17-healthy-roots.webp"),
    ("Healthy shoot tip", "assets/img/ipm-blueprint/18-healthy-meristem.webp"),
    ("Healthy flower interior", "assets/img/ipm-blueprint/19-healthy-flower-interior.webp"),
    ("Fungus gnat beside a winged root aphid", "assets/img/ipm-blueprint/20-gnat-vs-root-aphid.webp"),
    ("Leaf curl from heat and light, no mites present", "assets/img/ipm-blueprint/21-abiotic-tacoing.webp"),
    ("Dried spray residue, not powdery mildew", "assets/img/ipm-blueprint/22-foliar-residue.webp"),
    ("Root stress with no pathogen, which is not yet a diagnosis", "assets/img/ipm-blueprint/23-abiotic-root-stress.webp"),
]


BENEFICIAL_ROWS = [
    ("Canopy predatory mites", "Phytoseiulus persimilis for spider-mite hotspots; Neoseiulus californicus or N. fallacis for broader spider-mite suppression; N. cucumeris or Amblyseius swirskii for thrips larvae and, where the evidence supports it, broad mites or young whitefly stages", "Before calling any of these deployable, confirm the organism's current New Zealand status, whether a supplier can actually deliver it, which pest stage it attacks, whether the room climate suits it, how it is released in sachets or loose, what residues are already present, and whether there is evidence it establishes"),
    ("Canopy predators", "Orius species against thrips life stages, and lacewing larvae against aphids and other exposed soft-bodied prey where the host fit is supported", "Confirm current New Zealand status and supplier availability, then release against the correct prey stage and check how far they disperse, whether there is enough prey to stop them eating each other, the crop stage, and residues that would kill them"),
    ("Aphid parasitoids", "Aphidius species chosen for the confirmed aphid host; cannabis, green peach and potato aphids are not interchangeable targets", "Confirm current New Zealand status, supplier availability and host match. Then monitor the mummies that show parasitism is happening, watch for wasps that attack the parasitoids themselves where that is relevant, and track residues and when a replacement release is due"),
    ("Whitefly parasitoids", "Encarsia formosa or Eretmocerus species chosen for the confirmed whitefly species and nymph stage", "Confirm current New Zealand status and supplier availability, then confirm the whitefly species, the release timing, the climate, the evidence of parasitism, and whether residues in the room are compatible"),
    ("Root-zone predators", "Stratiolaelaps scimitus and, where lawful and available, Dalotia coriaria against fungus-gnat larvae, soil-dwelling thrips stages and other small prey in the media", "Confirm current New Zealand status and supplier availability; check media depth and moisture, whether there is prey for them, whether they arrive alive, how evenly they are distributed at release, the residues present, and whether they establish"),
    ("Beneficial nematodes", "Steinernema feltiae against susceptible fungus-gnat larvae and other supported stages in the media", "Confirm the product and organism are lawful and available; check live and dead morphology on arrival, keep them cold, use them promptly, and check agitation and oxygen in the tank, light exposure, filter and nozzle sizes, and whether a dip, drench or sprench suits"),
    ("Entomopathogenic microbes", "Beauveria and other approved insect-pathogenic strains against the aphid, thrips, whitefly or other stages named on the label", "Confirm the exact strain and product and its New Zealand pathway, then manage storage and viability, the contact and environmental conditions it needs, effects on non-target organisms, worker controls, residues, and the recheck"),
    ("Plant-pathogen antagonists", "Trichoderma, Bacillus or Streptomyces strains for preventive suppression of supported root or foliar pathogens, not for reviving dead tissue or a plant already colonised internally", "Confirm the exact strain and product, its New Zealand status and supplier availability. Keep it away from sanitisers, check it suits the reservoir and the crop, and check storage, whether it colonises, and what evidence exists for the outcome you want"),
]


APPROVED_TOOL_FIELDS = [
    "Product and supplier",
    "Active ingredient / living organism / strain",
    "Target organism and target life stage",
    "Inhalation or segregated non-inhalation pathway",
    "Medicinal-cannabis legal basis",
    "ACVM registration or exemption evidence",
    "EPA approval / HSNO controls and current SDS revision",
    "Label use, crop or contact site, and application method",
    "IRAC or FRAC group, or the physical or biological mode of action",
    "PPE, REI, signage, pre-harvest interval or withholding period, and crop-stage restriction",
    "Analytical method, required limit, and the LOQ achievable in practice",
    "Compatibility with every beneficial organism in the room",
    "Mixing, water quality, calibration and clean-out requirements",
    "Waste, rinse and spill route",
    "Evidence grade, approver, last verification and review due date",
]


SCOUT_FIELDS = [
    "Date and time, scout, room, zone, bench and fixed route point",
    "Plant or lot ID and growth stage",
    "Leaf top, leaf underside, shoot tip, stem and crown, flower, media and roots checked",
    "Trap ID, colour, height, deploy and replace date, and counts by organism",
    "Confirmed organism, life stage, incidence and severity 0-4",
    "Beneficial organism and the evidence it has established",
    "Environmental or root-zone anomaly, and any recent intervention",
    "Photo ID, specimen ID, chain of custody and lab result",
    "Threshold status, containment, owner and due date",
    "Recheck date, success criterion, and close or CAPA decision",
]


GLOSSARY = [
    ("Action threshold", "You set the oven timer before the roast goes in, not while standing over a hot pan wondering. An action threshold works the same way: the observation agreed in advance that turns watching into acting. It may be a count, a trend across several reads, a severity level, or a single confirmed find where the tolerance is zero."),
    ("Alate", "A winged aphid, produced when a colony becomes crowded so that part of it can leave and start elsewhere."),
    ("Antagonist", "A beneficial microorganism that suppresses a plant pathogen, by competing with it for space and food, by producing substances that inhibit it, or by other interactions."),
    ("Asexual", "Reproduction without the fusion of gametes. Indoors, most pest and pathogen populations multiply mainly this way."),
    ("Axil", "The angle where a leaf or branch joins the stem. It is sheltered, which is exactly why it is worth inspecting."),
    ("Biosecurity", "The controls that stop pests and pathogens entering the facility, and stop them moving around once inside."),
    ("Bronzing", "A bronze-brown discolouration caused by feeding injury or stress. It describes what you can see; it does not name what caused it."),
    ("CAPA", "Corrective and preventive action: contain the event, find the cause, fix it, change what allowed it, and then verify that the change worked."),
    ("Chlorosis", "Loss of green colour from plant tissue."),
    ("Conidium / conidia", "A fungal spore produced without sex and used for dispersal; conidia is the plural."),
    ("Cornicle", "One of the pair of short tubes near the rear of an aphid, and the feature that most quickly confirms an aphid is what you are looking at."),
    ("Crown rot", "Disease at the crown, where the stem meets the root system."),
    ("Cupping / tacoing", "Leaf edges curling upward or downward. Heat, humidity, chemical injury and mite feeding all cause it, so look for the organism before deciding which."),
    ("Damping-off", "The sudden collapse of a seedling or cutting caused by root or crown pathogens, commonly Pythium or Fusarium."),
    ("Dew-point margin", "A cold glass sweats in a warm room because its surface sits below the temperature at which the surrounding air has to give up its water. Dew-point margin is that gap measured on your crop: the difference between the temperature of the leaf or surface and the dew point of the air around it. A small margin means condensation is close."),
    ("Dissolved oxygen", "The oxygen carried in the irrigation solution. Roots need it, and when it runs low they are stressed and some root-disease conditions are favoured."),
    ("Dudding", "A production term for weak, stunted cannabis with poor flower development. It describes an appearance and diagnoses nothing; it is not a synonym for HLVd."),
    ("Entomopathogenic", "Able to infect and kill insects or mites; used of the fungi, bacteria and nematodes deployed as biological controls."),
    ("Exclusion", "Everything that keeps a pest, pathogen or unapproved material from entering the controlled crop system in the first place."),
    ("FRAC / IRAC", "Stop a course of antibiotics early and the bacteria left standing are the ones the drug bothered least, and those are the ones that go on to multiply. Repeated use of one mode of action does the same to a pest or pathogen population, which is what resistance means. FRAC and IRAC are the systems that classify fungicides and insecticides by mode of action, so that a programme can rotate between groups instead of reapplying the same pressure."),
    ("Honeydew", "The sticky, sugar-rich liquid excreted by aphids, whiteflies and other sap-feeding insects."),
    ("Incidence", "After a storm you ask two separate questions: how many rooms have a leak, and how wet each one is. Incidence is the first question, the proportion of plants or sites affected, and it is tracked separately from severity, which is the second."),
    ("Inoculum", "Pathogen material capable of starting a new infection, such as spores, infected debris or contaminated water."),
    ("Instar", "The stage an immature arthropod occupies between one moult and the next."),
    ("Larva", "A feeding immature stage that looks nothing like the adult. In fungus gnats, thrips and caterpillars the larva is both the damaging stage and the one worth identifying."),
    ("LOQ", "Limit of quantification: the lowest concentration a laboratory method can report with acceptable performance. Below it, the method cannot give you a number."),
    ("Meristem", "The actively dividing tissue at a shoot tip that produces all the new growth above it."),
    ("Mycelium", "The network of fine threads that makes up the growing body of a fungus."),
    ("Mould / mold", "Visible fungal growth. Mould is the standard New Zealand spelling; mold appears in imported references and means the same thing."),
    ("Necrosis", "Dead plant tissue."),
    ("Nymph", "An immature arthropod that already resembles the adult but is not yet mature."),
    ("Oomycete", "A fungus-like organism from a lineage separate from the true fungi. Pythium is an oomycete, not a true fungus."),
    ("Oospore", "A thick-walled survival spore produced by some oomycetes; it can persist in a system between crops."),
    ("Parasite", "An organism that lives in or on a host and draws resources from it, usually without the one-host lethal outcome that defines a parasitoid."),
    ("Parasitoid", "An organism, in IPM usually a small wasp, whose immature stage develops in or on a single host and kills it."),
    ("Parthenogenesis", "A jar of dough left in the warm doubles overnight with nothing added to it. Parthenogenesis is the equivalent in a pest population: offspring produced without fertilisation, so one female can found a colony and numbers climb without the delay that finding a mate would impose. Several indoor pests reproduce this way."),
    ("Pathogen", "An organism or agent that causes disease."),
    ("Petiole", "The stalk joining a leaf blade to the stem, and a reliable place to look for mites and early symptoms."),
    ("Preventive / curative", "Preventive means applied before a problem establishes, to keep pressure down. Curative means applied after confirmation, to reduce a problem already present."),
    ("Predator", "A beneficial organism that hunts and eats many individual prey across its lifetime."),
    ("Pupa", "The stage between larva and adult in insects with complete metamorphosis. It generally does not feed, and it is often tucked into media or debris where sprays do not reach."),
    ("Pycnidium", "A small flask-shaped fungal fruiting body that produces conidia. In a Septoria lesion it appears as a dark dot in the centre."),
    ("REI", "Restricted entry interval: the period after an application when nobody may enter the treated area unless the specified PPE and conditions are in place."),
    ("Release", "The documented quality decision that allows a held plant, material or batch to move or be supplied, once the required evidence and approvals are complete."),
    ("Residue limit", "The maximum or action limit a residue must sit under for a batch to be released. A substance having a limit is not permission to apply it."),
    ("Rogue / roguing", "To remove a diseased or infested plant from the production system and destroy it."),
    ("Russeting", "Bronze-brown roughened tissue caused by feeding injury or other stress."),
    ("Severity", "How much of an individual plant or site is affected. It is tracked separately from incidence, which is how many are affected at all."),
    ("Sachet", "A small carrier pack that releases beneficial organisms into the crop gradually, provided the conditions it needs are met."),
    ("Sanitation", "Cleaning, and where required disinfection, carried out by a validated method that removes debris and reduces viable contamination on a defined surface or system."),
    ("Scouting", "A repeatable inspection along a mapped route, used to detect, identify, count and trend what is happening to crop health."),
    ("Sooty mould", "A dark fungus that grows on honeydew. It points to sap-feeding insects above it and is not usually the primary plant pathogen."),
    ("Sprench", "An application volume between a spray and a drench, aimed at the plant base and the media surface."),
    ("Spore", "Dried yeast sits inert in a cupboard for months and comes back to life the moment it is warm and wet, which is why debris left between crops still matters. A spore is the reproductive or survival unit produced by a fungus or a fungus-like organism, and its type decides how you sample for it and how you control it."),
    ("Stippling", "The many tiny pale points left where mites or similar pests have emptied individual plant cells."),
    ("Systemic resistance", "A defensive state switched on across a whole plant by some stimulus. It may reduce susceptibility, but it is not evidence of control over a pathogen already established."),
    ("Vector", "Anything that carries a pest or pathogen from one place to another, living or not: an insect, a tool, a pair of hands."),
    ("Viroid", "A small infectious RNA molecule with no protein coat around it, simpler than a virus. HLVd is a viroid."),
    ("Zoospore", "A spore that swims. Oomycetes such as Pythium produce them, which is how the disease travels through a water system."),
    ("ACVM", "The New Zealand regulatory framework for agricultural compounds and veterinary medicines, administered by MPI."),
    ("EPA", "New Zealand's Environmental Protection Authority, which administers approvals and controls for hazardous substances and new organisms."),
    ("HSNO", "The Hazardous Substances and New Organisms Act framework, administered by the EPA."),
    ("Inhalation / non-inhalation line", "The decision about whether a lot may end up being inhaled. It changes which pesticide-active provisions apply and what the quality consequences are, and it must be settled before any input is selected."),
    ("MPI", "New Zealand's Ministry for Primary Industries, which administers ACVM and the biosecurity pathways governing inputs and imported organisms."),
    ("Minimum quality standard", "The statutory quality requirements that medicinal-cannabis ingredients and products must meet before they can be supplied in New Zealand."),
    ("Approved-input register", "The site's controlled list of products and organisms that have passed legal, safety, analytical, compatibility and operational review."),
    ("Batch hold", "A quality status that stops a batch moving or being released while evidence or an investigation is still incomplete."),
    ("Trade waste", "Commercial or industrial liquid waste discharged into the wastewater network under Watercare and Auckland controls."),
]
