# -*- coding: utf-8 -*-
"""Structured source for the Auckland medicinal-cannabis IPM blueprint.

The supplied IPM Book V15 is used as a coverage benchmark only. Wording, branded
programmes and artwork are not reproduced. New Zealand official sources and primary
literature control legal and technical claims.
"""

SLUG = "auckland-ipm-blueprint"
TITLE = "Integrated pest management blueprint for indoor medicinal cannabis in Auckland"
EYEBROW = "Plant health · Auckland medicinal cannabis"
SUB = (
    "An exclusion-first, residue-aware operating system for clean stock, pest and disease "
    "identification, lawful control selection, crop-cycle monitoring, CAPA, batch hold and release."
)
META = [
    ("shield", "Plant health"),
    ("image", "23 generated photo plates"),
    ("quote", "Official NZ + primary sources"),
    ("clock", "~55 min read"),
]
RELATED = ["ipm-sop", "pest-id", "mould-risk", "pppe", "tissue-culture"]

REF_IDS = [
    "moh-nz-pesticide-use-2024",
    "moh-nz-mqs-2026",
    "mpi-nz-acvm-exempt",
    "mpi-nz-invertebrate-import",
    "epa-nz-hsno-approvals",
    "worksafe-nz-rei",
    "worksafe-nz-hs-training",
    "watercare-nz-trade-waste",
    "auckland-unitary-plan-e33",
    "athena-ipm-book-v15",
    "ahmed-2024-hemp-pests-florida-jipm",
    "pulkoski-burrack-2023-piercing-sucking-hemp",
    "cranshaw-2018-phorodon-cannabis-north-america",
    "cranshaw-wainwright-2020-rice-root-aphid-cannabis",
    "lopez-2023-amblyseius-swirskii-review-jipm",
    "vanmaanen-2010-broad-mite-swirskii-biocontrol",
    "cloyd-2015-fungus-gnat-ecology-management",
    "cloyd-2024-biopesticides-cannabis-oregon",
    "punja-2021-emerging-diseases-cannabis",
    "scott-punja-2021-powdery-mildew-management",
    "mahmoud-2023-botrytis-budrot",
    "punja-2023-fusarium-pythium-biocontrol",
    "sutton-2006-pythium-hydroponic-etiology",
    "hlvd_threat2023",
    "hlvd_mgmt2025",
    "hlvd-transmission-2025",
    "rahnama-2021-septoria-cannabis",
    "ujata-2024-septoria-cannabicola",
]


LEGAL_GATES = [
    (
        "1. Intended end use",
        "If any lot may become inhaled flower, keep the inhalation-capable pathway open. "
        "Do not borrow the wider non-inhalation pathway by accident.",
    ),
    (
        "2. Medicinal-cannabis pathway",
        "Confirm the active or product fits Regulation 18 or another specifically accepted "
        "medicinal-cannabis route. A residue analyte appearing in Regulation 7 is not permission to use it.",
    ),
    (
        "3. ACVM authority",
        "Confirm the product is registered or falls within a documented exemption and all exemption "
        "conditions are met. Absence from a register is not proof of exemption.",
    ),
    (
        "4. HSNO approval",
        "Confirm an applicable EPA approval and its controls. Check section 15 of the current New "
        "Zealand SDS and verify it against the EPA database.",
    ),
    (
        "5. Worker controls",
        "Read the current label and SDS for PPE, application controls and REI. Indoor treated areas "
        "with an REI need signs and controlled access.",
    ),
    (
        "6. Analytical route",
        "Know which residues must be tested, the release limit, the laboratory accreditation scope, "
        "and whether the method LOQ is fit before the product enters the approved-input register.",
    ),
    (
        "7. Biological compatibility",
        "Check current side-effect data for every predator, parasitoid, nematode and microbial already "
        "in the room. A lawful spray can still erase the biological programme.",
    ),
    (
        "8. Environmental route",
        "Define how unused mix, rinse water, contaminated PPE and spills are contained and disposed. "
        "Nothing goes to stormwater; trade-waste discharge depends on the site's Watercare position.",
    ),
]


CONTROL_LAYERS = [
    ("Cultural", "Exclude, quarantine, sanitise, control movement, remove reservoirs, scout and record."),
    ("Environmental", "Remove the temperature, moisture, airflow and root-zone conditions that favour the problem."),
    ("Biological", "Establish the right predator, parasitoid, nematode or antagonist before pest pressure outruns it."),
    ("Chemical / reduced-risk", "Use only after the legal gate, targeted to the right life stage and followed by a defined recheck."),
]


SEVERITY = [
    ("0", "Not found", "No confirmed organism or damage. Continue the planned monitoring frequency."),
    ("1", "Trace", "One confirmed individual, colony or lesion at one mapped site; no spread seen."),
    ("2", "Local", "More than one finding in one zone, or a rising trap trend without room-wide spread."),
    ("3", "Established", "Multiple zones, repeated life stages, increasing disease incidence or biological control losing ground."),
    ("4", "Systemic", "Room-wide or linked-room spread, clean-stock involvement, crop-quality threat, or contaminated shared infrastructure."),
]


ATLAS = [
    {
        "kind": "arthropod",
        "name": "Rice root aphid",
        "scientific": "Rhopalosiphum rufiabdominale",
        "image": "assets/img/ipm-blueprint/01-rice-root-aphid.webp",
        "alt": "AI-generated educational reconstruction of rice root aphids colonising cannabis roots",
        "scale": "Plate is uncalibrated. Colonies are visible at whole-root scale; use about 30x-60x hand-lens or microscope inspection to resolve cornicles, antennae and alate body form.",
        "identify": "Soft, pear-shaped root-zone aphids in cream, amber or brown colonies, often with waxy residue. Winged alates may appear on low sticky cards. Cornicles and an aphid body plan separate them from fungus gnats.",
        "signs": "Unexplained yellowing, stunting, weak water response, sticky or waxy material around the root crown, and colonies on roots or the pot base. Above-ground symptoms are nonspecific.",
        "biology": "Wingless colonies feed below ground; crowded populations produce winged dispersers. They can move with rooted cuttings, loose media, pots, runoff and shared handling.",
        "inspect": "Lift root-zone covers, inspect the crown, root ball edge, drainage holes and bench debris. Place yellow cards just above the media and preserve unknown alates.",
        "confirm": "Microscopy or specialist identification. Compare antennae, cornicles and body shape against fungus-gnat adults before selecting control.",
        "lookalikes": "Fungus-gnat adults, nutrient/root-zone stress, Pythium and overwatering.",
        "threshold": "Zero tolerance in quarantine, foundation mothers, production mothers and clone rooms. Any confirmed colony in production triggers containment and linked-lot inspection.",
        "response": "Isolate the zone; bag severe plants; stop moving pots/media; inspect linked mothers and clone lots; correct standing water and algae; select only currently lawful root-zone biological or input options; recheck roots and low traps on the approved interval.",
        "development": "A complete indoor generation may take roughly 10-14 days under favourable root-zone conditions; host, temperature and media can shift that window. Include live-born immature/nymph, wingless adult and winged alate stages in the survey.",
        "controls": "Cultural: exclude infested stock/media, segregate pots and clean spills. Environmental: remove standing water and algae without stressing roots. Biological: consider lawful root-zone predators or nematodes matched to the target stage. Approved input: only a registered or documented exempt root-zone use that passes the NZ legal gate.",
        "targeting": "Target exposed colonies and mobile immature stages on roots/crown; monitor alates on cards just above media. Canopy-only treatment does not reach the colony.",
        "constraints": "Quarantine and mother stock remain zero tolerance. Verify organism/product status, root-zone use, beneficial compatibility, crop stage, label PPE/REI and residue implications before treatment.",
        "specimen": "Bag a labelled root/crown sample with some live colony material; preserve low-card alates separately; record plant, lot, room, root zone and collection time under chain of custody.",
        "recheck": "Reinspect mapped roots and low cards after the approved intervention interval and again over one expected generation; success means no live colony or new alates and no linked-plant spread.",
        "capa": "Trace source genetics, media/pot lots, irrigation/runoff links, benches, tools and staff movement; hold linked clone lots until the source and spread route are resolved.",
        "refs": ["cranshaw-wainwright-2020-rice-root-aphid-cannabis", "ahmed-2024-hemp-pests-florida-jipm"],
    },
    {
        "kind": "arthropod",
        "name": "Fungus gnats",
        "scientific": "Bradysia species",
        "image": "assets/img/ipm-blueprint/02-fungus-gnat.webp",
        "alt": "AI-generated educational reconstruction of fungus gnat adult and larva at cannabis media",
        "scale": "Plate is uncalibrated. Adults are roughly 2-4 mm long and visible over media; use about 30x-60x to confirm the larval black head capsule or adult venation/body form.",
        "identify": "Adults are delicate dark flies with long legs and antennae. Larvae are translucent, legless and wormlike with a distinct shiny black head capsule.",
        "signs": "Adults run or fly weakly over wet media; larvae occur near algae, decaying roots and biofilm. Root-hair feeding can slow young plants and wounds can interact with root disease.",
        "biology": "Egg and larval stages are in the medium, followed by a pupa and flying adult. Canopy-only treatment misses most of the population.",
        "inspect": "Read low yellow cards, use potato slices or media samples for larvae, and inspect irrigation uniformity, standing water, algae and organic debris.",
        "confirm": "Adult wing venation/body form or larval black head under a loupe or microscope. Preserve specimens if root aphid alates are possible.",
        "lookalikes": "Winged root aphids, shore flies, harmless small flies, Pythium-driven poor rooting.",
        "threshold": "Any larvae in propagation deserve action. Elsewhere use a site-set trend threshold; a rising multi-card trend matters more than one adult.",
        "response": "Dry the media surface within crop limits, remove algae and leaks, clean drains, target larvae with an approved root-zone biological programme, and use cards to verify adult decline over the next life cycle.",
        "development": "Egg-to-adult development is commonly about 18-28 days, with temperature, moisture, substrate and food strongly affecting the interval. Track egg, larva, pupa and adult rather than treating card counts as the whole population.",
        "controls": "Cultural: remove algae, debris and wet reservoirs and repair leaks. Environmental: allow a crop-safe surface dryback and correct poor drainage. Biological: use lawful nematodes or media predators against larvae. Approved input: restrict any drench or surface treatment to its authorised use and target stage.",
        "targeting": "Target larvae in the upper moist substrate/root zone; cards monitor adults but do not control the damaging stage. Coordinate media and adult monitoring across one full cycle.",
        "constraints": "Do not force dryback beyond crop limits. Check root-biological compatibility, irrigation-system effects, crop stage, label PPE/REI and residue route before any input.",
        "specimen": "Seal labelled adults/card sections and a separate media/root sample containing larvae; preserve the plant, zone, trap height and moisture context and submit unknowns for microscopy.",
        "recheck": "Count live larvae in the same media sites and adults on the same mapped cards at the site-set interval through one expected generation; success is a sustained falling trend with no propagation root injury.",
        "capa": "Investigate irrigation uniformity, leaks, algae/biofilm, drains, incoming media, propagation hygiene and any coincident root-disease pattern.",
        "refs": ["cloyd-2015-fungus-gnat-ecology-management", "ahmed-2024-hemp-pests-florida-jipm"],
    },
    {
        "kind": "arthropod",
        "name": "Thrips",
        "scientific": "Frankliniella occidentalis and other thrips species",
        "image": "assets/img/ipm-blueprint/03-thrips.webp",
        "alt": "AI-generated educational reconstruction of thrips and feeding injury on cannabis",
        "scale": "Plate is uncalibrated. Adults and larvae require close plant-part inspection; use about 30x-60x to resolve pale larvae, fringed adult wings and embedded-egg or species detail.",
        "identify": "Slender adults with narrow fringed wings; smaller pale larvae. Feeding scrapes cells into silvery streaks or patches, usually with black frass dots.",
        "signs": "Silvering, distorted young leaves, flower scarring and dark specks. Adults and larvae hide in folds and flowers; prepupae and pupae may be in media or debris.",
        "biology": "Eggs are inserted into plant tissue, larvae feed on the plant, then non-feeding stages occur in protected sites before adults return to the canopy.",
        "inspect": "Blue or yellow cards, tap flowers over white paper, inspect young folded leaves and flowers, and sample media/debris where pupation occurs.",
        "confirm": "Loupe or microscopy; species confirmation matters when choosing specialist biological control or assessing virus-vector risk.",
        "lookalikes": "Mechanical abrasion, wind burn, oedema and spray injury.",
        "threshold": "Zero tolerance in quarantine and clean stock. In production, a confirmed hotspot or rising repeated card trend triggers the site response level.",
        "response": "Contain the hotspot, remove heavily damaged tissue without scattering insects, target canopy and protected/off-plant stages, verify biological compatibility, and re-read mapped cards after the defined recheck window.",
        "development": "A generation often takes about 14-21 days under warm indoor conditions, but species and temperature matter. Eggs are embedded in tissue, larvae feed on the crop, prepupae/pupae occupy protected sites and adults disperse.",
        "controls": "Cultural: exclude infested stock, bag hotspots and remove debris. Environmental: reduce protected weeds/debris and correct unsuitable canopy conditions. Biological: use lawful predators or parasitoids matched to species and stage. Approved input: choose a legal contact or microbial option that reaches the target without collapsing beneficials.",
        "targeting": "Target feeding larvae on young leaves/flowers and protected prepupal/pupal sites; adults and embedded eggs require monitoring and repeat timing rather than assuming one contact pass is complete.",
        "constraints": "Species can determine biological fit. Flower contact, beneficial residues, crop-stage quality, label PPE/REI and analytical residue consequences constrain input choice.",
        "specimen": "Collect larvae and adults from a mapped hotspot into labelled sealed vials and retain a symptomatic leaf/flower separately; preserve card ID and plant-part context for specialist identification.",
        "recheck": "Repeat tap tests, plant inspection and mapped card counts at the approved interval through one expected generation; success is no feeding larvae and a falling adult trend without expansion beyond the hotspot.",
        "capa": "Trace incoming plants, flowers/packaging, doors/screens, weeds, tools, staff sequence and substrate debris; investigate species if control performance or vector consequence differs.",
        "refs": ["pulkoski-burrack-2023-piercing-sucking-hemp", "ahmed-2024-hemp-pests-florida-jipm"],
    },
    {
        "kind": "arthropod",
        "name": "Two-spotted spider mite",
        "scientific": "Tetranychus urticae",
        "image": "assets/img/ipm-blueprint/04-two-spotted-spider-mite.webp",
        "alt": "AI-generated educational reconstruction of two-spotted spider mites, eggs and webbing on cannabis",
        "scale": "Plate is uncalibrated. Inspect individual leaf undersides with a 10x-30x loupe; use microscopy where the two-spot pattern, eggs or beneficial-mite distinction is uncertain.",
        "identify": "Oval mites with two dark lateral patches, round translucent eggs and colonies on leaf undersides. Fine silk appears as pressure rises.",
        "signs": "Fine pale stippling progresses to bronzing, leaf decline and webbing over petioles, shoots and flowers. Hot, dry canopy pockets often show first.",
        "biology": "Egg, six-legged larva, nymphal stages and adult can overlap. Development accelerates strongly with warmth, so a small patch can change rapidly.",
        "inspect": "Map hot/dry zones, inspect leaf undersides with a 10x-30x loupe, tap foliage over white paper and trace webbing back to live colonies.",
        "confirm": "Microscopy for the two-spotted adult pattern and life stages. Distinguish from beneficial mites before treatment.",
        "lookalikes": "Spray stipple, nutrient flecking, dust and beneficial mites.",
        "threshold": "Any confirmed colony in quarantine or mothers. In veg/flower, a single reproducing hotspot is enough to trigger containment rather than wait for webbing.",
        "response": "Flag and isolate the hotspot, restrict staff/tool movement, remove the worst leaves into bags, correct extreme hot/dry pockets, release the approved predator programme or lawful compatible control, and verify live-mite decline rather than judging leaf damage that cannot heal.",
        "development": "Egg to adult may take roughly 7-14 days, accelerating as canopy temperature rises. Survey egg, six-legged larva, protonymph/deutonymph and adult because overlapping stages are normal indoors.",
        "controls": "Cultural: exclude infested stock, bag hotspot leaves and prevent contact spread. Environmental: correct extreme hot/dry pockets without creating disease risk. Biological: deploy a currently lawful predatory-mite programme early. Approved input: use only a compatible legal contact or microbial option with adequate underside access.",
        "targeting": "Target live mites and eggs on leaf undersides and the leading edge of hotspots; webbed flowers and protected colonies are harder to reach and carry higher quality consequence.",
        "constraints": "Old stippling is not an efficacy measure. Check predator residues, flower contact, crop stage, label PPE/REI, residue route and phytotoxicity before any input.",
        "specimen": "Bag labelled leading-edge leaves with live mites, keep samples cool and intact, and submit a separate slide/tape preparation if required; record hotspot temperature and plant location.",
        "recheck": "Recount live mites and eggs on the same mapped leaves plus the hotspot edge after the approved interval and again before one expected generation closes; success is no outward spread and a sustained live-stage decline.",
        "capa": "Trace plant contact, staff/tools, carts, incoming stock and hot/dry dead zones; review delayed detection and any incompatible residue that prevented predator establishment.",
        "refs": ["pulkoski-burrack-2023-piercing-sucking-hemp", "ahmed-2024-hemp-pests-florida-jipm"],
    },
    {
        "kind": "arthropod",
        "name": "Broad mite",
        "scientific": "Polyphagotarsonemus latus",
        "image": "assets/img/ipm-blueprint/05-broad-mite.webp",
        "alt": "AI-generated educational reconstruction of broad mites and ridged eggs on cannabis meristem",
        "scale": "Plate is uncalibrated. Adults are under about 0.2 mm; inspect intact meristems and characteristic eggs at roughly 20x-60x, escalating to compound microscopy for confirmation.",
        "identify": "Microscopic, pale mites on tender tissue. Eggs are diagnostically useful: oval and ornamented with pale raised dots or ridges.",
        "signs": "Hardened, blistered, glossy or twisted new growth, short internodes and damaged meristems. Symptoms can remain after mites are gone.",
        "biology": "Broad mites concentrate on protected new growth and can be carried on plant material, workers and equipment. Their size makes visual scouting alone unreliable.",
        "inspect": "Sample the youngest distorted tissue, petiole bases and shoot tips. Mount tape or leaf pieces for a dissecting/compound microscope.",
        "confirm": "Microscopic mites plus characteristic eggs. Confirmation is required before changing nutrition or applying a rescue treatment.",
        "lookalikes": "Heat/light tacoing, herbicide or spray injury, nutrient toxicity, viral/viroid stunting and genetic fasciation.",
        "threshold": "Zero tolerance in quarantine, mothers and propagation. Any confirmed production finding is high consequence because detection is late.",
        "response": "Isolate and usually remove confirmed clean-stock plants; trace clones and movement; intensify tip sampling; choose a currently lawful, crop-stage-compatible control; verify on new growth and microscopy, not on old distorted leaves.",
        "development": "A warm, humid crop can support a generation in roughly 4-7 days. Include ornamented egg, six-legged larva, quiescent/protected nymphal transition and microscopic adult when timing controls.",
        "controls": "Cultural: reject infested stock, isolate tips and remove confirmed clean-stock plants. Environmental: correct excess heat/humidity without imposing a universal setpoint. Biological: use a currently lawful predator with evidence for broad-mite stages. Approved input: limit use to a legal meristem-contact option compatible with predators and crop stage.",
        "targeting": "Target eggs and mobile mites within meristems, folded leaves and petiole bases; protected/quiescent stages and hidden tissue make coverage and repeat timing critical.",
        "constraints": "Diagnosis requires microscopy because symptoms persist after mites are gone. Protect beneficials and verify flower contact, crop stage, label PPE/REI, residues and phytotoxicity before inputs.",
        "specimen": "Collect several intact symptomatic shoot tips from the leading edge into labelled sealed bags, keep cool, and prepare tape/leaf mounts under the laboratory method without crushing the meristem.",
        "recheck": "Microscope multiple new tips from the hotspot and its perimeter after the approved interval and through one expected generation; success is repeated absence of live mites/eggs and normal new growth with no spatial expansion.",
        "capa": "Trace source plants/clones, worker and tool movement, carts, nearby crops and any treatment that masked symptoms; hold linked propagation material until microscopy clears it.",
        "refs": ["vanmaanen-2010-broad-mite-swirskii-biocontrol", "pulkoski-burrack-2023-piercing-sucking-hemp", "ahmed-2024-hemp-pests-florida-jipm"],
    },
    {
        "kind": "arthropod",
        "name": "Hemp russet mite",
        "scientific": "Aculops cannabicola",
        "image": "assets/img/ipm-blueprint/06-hemp-russet-mite.webp",
        "alt": "AI-generated high-magnification educational reconstruction of hemp russet mites on cannabis",
        "scale": "Plate is uncalibrated. Adults are under about 0.2 mm and eggs may be around 20 micrometres; inspect multiple stem, petiole and flower samples at roughly 60x-100x or use a diagnostic laboratory.",
        "identify": "Extremely small, pale, tapered and wormlike eriophyid mites with only two pairs of legs near the head. High magnification is mandatory.",
        "signs": "Dull bronzing or russeting, brittle petioles, curled margins, weak new growth and declining flower quality. Damage may climb upward through the plant.",
        "biology": "Mites aggregate on stems, petioles, leaf surfaces and flowers and can disperse on air currents, people, tools and plant contact.",
        "inspect": "Take multiple samples from the leading edge of symptoms, including petioles, stems and flowers. Use roughly 60x-100x or a diagnostic lab.",
        "confirm": "Specialist microscopy; absence in one sample does not clear a symptomatic plant because distribution is patchy.",
        "lookalikes": "Broad-mite injury, heat/light tacoing, nutrient problems, drought and HLVd-associated poor vigour.",
        "threshold": "Zero tolerance in quarantine, mothers and propagation. A single confirmed production plant triggers containment and trace-back.",
        "response": "Stop plant contact and movement, bag confirmed plants as the site procedure directs, sample linked cohorts, review airflow/tool vectors, apply only currently lawful compatible measures within the crop-stage window, and require repeated negative microscopy before closure.",
        "development": "A generation may take roughly 7-10 days in favourable warm indoor conditions, with host and environment changing the interval. Track egg, larva, nymph and tapered adult; all active stages retain two pairs of legs near the head as populations migrate upward.",
        "controls": "Cultural: exclude infested stock, stop plant contact and bag confirmed high-consequence plants. Environmental: review airflow and heat/dry stress without treating climate as eradication. Biological: use only a lawful predator with evidence for eriophyid mites. Approved input: select a legal high-magnification-confirmed tactic compatible with crop stage and existing biologicals.",
        "targeting": "Target the symptom-leading edge on stems, petioles, young leaves and flowers; multiple plant heights must be sampled because mites migrate upward and distribution is patchy.",
        "constraints": "High-magnification confirmation is mandatory. Late flower sharply limits crop-contact options; verify beneficial compatibility, label PPE/REI, residues, quality and phytotoxicity.",
        "specimen": "Collect several labelled stem, petiole, leaf and flower pieces from the leading edge and linked asymptomatic plants, keep cool and sealed, and submit intact for specialist microscopy.",
        "recheck": "Repeat 60x-100x or laboratory counts at the same mapped heights and leading edge after the approved interval and across one expected generation; closure requires repeated negative samples and no new upward spread.",
        "capa": "Trace genetics, clone cohorts, plant contact, airflow, staff/tools and sampling sensitivity; hold linked clean-stock material and review any false-negative clearance.",
        "refs": ["pulkoski-burrack-2023-piercing-sucking-hemp", "ahmed-2024-hemp-pests-florida-jipm"],
    },
    {
        "kind": "arthropod",
        "name": "Whiteflies",
        "scientific": "Trialeurodes vaporariorum, Bemisia tabaci complex and related species",
        "image": "assets/img/ipm-blueprint/07-whitefly.webp",
        "alt": "AI-generated educational reconstruction of whitefly adults and nymphs on cannabis leaf underside",
        "scale": "Plate is uncalibrated. Adults are roughly 1-2 mm and visible when flushed; inspect underside eggs, crawlers, fixed nymphs and red-eye stages at about 30x-60x, with specialist microscopy for species.",
        "identify": "White, powdery, moth-like adults flush from the leaf underside. Eggs, crawlers and flat scale-like nymphs remain on the underside; older nymphs may show red eyes.",
        "signs": "General chlorosis, honeydew, sooty mould and clouds of adults when foliage is disturbed. Nymphal stages are easy to miss.",
        "biology": "Only the first nymphal crawler moves far; later nymphs are fixed feeders. Species and stage affect parasitoid performance and control choice.",
        "inspect": "Turn lower and mid-canopy leaves, count nymph-bearing leaves, use yellow cards at canopy height, and inspect honeydew/sooty mould sites.",
        "confirm": "Microscopy or specialist species identification when the biological programme depends on species.",
        "lookalikes": "Powdery mildew, small moths, cast aphid skins and harmless white debris.",
        "threshold": "Zero tolerance at entry. In production, any reproducing underside colony or rising card trend triggers action before adults spread.",
        "response": "Contain the zone, remove heavily colonised leaves into bags, improve underside scouting, deploy only approved species-matched biologicals or compatible lawful inputs, and verify both adult cards and live nymphs.",
        "development": "Egg to adult commonly takes about 21-28 days under warm indoor conditions, but species and temperature change the range. Include egg, mobile crawler, fixed scale-like nymph/red-eye stage and winged adult.",
        "controls": "Cultural: exclude infested plants, bag colonised leaves and control weeds/reservoirs. Environmental: correct stagnant hot spots without creating excess humidity. Biological: use lawful predators or parasitoids matched to the confirmed species. Approved input: use only a legal underside-targeted option compatible with parasitoids and crop stage.",
        "targeting": "Target crawler and young nymph stages on leaf undersides while monitoring adults on yellow cards; fixed older nymphs and eggs may require stage-timed follow-up.",
        "constraints": "Species affects parasitoid fit. Check flower contamination, honeydew/sooty mould, beneficial residues, label PPE/REI, crop stage and residue release before inputs.",
        "specimen": "Bag labelled underside leaves carrying eggs and nymphs; preserve representative adults/card sections separately; record plant height, card position and any honeydew before specialist identification.",
        "recheck": "Count live nymphs on the same mapped leaves and adults on the same cards at the approved interval through one expected generation; success is no new colonies and a sustained decline in both measures.",
        "capa": "Trace incoming plants, weeds, doors/vents/screens, staff/tools and species mismatch in biological releases; assess sooty mould and affected product surfaces.",
        "refs": ["pulkoski-burrack-2023-piercing-sucking-hemp", "ahmed-2024-hemp-pests-florida-jipm"],
    },
    {
        "kind": "arthropod",
        "name": "Foliar aphids",
        "scientific": "Phorodon cannabis, Myzus persicae, Macrosiphum euphorbiae and others",
        "image": "assets/img/ipm-blueprint/08-cannabis-aphid.webp",
        "alt": "AI-generated educational reconstruction of cannabis aphids on a cannabis shoot",
        "scale": "Plate is uncalibrated. Colonies and adults are visible on shoots and undersides; use about 30x-60x to resolve cornicles, cast skins, nymphs and species-level characters.",
        "identify": "Soft pear-shaped insects with paired cornicles near the rear. Colonies contain nymphs, wingless adults, cast white skins and sometimes winged adults.",
        "signs": "Clusters on shoots, stems, leaf undersides or flowers; curled/distorted growth; sticky honeydew and secondary sooty mould.",
        "biology": "Females can produce live nymphs without mating under crop conditions, so colonies build quickly. Crowding produces winged dispersers.",
        "inspect": "Examine meristems, leaf undersides, petioles and flowers; map honeydew; read yellow cards for alates; distinguish aphids from beneficial larvae.",
        "confirm": "Species-level identification when choosing specialist parasitoids. Cannabis aphid, green peach aphid and potato aphid are not interchangeable targets.",
        "lookalikes": "Whitefly nymphs/cast skins, scale insects, beneficial larvae and root aphid alates.",
        "threshold": "Zero tolerance in clean stock. A single reproducing colony in production triggers local containment and a same-room survey.",
        "response": "Bag severely infested tips, control ant activity if present, avoid spreading honeydew on tools/PPE, select species-appropriate lawful biologicals or compatible input, and recheck living aphids and new nymph production.",
        "development": "Under warm indoor conditions a clonal aphid generation may be roughly 7-10 days. Live-born nymphs mature into wingless adults; crowding and stress can produce winged dispersers, with overlapping generations.",
        "controls": "Cultural: exclude stock, bag infested tips, control ants and remove weeds. Environmental: correct plant stress without assuming climate alone will control aphids. Biological: use lawful predators or parasitoids matched to aphid species. Approved input: choose a legal contact or microbial option compatible with beneficials and crop stage.",
        "targeting": "Target exposed nymphs and wingless adults on meristems, undersides, petioles and flowers; monitor alates on yellow cards and repeat for newborn nymphs.",
        "constraints": "Species-level identity can determine parasitoid success. Honeydew on flowers raises quality risk; verify beneficial residues, crop stage, label PPE/REI and residue consequences.",
        "specimen": "Collect live wingless and winged adults plus nymphs from a mapped colony into labelled sealed vials; retain a symptomatic tip separately and record host plant part for specialist identification.",
        "recheck": "Recount live aphids and newborn nymphs on the same marked tips plus alates on mapped cards after the approved interval and across one expected generation; success is colony extinction or an approved sustained decline without spread.",
        "capa": "Trace incoming stock, weeds, ants, staff/tools and species mismatch in the biological programme; assess honeydew contact and linked clean-stock lots.",
        "refs": ["cranshaw-2018-phorodon-cannabis-north-america", "pulkoski-burrack-2023-piercing-sucking-hemp"],
    },
    {
        "kind": "arthropod",
        "name": "Budworms and caterpillars",
        "scientific": "Lepidopteran larvae; species confirmation required",
        "image": "assets/img/ipm-blueprint/15-budworm-caterpillar.webp",
        "alt": "AI-generated educational reconstruction of caterpillar damage and frass inside a cannabis flower",
        "scale": "Plate is uncalibrated. Inspect the whole flower interior for larvae, bore holes and pellet-like frass; use about 30x-60x for eggs, very small larvae or diagnostic larval characters.",
        "identify": "Chewing larva in foliage or flowers with bore holes and pellet-like frass. Flower injury can create a direct entry site for Botrytis.",
        "signs": "Missing tissue, bored flowers, frass, local browning and a wilted sugar leaf. Damage can be hidden until the flower is opened.",
        "biology": "Eggs hatch to feeding larvae; later pupae and adults may be outside the crop. Exclusion is more reliable than trying to rescue late-flower injury.",
        "inspect": "Inspect entry points, screens, flowers with frass or wilted leaves, and conduct destructive checks where risk warrants it.",
        "confirm": "Larval morphology or specialist identification. Open damaged flower to separate feeding injury from primary Botrytis.",
        "lookalikes": "Botrytis without an insect, mechanical flower damage and broken stems.",
        "threshold": "Zero tolerance in indoor production and any flower finding is an immediate quality event.",
        "response": "Remove and bag the larva and affected flower, inspect neighbouring plants, close the entry route, assess secondary rot, and use only a lawful crop-stage-appropriate control where justified.",
        "development": "Development is species- and temperature-dependent; identify the larva before setting any interval. Treat egg, feeding larva, pupa and adult as distinct surveillance targets.",
        "controls": "Cultural: maintain exclusion screens, inspect entries and bag larvae/damaged flowers. Environmental: remove outdoor host and entry pressure without compromising ventilation. Biological: consider only a lawful species-appropriate organism. Approved input: late-flower contact is a last-resort legal and quality decision, not a default.",
        "targeting": "Target eggs or small exposed larvae before they enter flowers; once inside a cola, removal and secondary-rot assessment are more reliable than surface coverage.",
        "constraints": "Species confirmation matters. Any flower treatment must pass crop-stage, residue, microbial-quality, beneficial-compatibility, label PPE/REI and market-release review.",
        "specimen": "Seal the larva with the damaged flower/frass in separate labelled containers, retain bore-site photographs and keep the specimen intact for specialist identification.",
        "recheck": "Inspect neighbouring flowers and entry points daily during the defined containment window; success is no new frass, bore holes, larvae or secondary rot through the site-set risk period.",
        "capa": "Trace doors, screens, incoming plants/materials, outdoor hosts, night work and staff movement; assess linked flowers and Botrytis risk as a quality event.",
        "refs": ["ahmed-2024-hemp-pests-florida-jipm"],
    },
    {
        "kind": "disease",
        "name": "Powdery mildew",
        "scientific": "Golovinomyces and related powdery-mildew fungi on cannabis",
        "image": "assets/img/ipm-blueprint/09-powdery-mildew.webp",
        "alt": "AI-generated educational reconstruction of early powdery mildew colonies on cannabis leaf",
        "scale": "Plate is uncalibrated. Inspect whole leaves, stems and flowers under angled light, then examine a single colony at about 30x-60x; use microscopy or a laboratory when residue or trichomes remain plausible.",
        "identify": "Raised, patchy white colonies grow on living leaf, petiole, stem or flower surfaces. Early colonies are discrete rather than an even dusting.",
        "signs": "Dull pale spots develop visible superficial mycelium and conidia. Colonies expand and produce repeated airborne secondary cycles.",
        "biology": "Superficial fungal growth feeds from epidermal cells. Dense canopies, susceptible genetics and poor local air movement support spread even without free water.",
        "inspect": "Use angled light on leaves and stems, inspect lower/inner canopy and flowers, map single colonies, and compare against recent spray records.",
        "confirm": "Hand lens or microscopy for fungal structures; lab confirmation when dried spray/mineral residue, trichomes or dust create doubt.",
        "lookalikes": "Dried foliar spray, mineral residue, dust, trichomes and light reflection.",
        "threshold": "Zero tolerance in quarantine/mothers and any colony on flower. A single vegetative colony triggers containment and room-wide intensified scouting.",
        "response": "Bag affected tissue without shaking it, restrict room movement, correct canopy density and humid/dead-air pockets, use only a lawful crop-stage-compatible measure, and recheck new colonies rather than old scars.",
        "development": "Under favourable canopy conditions, germination begins within hours and visible colonies/secondary conidia can develop over several days; cultivar and microclimate change the interval.",
        "controls": "Cultural: exclude infected stock, bag lesions and sanitise vectors. Environmental: correct dense dead-air and humidity/dew-point excursions. Biological: use only a lawful preventive antagonist with evidence for the target. Approved input: select a legal crop-contact option appropriate to tissue and stage.",
        "targeting": "Target the first superficial colonies and new secondary spread on leaves/stems; flower infection is a quality event with far narrower intervention scope.",
        "constraints": "Do not confuse residue with infection. Flower contact, visible residues, beneficial compatibility, label PPE/REI, crop stage, phytotoxicity and analytical release constrain any input.",
        "specimen": "Photograph and bag an intact colony with adjacent healthy tissue using clean tools; retain recent spray records and submit dry/cool under the diagnostic laboratory instruction.",
        "recheck": "Use angled light and microscopy at mapped sites after the approved interval and again within the expected secondary-cycle window; success is no new colonies and no expansion of existing sites.",
        "capa": "Investigate source stock, staff/tools, airflow, canopy density, night humidity/dew point, cultivar susceptibility and affected flowers/batches.",
        "refs": ["scott-punja-2021-powdery-mildew-management", "punja-2021-emerging-diseases-cannabis"],
    },
    {
        "kind": "disease",
        "name": "Botrytis bud rot",
        "scientific": "Botrytis cinerea",
        "image": "assets/img/ipm-blueprint/10-botrytis-bud-rot.webp",
        "alt": "AI-generated educational reconstruction of internal Botrytis bud rot in a cannabis cola",
        "scale": "Plate is uncalibrated. Diagnose at whole-flower and opened-flower-interior scale, inspecting the lesion margin and sporulation with a hand lens; use laboratory microscopy/culture when species affects disposition.",
        "identify": "Internal flower tissue turns tan to brown and collapses; grey dusty sporulation may follow. A single wilted sugar leaf can be the first external clue.",
        "signs": "Local leaf wilt, soft or dry necrosis within dense flower, grey mould and rapid spread through touching tissue under humid conditions.",
        "biology": "Conidia enter susceptible, wounded or senescent tissue. Dense flowers create a humid microclimate; sclerotia and contaminated debris can carry inoculum between crops.",
        "inspect": "Daily high-risk flower checks, with destructive opening of suspicious dense buds. Track cultivar, zone, irrigation events, night humidity and handling injuries.",
        "confirm": "Characteristic internal necrosis and sporulation; diagnostic laboratory where quality disposition depends on species confirmation.",
        "lookalikes": "Caterpillar damage, mechanical bruising, senescence and other flower rots.",
        "threshold": "Any confirmed inflorescence is an immediate containment and batch-impact event.",
        "response": "Stop movement and fans that could spread spores during removal; bag a generous margin of affected material; inspect neighbours; hold implicated lot as site procedure requires; correct humidity/airflow/density; open CAPA if more than isolated.",
        "development": "Under sustained high humidity and susceptible tissue, infection may progress to visible necrosis/sporulation in roughly 3-5 days; temperature, wetness, wounds and flower architecture control the rate.",
        "controls": "Cultural: remove senescent/wounded tissue and bag affected flowers. Environmental: prevent condensation, prolonged wetness and dense stagnant flower zones. Biological: use only a lawful preventive antagonist with relevant evidence. Approved input: late-flower use requires explicit legal, quality and residue approval.",
        "targeting": "Prevent conidial infection at wounded/senescent tissue and remove internal lesions; an external surface spray cannot restore necrotic flower.",
        "constraints": "Any affected flower has batch/microbial-quality consequences. Avoid spore-dispersing handling; verify crop stage, worker PPE/REI, residues, compatibility and release testing before inputs.",
        "specimen": "Stop local airflow, photograph in place, bag an unopened suspicious flower plus the lesion margin with clean tools, keep cool, and submit separately from healthy comparators.",
        "recheck": "Conduct daily mapped flower checks during containment and repeat destructive inspection at the approved interval; success is no new internal necrosis or sporulation across the affected zone.",
        "capa": "Link cultivar/flower architecture, injury, canopy density, lights-off humidity/dew point, airflow, sanitation, staff/tools and every implicated lot or batch.",
        "refs": ["mahmoud-2023-botrytis-budrot", "punja-2021-emerging-diseases-cannabis"],
    },
    {
        "kind": "disease",
        "name": "Pythium root, crown rot and damping-off",
        "scientific": "Pythium species (oomycetes)",
        "image": "assets/img/ipm-blueprint/11-pythium-root-rot.webp",
        "alt": "AI-generated educational reconstruction of Pythium-like root rot in cannabis roots",
        "scale": "Plate is uncalibrated. Compare the whole root mass, individual root tips, cortex and crown against healthy white roots; confirm causal structures or organisms by diagnostic-laboratory microscopy, culture or molecular testing.",
        "identify": "Water-soaked tan to brown roots with weak cortex that may slough away, poor root tips, seedling damping-off or crown rot. Compare with firm bright-white healthy roots.",
        "signs": "Poor rooting, midday wilt despite wet media, yellowing, slow water uptake, stem-base collapse and linked symptoms along shared water circuits.",
        "biology": "Oospores persist; sporangia and motile zoospores support waterborne spread. Warm root zones, low dissolved oxygen, saturation and biofilm can increase risk, but species differ.",
        "inspect": "Roots, crown, drain water, tank/line biofilm, root-zone temperature, dissolved oxygen, irrigation frequency, standing water and linked hydro cohorts.",
        "confirm": "Plant diagnostic laboratory by microscopy, culture and/or molecular testing. Visual root colour alone is not a species diagnosis.",
        "lookalikes": "Abiotic root death, hypoxia without infection, Fusarium, nutrient salt injury and normal old-root browning.",
        "threshold": "Any damping-off cluster, crown rot or linked hydro pattern triggers isolation and water-system investigation.",
        "response": "Stop sharing water/material, remove collapsed plants, sample before sanitising, correct root-zone oxygen/moisture/temperature defects, clean biofilm under a validated SOP, and use only a lawful approved biological/input programme.",
        "development": "Motile zoospores can infect susceptible root tips quickly and symptoms may progress over days in warm, oxygen-poor or saturated systems; species, crop age and root-zone conditions alter the course.",
        "controls": "Cultural: start with clean stock/media and isolate affected water circuits. Environmental: correct saturation, heat, low dissolved oxygen, standing water and biofilm. Biological: use only a lawful preventive antagonist suited to the reservoir. Approved input: distinguish crop/root contact from validated line or surface sanitation.",
        "targeting": "Target prevention at root tips, crowns and waterborne inoculum; sample before sanitation. Dead/sloughed roots require removal and system correction, not a curative promise.",
        "constraints": "Antagonists are incompatible with many sanitisers. Verify root-zone use, strain/product status, crop stage, worker PPE/REI, residue route, reservoir compatibility and discharge controls.",
        "specimen": "Collect lesion-margin roots/crown, media and linked tank/return water before cleaning into separate sterile labelled containers; keep cool and preserve circuit/lot chain of custody.",
        "recheck": "Reinspect root tips/crowns and linked cohorts and repeat the validated water/root test after the approved interval; success is healthy new white roots, no new collapse and no linked spread.",
        "capa": "Investigate propagation source, water circuit, temperature/DO, saturation/dryback, biofilm, hoses/trays, tools, staff and every connected cohort.",
        "refs": ["sutton-2006-pythium-hydroponic-etiology", "punja-2023-fusarium-pythium-biocontrol", "punja-2021-emerging-diseases-cannabis"],
    },
    {
        "kind": "disease",
        "name": "Fusarium wilt, root and crown disease",
        "scientific": "Fusarium species complexes",
        "image": "assets/img/ipm-blueprint/12-fusarium-wilt.webp",
        "alt": "AI-generated educational reconstruction of Fusarium-like wilt and vascular browning in cannabis",
        "scale": "Plate is uncalibrated. Assess whole-plant asymmetry, then inspect longitudinal crown/stem cuts and root-lesion margins; laboratory isolation and molecular identification provide the causal scale.",
        "identify": "Progressive or one-sided wilt/yellowing with crown/root lesions and internal vascular browning in cut stem or crown tissue.",
        "signs": "Weak rooting, damping-off, stem-base lesions, chlorosis, wilt that does not recover normally, and cohort patterns linked to stock, tools, media or water.",
        "biology": "Different Fusarium species complexes can act as root, crown, vascular or flower pathogens. Conidia disperse with contaminated water, tissue and equipment; spores germinate at root tips or wounds, hyphae colonise xylem, and chlamydospores persist in plant/media debris.",
        "inspect": "Cut symptomatic crown/stem lengthwise, compare vascular tissue with a healthy plant, inspect roots, trace propagation source, tools, media lots and irrigation links.",
        "confirm": "Diagnostic laboratory isolation plus molecular identification where required. Management depends on the actual disease syndrome and source.",
        "lookalikes": "Pythium, drought/hypoxia, root mechanical injury, nutrient imbalance, HLVd-associated poor vigour.",
        "threshold": "Any confirmed clean-stock or clonal-line case is high consequence; clustered production cases are systemic until trace-back proves otherwise.",
        "response": "Isolate, bag and destroy as the site procedure directs; hold linked clones; sample before cleaning; investigate stock/tools/media/water; correct structural risk; do not promise a curative rescue for vascular infection.",
        "development": "Root infection and vascular symptoms can develop over days to weeks; species complex, inoculum, temperature, moisture and plant stress determine the interval, while resting chlamydospores persist far longer.",
        "controls": "Cultural: use tested stock, clean media/tools and destroy confirmed vascular cases. Environmental: correct root injury, saturation and heat without implying climate cures infection. Biological: use only a lawful preventive antagonist with strain-specific evidence. Approved input: distinguish preventive root use from line/surface sanitation.",
        "targeting": "Prevent root-tip/wound entry and conidial movement; vascular colonisation is not a credible curative target, so confirmed plants and linked source pathways drive the decision.",
        "constraints": "Species/syndrome confirmation matters. Antagonist-sanitiser incompatibility, crop stage, root-zone use, label PPE/REI, residue route and discharge controls must be resolved before inputs.",
        "specimen": "Collect root/crown lesion margins and a longitudinal stem section including brown and healthy vascular tissue with clean tools; bag separately, keep cool and preserve stock/media/water links.",
        "recheck": "Inspect linked cohorts for new wilt and vascular browning and repeat laboratory testing on the approved schedule; success is no new cases after removal and correction, not recovery of infected vascular tissue.",
        "capa": "Trace mother/clone genealogy, seed or plant source, tools, media lots, water circuits, root injury, staff movement and every linked cohort or batch.",
        "refs": ["punja-2023-fusarium-pythium-biocontrol", "punja-2021-emerging-diseases-cannabis"],
    },
    {
        "kind": "disease",
        "name": "Hop latent viroid disease",
        "scientific": "Hop latent viroid (HLVd)",
        "image": "assets/img/ipm-blueprint/13-hlvd-syndrome.webp",
        "alt": "AI-generated educational comparison of healthy cannabis and nonspecific HLVd-like symptoms",
        "scale": "Plate is uncalibrated. Compare whole plants and clonal cohorts only to choose samples; confirmation operates at the traceable individual-plant or validated pool level by RT-qPCR/RT-PCR, not visual magnification.",
        "identify": "There is no reliable visual diagnosis. Plants may be asymptomatic or show shortened internodes, weak vigour, poor rooting, reduced trichomes and small low-quality flowers.",
        "signs": "A clonal line or linked hydro cohort underperforms without a clear environmental cause. Visual symptoms are nonspecific and absence of symptoms proves nothing.",
        "biology": "The viroid moves with infected vegetative material and mechanically through contaminated tools; research also supports risk through roots and recirculated hydroponic solution.",
        "inspect": "Use traceable molecular surveillance in quarantine, foundation mothers and production mothers. Sampling tissue and timing must follow the validated laboratory method.",
        "confirm": "RT-qPCR or RT-PCR only, with appropriate controls and repeat/inconclusive rules. The generated plate is not diagnostic evidence.",
        "lookalikes": "Root disease, irrigation faults, nutrient imbalance, russet/broad mites, genetic low vigour and other systemic pathogens.",
        "threshold": "Zero tolerance in quarantine, foundation mothers, production mothers and clone-source material.",
        "response": "Quarantine the plant and linked material; stop clone movement; confirm result; destroy positives under the approved SOP; hold daughters since the last verified negative; investigate tools, staff path and shared hydro systems; verify CAPA with follow-up testing.",
        "development": "There is no dependable visual development window: infection may remain asymptomatic while moving through clonal lines. Surveillance timing must follow the validated molecular method and stock-risk schedule.",
        "controls": "Cultural: admit tested stock, segregate genealogy, sanitise tools between defined plant units and destroy confirmed positives. Environmental: segregate unvalidated recirculating solution; climate does not clear infection. Biological: no established curative role. Approved input: sanitisers apply only through a validated legal tool/surface process.",
        "targeting": "Target exclusion and mechanical/root transmission pathways, not visible symptoms. Molecularly monitor quarantine, foundation and production mothers and trace every daughter lot.",
        "constraints": "No image, vigour score or symptom absence releases stock. Sampling tissue/timing, controls, pooling, repeats and inconclusive rules follow the validated RT-qPCR/RT-PCR method; review sanitiser PPE/REI/residue use separately.",
        "specimen": "Collect the validated tissue with single-use or decontaminated tools into the laboratory container; maintain accession, plant, mother, clone-lot, collector, time and temperature chain of custody.",
        "recheck": "Repeat positives/inconclusives and test linked material under the approved method; success is documented destruction/containment plus verified negative surveillance of the defined trace cohort, never symptom improvement.",
        "capa": "Trace every daughter since the last verified negative, tool/staff path, sampling integrity, root contact and shared hydro circuits; hold affected lots until QA closes the investigation.",
        "refs": ["hlvd_threat2023", "hlvd_mgmt2025", "hlvd-transmission-2025"],
    },
    {
        "kind": "disease",
        "name": "Septoria leaf spot",
        "scientific": "Septoria cannabis, S. neocannabina, S. cannabicola and related diagnoses",
        "image": "assets/img/ipm-blueprint/14-septoria-leaf-spot.webp",
        "alt": "AI-generated educational reconstruction of Septoria-like leaf spot on a lower cannabis leaf",
        "scale": "Plate is uncalibrated. Inspect the whole lower leaf and individual lesion centres at about 30x-60x for dark pycnidia; laboratory microscopy, culture or sequencing is required where species matters.",
        "identify": "Discrete tan, grey-brown or brown leaf lesions with chlorotic margins; tiny dark pycnidia may occur in lesion centres. Lesions can coalesce and drive lower-leaf loss.",
        "signs": "Lower/older leaves commonly show first. Splash, wet foliage and infected debris support spread, although indoor importance is site-specific.",
        "biology": "Septoria species produce pycnidia and conidia in lesions. Species names cannot be assigned safely from lesion appearance alone.",
        "inspect": "Map lower-leaf lesions, check for splash/leaf wetness and infected debris, photograph both leaf surfaces, and review spray/nutrient history.",
        "confirm": "Plant diagnostic laboratory by microscopy/culture and sequence-based methods where species matters.",
        "lookalikes": "Nutrient deficiency, chemical splash, Cercospora/Bipolaris and other leaf spots, mechanical injury and senescence.",
        "threshold": "Any confirmed quarantine/stock case triggers exclusion. In production, repeated lesions or a spreading pattern triggers containment and lab work.",
        "response": "Remove infected debris into bags, prevent splash and leaf wetness, improve airflow, stop cross-room movement of wet tools/PPE, confirm diagnosis, and use only a lawful evidence-supported measure if intervention is justified.",
        "development": "Lesion and pycnidium development takes days to weeks depending on species, temperature and wetness duration; repeated splash-driven conidial cycles can continue while wet debris remains.",
        "controls": "Cultural: exclude infected stock, bag lesions/debris and prevent wet-tool movement. Environmental: stop splash and prolonged leaf wetness and improve lower-canopy airflow. Biological: use only a lawful antagonist supported for the confirmed diagnosis. Approved input: choose a legal crop-contact option only after laboratory and indoor-relevance review.",
        "targeting": "Target infected lower leaves, debris and splash pathways before lesions coalesce; protect new foliage rather than expecting necrotic lesions to recover.",
        "constraints": "Indoor importance and species identity are site-specific. Flower contact, crop stage, beneficial compatibility, label PPE/REI, residues, phytotoxicity and spray-injury lookalikes constrain treatment.",
        "specimen": "Photograph both surfaces and collect several dry lesion-margin leaves with pycnidia plus a healthy comparator in separate labelled paper or laboratory-approved packaging; preserve spray/nutrient history.",
        "recheck": "Map and recount new lesions on lower and newly exposed leaves after the approved interval and following any wetness event; success is no new lesions or upward spread through the defined observation window.",
        "capa": "Investigate incoming stock, infected debris, overhead splash/irrigation, condensation/leaf wetness, tools/PPE, nutrient or chemical injury and linked rooms.",
        "refs": ["rahnama-2021-septoria-cannabis", "ujata-2024-septoria-cannabicola", "punja-2021-emerging-diseases-cannabis"],
    },
]


REFERENCE_PLATES = [
    ("Healthy leaf underside", "assets/img/ipm-blueprint/16-healthy-leaf-underside.webp"),
    ("Healthy white roots", "assets/img/ipm-blueprint/17-healthy-roots.webp"),
    ("Healthy shoot meristem", "assets/img/ipm-blueprint/18-healthy-meristem.webp"),
    ("Healthy flower interior", "assets/img/ipm-blueprint/19-healthy-flower-interior.webp"),
    ("Fungus gnat vs winged root aphid", "assets/img/ipm-blueprint/20-gnat-vs-root-aphid.webp"),
    ("Heat/light tacoing without mites", "assets/img/ipm-blueprint/21-abiotic-tacoing.webp"),
    ("Dried foliar residue, not mildew", "assets/img/ipm-blueprint/22-foliar-residue.webp"),
    ("Abiotic root stress, not a diagnosis", "assets/img/ipm-blueprint/23-abiotic-root-stress.webp"),
]


BENEFICIAL_ROWS = [
    ("Canopy predatory mites", "Phytoseiulus persimilis for spider-mite hotspots; Neoseiulus californicus or N. fallacis for broader spider-mite suppression; N. cucumeris or Amblyseius swirskii for thrips larvae and, where evidence fits, broad mites or whitefly eggs/young stages", "Before naming any agent as deployable, verify current NZ organism status, supplier availability, target stage, climate, sachet/loose-release method, residues and establishment evidence"),
    ("Canopy predators", "Orius species for thrips life stages and lacewing larvae for aphids or other exposed soft-bodied prey where host fit is supported", "Verify current NZ status and supplier availability; release against the correct prey stage and check dispersal, cannibalism/prey availability, crop stage and incompatible residues"),
    ("Aphid parasitoids", "Aphidius species selected for the confirmed aphid host; cannabis, green peach and potato aphids are not interchangeable targets", "Verify current NZ status, supplier availability and host match; monitor mummies/parasitism, hyperparasitoids where relevant, residues and replacement action"),
    ("Whitefly parasitoids", "Encarsia formosa or Eretmocerus species selected for the confirmed whitefly and nymphal stage", "Verify current NZ status and supplier availability; confirm whitefly species, release timing, climate, parasitism evidence and residue compatibility"),
    ("Root-zone predators", "Stratiolaelaps scimitus and, where lawful and available, Dalotia coriaria for fungus-gnat larvae, soil-stage thrips and other small media prey", "Verify current NZ status and supplier availability; check media depth/moisture, prey, arrival viability, release distribution, residues and establishment"),
    ("Beneficial nematodes", "Steinernema feltiae for susceptible fungus-gnat larvae and other supported soil stages", "Verify lawful product/organism status and supplier availability; check live/dead morphology, cool storage, prompt use, agitation/oxygen, light, filters/nozzles and dip/drench/sprench fit"),
    ("Entomopathogenic microbes", "Beauveria and other approved insect-pathogen strains against labelled susceptible aphid, thrips, whitefly or other stages", "Verify exact strain/product and NZ pathway; manage storage/viability, contact and environmental requirements, non-target effects, worker controls, residues and recheck"),
    ("Plant-pathogen antagonists", "Trichoderma, Bacillus or Streptomyces strains for preventive suppression of supported root or foliar pathogens, not revival of dead or vascularly colonised tissue", "Verify exact strain/product, NZ status and supplier availability; separate from sanitisers, check reservoir/crop compatibility, storage, colonisation and outcome evidence"),
]


APPROVED_TOOL_FIELDS = [
    "Product and supplier",
    "Active ingredient / living organism / strain",
    "Target organism and target life stage",
    "Inhalation or segregated non-inhalation pathway",
    "Medicinal-cannabis legal basis",
    "ACVM registration or exemption evidence",
    "EPA approval / HSNO controls and current SDS revision",
    "Label use, crop/contact site and application method",
    "IRAC/FRAC group or physical/biological mode",
    "PPE, REI, signage, PHI/withholding and crop-stage restriction",
    "Analytical method, required limit and practical LOQ",
    "Compatibility with every beneficial in the room",
    "Mixing, water quality, calibration and clean-out requirements",
    "Waste/rinse/spill route",
    "Evidence grade, approver, last verification and review due date",
]


SCOUT_FIELDS = [
    "Date/time, scout, room, zone, bench and fixed route point",
    "Plant/lot ID and growth stage",
    "Leaf top, underside, meristem, stem/crown, flower, media and roots checked",
    "Trap ID, colour, height, deploy/replace date and counts by organism",
    "Confirmed organism, life stage, incidence and severity 0-4",
    "Beneficial organism and establishment evidence",
    "Environmental/root-zone anomaly and recent intervention",
    "Photo ID, specimen ID, chain of custody and lab result",
    "Threshold status, containment, owner and due date",
    "Recheck date, success criterion and close/CAPA decision",
]


GLOSSARY = [
    ("Action threshold", "The pre-approved point at which observation becomes intervention. It may be a count, a trend, a severity level or a zero-tolerance finding."),
    ("Alate", "A winged aphid produced for dispersal."),
    ("Antagonist", "A beneficial microorganism that suppresses a plant pathogen by competition, antibiosis or other interaction."),
    ("Asexual", "Reproduction without fusion of gametes; many indoor pest and pathogen populations multiply mainly through asexual stages."),
    ("Axil", "The angle where a leaf or branch joins the stem, often a protected inspection point."),
    ("Biosecurity", "Controls that prevent pests and pathogens entering or moving through the facility."),
    ("Bronzing", "Bronze-brown discolouration caused by feeding injury or stress; it is a symptom, not an organism diagnosis."),
    ("CAPA", "Corrective and preventive action: contain the event, find the cause, fix it, prevent recurrence and verify effectiveness."),
    ("Chlorosis", "Loss of green colour from tissue."),
    ("Conidium / conidia", "An asexual fungal spore / spores used for dispersal."),
    ("Cornicle", "One of the paired tube-like structures near the rear of an aphid."),
    ("Crown rot", "Disease at the junction of stem and root system."),
    ("Cupping / tacoing", "Upward or downward leaf-edge curvature associated with heat, humidity, chemical injury or mite feeding; inspect for organisms before assigning cause."),
    ("Damping-off", "Seedling or cutting collapse caused by root/crown pathogens, commonly including Pythium or Fusarium."),
    ("Dew-point margin", "The gap between tissue/surface temperature and dew point. A small gap means condensation risk."),
    ("Dissolved oxygen", "Oxygen dissolved in irrigation solution; low levels can stress roots and favour some root-disease conditions."),
    ("Dudding", "A nonspecific production term for weak, stunted cannabis with poor flower development; it does not diagnose HLVd."),
    ("Entomopathogenic", "Able to infect and kill insects or mites."),
    ("Exclusion", "Measures that prevent a pest, pathogen or unapproved material entering the controlled crop system."),
    ("FRAC / IRAC", "Fungicide and insecticide resistance-action classification systems used to rotate modes of action."),
    ("Honeydew", "Sticky sugar-rich excretion from aphids, whiteflies and related sap feeders."),
    ("Incidence", "The proportion of plants or sites affected, separate from how badly each is affected."),
    ("Inoculum", "Pathogen material capable of starting infection, such as spores or infected debris."),
    ("Instar", "A growth stage between moults in an immature arthropod."),
    ("Larva", "A feeding immature stage that differs from the adult; fungus gnats, thrips and caterpillars have diagnostically important larval stages."),
    ("LOQ", "Limit of quantification: the lowest level a method can measure with acceptable performance."),
    ("Meristem", "The actively dividing shoot-tip tissue that produces new growth."),
    ("Mycelium", "The network of fungal hyphae that forms the growing body of a fungus."),
    ("Mould / mold", "Visible fungal growth; mould is the standard New Zealand spelling, while mold may appear in imported references."),
    ("Necrosis", "Dead plant tissue."),
    ("Nymph", "An immature arthropod stage that broadly resembles the adult but is not yet mature."),
    ("Oomycete", "A fungus-like organism; Pythium is an oomycete, not a true fungus."),
    ("Oospore", "A thick-walled survival spore produced by some oomycetes."),
    ("Parasite", "An organism that lives in or on a host and draws resources from it, usually without the one-host lethal outcome that defines a parasitoid."),
    ("Parasitoid", "An organism, usually a wasp in IPM, whose immature stage develops in or on one host and kills it."),
    ("Parthenogenesis", "Production of offspring without fertilisation; it enables rapid population growth in several indoor pests."),
    ("Pathogen", "An organism or agent that causes disease."),
    ("Petiole", "The stalk joining a leaf blade to the stem and a useful inspection site for mites and symptoms."),
    ("Preventive / curative", "Applied before establishment to prevent pressure / applied after confirmation to reduce an active problem."),
    ("Predator", "A beneficial organism that consumes multiple prey during its life."),
    ("Pupa", "A generally non-feeding stage between larva and adult in complete metamorphosis; it may be protected in media or debris."),
    ("Pycnidium", "A small flask-like fungal fruiting body that produces conidia; it may appear as a dark dot in a Septoria lesion."),
    ("REI", "Restricted entry interval: the period when entry is prohibited unless specified PPE and conditions are met."),
    ("Release", "A documented quality decision allowing a held plant, material or batch to move or be supplied after defined evidence and approvals are complete."),
    ("Residue limit", "The applicable maximum or action limit used for analytical disposition; its presence does not authorise pesticide use."),
    ("Rogue / roguing", "Remove and destroy a diseased or infested plant from the production system."),
    ("Russeting", "Bronze-brown roughened tissue associated with feeding injury or other stress."),
    ("Severity", "How much of a plant/site is affected, distinct from incidence."),
    ("Sachet", "A small carrier pack that releases beneficial organisms into the crop over time under defined conditions."),
    ("Sanitation", "Validated cleaning and, where required, disinfection that removes debris and reduces viable contamination on a defined surface or system."),
    ("Scouting", "A repeatable, mapped inspection and sampling process used to detect, identify, quantify and trend crop-health findings."),
    ("Sooty mould", "Dark fungus growing on honeydew; it is a sign of sap-feeding insects, not usually the primary plant pathogen."),
    ("Sprench", "An application volume between a spray and drench intended to reach the plant base/media surface."),
    ("Spore", "A fungal or fungus-like reproductive or survival unit; its type and biology determine sampling and control."),
    ("Stippling", "Many tiny pale feeding points caused when mites or other pests empty plant cells."),
    ("Systemic resistance", "A plant-wide defensive state induced by a stimulus; it may reduce susceptibility but does not prove control of an established pathogen."),
    ("Vector", "A living or mechanical carrier that moves a pest or pathogen."),
    ("Viroid", "A small infectious RNA molecule without a protein coat; HLVd is a viroid."),
    ("Zoospore", "A motile waterborne spore produced by oomycetes such as Pythium."),
    ("ACVM", "New Zealand agricultural compounds and veterinary medicines regulatory framework administered by MPI."),
    ("EPA", "New Zealand Environmental Protection Authority, which administers hazardous-substance and new-organism approvals and controls."),
    ("HSNO", "Hazardous Substances and New Organisms Act framework administered by the EPA."),
    ("Inhalation / non-inhalation line", "The intended medicinal-cannabis end-use pathway that changes which pesticide-active provisions and quality consequences apply; it must be set before input selection."),
    ("MPI", "New Zealand Ministry for Primary Industries, including administration of ACVM and biosecurity pathways relevant to inputs and organisms."),
    ("Minimum quality standard", "The statutory quality requirements medicinal-cannabis ingredients and products must meet before supply in New Zealand."),
    ("Approved-input register", "The site's controlled list of products and organisms that passed legal, safety, analytical, compatibility and operational review."),
    ("Batch hold", "A quality status that prevents movement or release while evidence or investigation is incomplete."),
    ("Trade waste", "Commercial or industrial liquid waste discharged to the wastewater network under Watercare/Auckland controls."),
]
