# -*- coding: utf-8 -*-
"""Image manifest. Drives gen_images.py (generation) AND build.py (embedding).
Each entry: slug, n (per-paper index), sec (0-based section to append the photo to,
clamped), model, ar, res, prompt, caption, alt. File = img/<slug>-<n>.jpg."""

MODEL_LABEL = {
    "nano_banana_2": "Nano Banana 2",
    "gpt_image_2": "GPT Image 2 (OpenAI)",
    "cinematic_studio_2_5": "Cinema Studio",
    "factcheck_pack": "Fact check",
    "code_diagram": "Diagram for education",
    "grok_imagine": "Grok Imagine",
}

# NB = photoreal practical, GPT = labelled/diagram, CIN = epic/cinematic hero
# FC = fact-check educational pack (photo or code diagram)
NB, GPT, CIN, FC, CD = "nano_banana_2", "gpt_image_2", "cinematic_studio_2_5", "factcheck_pack", "code_diagram"

IMAGES = [
 # ---- tissue culture (photoreal step series; sec indices AFTER evidence panel insert) ----
 {"slug":"tissue-culture","n":1,"sec":6,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"still-air box TC workstation","caption":"Step: setup of the laboratory. A still-air box, alcohol, tools and culture vessels. The necessary items are clean air, sterilized tools and a warm shelf with light. A hospital laboratory is not necessary.","alt":"Work area with a still-air box for tissue culture at home"},
 {"slug":"tissue-culture","n":2,"sec":7,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"aseptic tool sterilisation","caption":"Step: aseptic technique. Sterilize the tools with a flame or with alcohol each time. Contamination from the hands, from the breath or from dirty tools causes most unsatisfactory results of growers who are new to the work.","alt":"Sterilization of tissue culture tools, with hands in gloves"},
 {"slug":"tissue-culture","n":3,"sec":8,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"pouring agar media into jars","caption":"Step: make and sterilize the medium. Put the warm medium with agar in the vessels after sterilization in an autoclave. In a sealed vessel, the medium gives the plant sugar, salts and hormones.","alt":"Medium for tissue culture, put in vessels"},
 {"slug":"tissue-culture","n":4,"sec":5,"model":FC,"ext":"jpg","ar":"16:9","res":"2k",
  "prompt":"(factcheck) meristem vs HpLVd","caption":"Meristem culture can remove Hop Latent Viroid. The viroid moves in vascular tissue, and it frequently cannot go into the meristem dome of new cells that you cut.","alt":"Diagram with labels of a meristem, with HpLVd"},
 {"slug":"tissue-culture","n":5,"sec":9,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"healthy cannabis mother plant","caption":"Stage 0: prepare the donor plant. Select a mother plant that is strong and has the correct traits of the cultivar. In the 1 to 2 weeks before you cut, make the plant clean. A donor plant in unsatisfactory condition gives cultures in unsatisfactory condition.","alt":"Cannabis mother plant in vegetative growth and in good condition"},
 {"slug":"tissue-culture","n":6,"sec":10,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"cutting nodal explant","caption":"Stage I: cut a nodal segment. For your first batches, use a stem piece of approximately 1 cm with one bud. With this piece, an error has a smaller effect.","alt":"A person cuts a nodal segment of cannabis with a scalpel"},
 {"slug":"tissue-culture","n":7,"sec":10,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"surface sterilise explant bleach","caption":"Stage I: sterilize the surface of the explant. Dilute bleach, or a sanitizer from a kit, kills the microbes on the outer surface. If the time is correct, the liquid does not kill the tissue.","alt":"Explant in a solution that sterilizes it"},
 {"slug":"tissue-culture","n":8,"sec":11,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"plating explant on agar","caption":"Initiation: put the sterilized explant on new medium and seal the vessel. Then the explant must start to increase in size. Contamination must not occur.","alt":"A person puts an explant on agar in a culture vessel"},
 {"slug":"tissue-culture","n":9,"sec":11,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"initiation culture shelf","caption":"Initiation, the culture room: approximately 25 °C and long days with light of low intensity. In the first weeks, monitor each vessel each day.","alt":"Vessels for tissue culture on a shelf with light"},
 {"slug":"tissue-culture","n":10,"sec":12,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"meristem excision under microscope","caption":"Cleanup, meristem dissection: use a stereo microscope and cut only the very small meristem dome. This step removes most systemic disease.","alt":"Meristem dissection with a microscope"},
 {"slug":"tissue-culture","n":11,"sec":13,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"RT-qPCR sample prep","caption":"Indexing: make sure that the plant has no disease. A plant with no signs of a problem is not clean until an RT-qPCR test, or an equivalent laboratory test, shows that it is clean. Send tissue to the laboratory. This test is mandatory.","alt":"Sample of leaf tissue for the laboratory test for viroid"},
 {"slug":"tissue-culture","n":12,"sec":14,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"multiplication shoots in jars","caption":"Stage II: multiplication. A medium with a cytokinin causes shoots. Thus one clean shoot becomes many shoots in many vessels.","alt":"Many cannabis shoots in tissue culture vessels"},
 {"slug":"tissue-culture","n":13,"sec":14,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"hyperhydricity glassy shoots","caption":"Monitor the shoots for hyperhydricity. The shoots are glassy and full of water. They are larger than usual, but they make a small number of roots and they do not acclimatize correctly. Decrease the hormone or the humidity.","alt":"Glassy shoots in tissue culture with hyperhydricity"},
 {"slug":"tissue-culture","n":14,"sec":15,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"in vitro rooting","caption":"Stage III: the rooting stage. A medium with an auxin, or the easier ex vitro procedure, makes roots on the shoot. Thus the shoot becomes a plant with white roots.","alt":"Tissue culture shoot with roots in agar"},
 {"slug":"tissue-culture","n":15,"sec":16,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"acclimatisation under dome","caption":"Stage IV: acclimatization. Decrease the humidity slowly and increase the light slowly. A fast acclimatization kills more plantlets than almost all other steps.","alt":"Tissue culture plantlet in a humidity dome, in acclimatization"},
 {"slug":"tissue-culture","n":16,"sec":17,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"clean mother stock plant","caption":"Make a new clean mother plant. Keep the plant in vegetative growth with long days, in a space that is very clean. Then get usual cuttings from a plant that a test shows is clean.","alt":"New clean cannabis mother plant from tissue culture"},
 {"slug":"tissue-culture","n":17,"sec":19,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"contamination vs clean jar","caption":"Troubleshooting, contamination: fungal growth, or slime in a medium that is not transparent, shows that a microbe kills the culture. Compare with a clean vessel. If possible, discard the vessel and do not open it.","alt":"Tissue culture vessel with contamination next to a clean vessel"},
 {"slug":"tissue-culture","n":18,"sec":4,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"workflow overview bench",
  "caption":"The full procedure on one bench: a clean work area, vessels of medium, culture vessels and a donor plant. The stages are in this sequence: from Stage 0 to a mother plant after acclimatization.","alt":"All the stages of the tissue culture procedure on a laboratory bench"},


 # ---- coco & crop steering ----
 {"slug":"coco-crop-steering","n":1,"sec":2,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic close-up in a commercial cannabis grow: a rectangular open-top coco coir grow bag (a printed white coir grow bag, about one gallon) sitting on a bench with a healthy cannabis plant growing out of the open top; a flat white rectangular three-prong capacitance substrate sensor (thin polished steel needles, white body, thin black cable with a cylindrical ferrite bead) inserted into the coir at an angle; thin white 4mm drip-irrigation lines arch over the bag with drip stakes pushed into the coir surface; bright greenhouse lighting, sharp documentary detail. NOT a fabric pot, NOT a terracotta pot, NOT a handheld dial meter.",
  "caption":"A root-zone capacitance probe and drip stakes in a bag of coco coir with an open top. The equipment is for the readings and for crop steering.","alt":"Capacitance sensor and drippers in a bag of coco coir"},
 {"slug":"coco-crop-steering","n":2,"sec":4,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic close-up: white pressure-compensating drip-emitter stakes fed by thin 4mm lines releasing water onto the surface of a rectangular open-top coco coir grow bag (printed white coir bag, about one gallon) with a cannabis plant growing from the open top, glistening wet patch spreading across the coir, greenhouse grow setting, ultra sharp detail. NOT a fabric pot, NOT a terracotta pot.",
  "caption":"An irrigation shot at a time that you select makes the coco coir in the bag wet. Small shots fill the root zone again in steps.","alt":"Drip irrigation on a bag of coco coir"},

 # ---- grow-room systems ----
 {"slug":"grow-room-systems","n":1,"sec":0,"model":CIN,"ar":"16:9","res":"2k",
  "prompt":"Epic cinematic wide shot of a pristine indoor cannabis grow room at peak flower, uniform canopy of healthy plants under powerful LED bar lights, visible airflow, clean white walls, atmospheric haze, symmetrical composition, photoreal, high-end facility",
  "caption":"The room as one system. Light, climate, airflow and water are in balance, and the uniformity of the canopy is high.","alt":"Very clean indoor grow room with LED lights"},
 {"slug":"grow-room-systems","n":2,"sec":4,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic: close-up of a digital climate sensor and controller unit mounted among cannabis plants in a grow room, reading temperature and humidity, LED light glow, condensation-free, crisp detail",
  "caption":"A climate sensor at the height of the canopy. The measurements are inputs that have an effect on all the parts of the coupled system.","alt":"Climate sensor in the canopy"},

 # ---- airflow design ----
 {"slug":"airflow-design","n":1,"sec":6,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic: oscillating wall fans and clip fans positioned around a cannabis canopy, leaves gently fluttering in the breeze, motion in the foliage, indoor grow room under LED, dynamic, sharp",
  "caption":"Fans in positions that move air through the canopy. Each leaf must move a small distance.","alt":"Fans that cause airflow above the canopy"},
 {"slug":"airflow-design","n":2,"sec":2,"model":GPT,"ar":"16:9","res":"1k",
  "prompt":"Clean labelled scientific cross-section diagram of a single leaf showing the boundary layer of still air, arrows of moving air thinning it, CO2 entering and water vapour leaving, minimalist white background, crisp vector style with clear small labels",
  "caption":"The boundary layer of a leaf. Moving air makes the boundary layer thinner (diagram with labels).","alt":"Diagram of the boundary layer of a leaf"},

 # ---- mould risk ----
 {"slug":"mould-risk","n":1,"sec":3,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic macro: a dense cannabis flower bud with the early grey fuzzy rot of botrytis starting deep inside, a yellowing leaf pulling away, dramatic detail, slightly clinical documentary lighting, sharp focus on the affected cola",
  "caption":"Bud rot (Botrytis) at the first stage, in the inner part of a cola with a high density. Scouting found the rot at this stage.","alt":"Botrytis bud rot at a high magnification"},
 {"slug":"mould-risk","n":2,"sec":5,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic: a grower in nitrile gloves inspecting cannabis buds with a bright LED loupe light during late flower scouting, focused close inspection, grow room background softly blurred, documentary realism",
  "caption":"Scouting is a task for each day in the last part of flowering. Five minutes with a bright light finds the rot before it causes damage to the other buds.","alt":"Scouting of buds for mold"},

 # ---- root zone TEROS-12 ----
 {"slug":"root-zone-teros12","n":1,"sec":0,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic product macro on a clean light-grey surface: a professional research-grade volumetric water content sensor, a flat white rectangular epoxy probe body about 9 cm long with three thin parallel polished stainless-steel needle prongs about 5 cm long extending from one end, and a thin black signal cable with a small black cylindrical ferrite choke bead near it; soft even studio lighting, crisp scientific product photography, ultra detailed. NOT a handheld dial meter, no round gauge, no screen.",
  "caption":"A capacitance probe with high precision: a white body, three thin prongs and a cable with a ferrite bead. It is not a low-cost meter with a gauge.","alt":"Capacitance probe for the root zone"},
 {"slug":"root-zone-teros12","n":2,"sec":2,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic close-up in a commercial cannabis grow: a research-grade capacitance substrate sensor (white-and-black rectangular body with thin polished steel prongs and a thin black cable with a cylindrical ferrite bead) inserted at an angle into an open-top one-gallon coco coir grow bag, thin white 4mm drip-irrigation lines arching over the bag with drip stakes, green cannabis stems and foliage rising above, a small irrigation controller unit with a screen on the floor in the foreground, bright even greenhouse lighting, documentary realism, sharp focus",
  "caption":"A capacitance probe in a bag of coco coir, with drip lines above the bag. A cable connects the probe to a controller.","alt":"Capacitance probe in a bag of coco coir, with drip lines"},

 # ---- smart watering VRWE ----
 {"slug":"smart-watering-vrwe","n":1,"sec":0,"model":GPT,"ar":"16:9","res":"1k",
  "prompt":"Clean modern infographic-style illustration: multiple sensor signals (moisture, EC, temperature, light) flowing as arrows into a glowing central 'brain' node that outputs a single watering decision, minimalist tech aesthetic, soft greens and greys, clear small labels",
  "caption":"Sensor fusion: the software controller puts many signals that have noise together in one estimate, and it gives a confidence value for the estimate. Then it makes one decision.","alt":"Drawing of sensor fusion in a software controller"},

 # ---- signal & noise ----
 {"slug":"signal-and-noise","n":1,"sec":3,"model":GPT,"ar":"16:9","res":"1k",
  "prompt":"Clean data-visualization style image: a noisy jittery sensor time-series line with statistical control limit bands, one clear point breaking out past the band highlighted as a real 'signal', minimalist chart, white background, crisp labels",
  "caption":"Control limits show the difference between a signal and noise. A value that is not in the control limits is a signal. A value in the control limits is noise.","alt":"Control chart with a signal and noise"},

 # ---- closed loop ----
 {"slug":"closed-loop","n":1,"sec":2,"model":GPT,"ar":"16:9","res":"1k",
  "prompt":"Clean labelled control-loop diagram: levers (light, climate, water) feeding a plant, sensors reading plant state, feedback arrow returning to a controller and back to the levers, circular flow, minimalist, white background, small clear labels",
  "caption":"The closed loop: change a lever, measure the plant state, compare it with the setpoint, and adjust. Then the cycle starts again.","alt":"Diagram of closed-loop control"},

 # ---- plant-state dashboard ----
 {"slug":"plant-state-dashboard","n":1,"sec":0,"model":GPT,"ar":"16:9","res":"1k",
  "prompt":"Clean modern dashboard UI mockup on a dark screen showing plant-state indicators (transpiration, stress, growth mode) as clear gauges and a canopy diagram instead of raw numbers, professional product design, crisp legible labels",
  "caption":"A dashboard that shows the state of the plant, and not only the raw numbers from the sensors.","alt":"Drawing of a plant-state dashboard"},

 # ---- f2 crop steering ----
 {"slug":"f2-crop-steering","n":1,"sec":3,"model":GPT,"ar":"16:9","res":"1k",
  "prompt":"Clean infographic board: the daily irrigation cycle split into four phases P0 P1 P2 P3 along a 24-hour timeline with a root-zone moisture curve rising and falling, minimalist, white background, clear labels",
  "caption":"The P0 to P3 cycle of one day on one board: dry, fill again, keep full, dry.","alt":"Board of the P0 to P3 cycle of one day"},

 # ---- irrigation manual ----
 {"slug":"irrigation-manual","n":1,"sec":2,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic: a tidy fertigation hardware setup, a pump, mixing tank, manifold and rows of drip lines feeding cannabis plants, clean tubing, professional installation, grow room, sharp technical detail",
  "caption":"Clean equipment for fertigation: pump, tank, manifold and dripper lines.","alt":"Fertigation and irrigation equipment"},

 # ---- cloning ----
 {"slug":"cloning","n":1,"sec":4,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic: fresh cannabis cuttings standing in rockwool cubes inside a clear humidity dome propagator, tiny white roots just emerging, water droplets on the dome, soft propagation lighting, macro detail",
  "caption":"Cuttings in rockwool cubes in a humidity dome. The first white roots show.","alt":"Cannabis clones in a humidity dome"},
 {"slug":"cloning","n":2,"sec":3,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic close-up: a freshly prepared cannabis cutting being dipped into a small pot of clear rooting gel, gloved hand holding the green stem, clean propagation bench with rockwool cubes and a humidity dome behind, soft propagation light, shallow depth of field, detailed",
  "caption":"Put the bottom end of a new cutting in rooting hormone gel. Then put the cutting in a rockwool cube.","alt":"Cannabis cutting with the end in rooting hormone gel"},

 # ---- nutrient mixing athena ----
 {"slug":"nutrient-mixing-athena","n":1,"sec":4,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic: a 50 litre plastic tank of nutrient solution being mixed with a paint-mixer paddle on a cordless drill creating a vortex, white mineral salt powder dissolving, hot water steam, clean grow-room utility area, sharp detail",
  "caption":"A full bag of powder in a 50 L tank with hot water. A paddle on a drill mixes the solution until it is transparent.","alt":"Nutrient stock tank, with a paddle on a drill that mixes the solution"},

 # ---- light acclimation ----
 {"slug":"light-acclimation","n":1,"sec":3,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic: a light meter / PAR sensor held over a healthy cannabis canopy under bright LED bar lights, reading on the meter, intense even lighting, grow room, crisp detail",
  "caption":"Measure the PPFD at the canopy. Increase the light in small steps to a value that you measure. Do not use an estimate that you make with your eyes.","alt":"PAR meter above the canopy"},
 {"slug":"light-acclimation","n":2,"sec":2,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic macro: cannabis fan leaves showing light bleaching, pale white-yellow tips on the topmost leaves closest to the lamp while lower leaves stay deep green, documentary clarity, sharp",
  "caption":"Bleaching from light: white tips at the top of the canopy, on the leaves near the lamp. This occurs when the intensity is more than the capacity of the plant.","alt":"Cannabis leaves with white tips from bleaching"},

 # ---- defoliation & training ----
 {"slug":"defoliation-training","n":1,"sec":3,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic top-down: a cannabis plant trained flat across a horizontal trellis net (SCROG), even canopy of shoot tips poking through the squares, lush green, grow-room lighting, sharp detail",
  "caption":"A SCROG net makes the canopy flat. Thus each bud site gets the same quantity of light.","alt":"Canopy on a SCROG trellis, from above"},
 {"slug":"defoliation-training","n":2,"sec":4,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic: a defoliated and lollipopped cannabis plant in early flower, lower growth stripped to bare stem, open airy structure with clear bud sites up top, clean grow room, documentary realism",
  "caption":"After lollipopping and defoliation, more energy and more airflow go to the top bud sites, which make the flowers that you harvest.","alt":"Cannabis plant after lollipopping"},

 # ---- IPM SOP ----
 {"slug":"ipm-sop","n":1,"sec":4,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic: a yellow sticky trap among cannabis plants with a few fungus gnats stuck to it, and a grower's hand placing it, scouting context, grow room, sharp macro detail",
  "caption":"A yellow sticky trap gives a first sign of a problem, and its cost is low. You count the pests on the trap, and you do not make an estimate.","alt":"Yellow sticky trap in the canopy"},
 {"slug":"ipm-sop","n":2,"sec":2,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic macro: a sachet of predatory mites being sprinkled onto a cannabis leaf as biological control, tiny beneficial insects visible, soft natural light, documentary detail",
  "caption":"A release of predator mites for biocontrol. The predators stay in the canopy and eat the pests.","alt":"A release of predator mites"},

 # ---- harvest / dry / trim / cure ----
 {"slug":"harvest-dry-trim-cure","n":1,"sec":1,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic extreme macro: cannabis trichomes on a flower at harvest maturity, milky-cloudy heads with a few amber, viewed through a jeweller's loupe clarity, glistening resin, ultra sharp, scientific",
  "caption":"Trichomes at harvest: most heads are cloudy, and a small number are amber. The color of the heads is the signal of maturity.","alt":"Cannabis trichomes at a high magnification"},
 {"slug":"harvest-dry-trim-cure","n":2,"sec":4,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic: whole cannabis branches hung upside down in a clean climate-controlled drying room, even spacing, soft low light, hygrometer on the wall, documentary facility photography",
  "caption":"A controlled hang-dry: branches hang in a dry room that is cool and dark, with the fans on and an RH of approximately 60%.","alt":"Cannabis dry room"},
 {"slug":"harvest-dry-trim-cure","n":3,"sec":6,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic: cured cannabis flower in clear glass mason jars with a small hygrometer inside reading about 60 percent, being burped, clean shelf, warm soft light, premium detail",
  "caption":"Cure in sealed glass jars with a hygrometer. Burp the jars to keep the correct water activity.","alt":"Cannabis in glass jars for the cure"},

 # ---- GMP hash lab ----
 {"slug":"gmp-hash-lab","n":1,"sec":0,"model":CIN,"ar":"16:9","res":"2k",
  "prompt":"Epic cinematic: a gowned technician in full cleanroom suit and gloves working stainless-steel solventless hash-wash equipment in a spotless GMP cleanroom, dramatic clean lighting, reflective surfaces, premium pharmaceutical facility, photoreal",
  "caption":"GMP processing: gowning of the personnel and stainless steel in a controlled cleanroom.","alt":"Technician in a GMP cleanroom for hash"},
 {"slug":"gmp-hash-lab","n":2,"sec":3,"model":GPT,"ar":"16:9","res":"1k",
  "prompt":"Clean labelled facility floor-plan diagram showing cleanroom zoning by grade, one-directional material and personnel flow arrows, airlocks and gowning rooms, minimalist top-down schematic, white background, clear small labels",
  "caption":"Zones for the flow of material and personnel. Each clean shell is in the next shell, in the sequence of the cleanroom grades.","alt":"Diagram of the zones of a GMP facility"},

 # ---- facility 3D ----
 {"slug":"facility-3d","n":1,"sec":0,"model":GPT,"ar":"16:9","res":"1k",
  "prompt":"Clean 3D architectural render: a top-down/isometric model of a cannabis grow facility floor plan with labelled rooms (veg, flower, dry, trim), equipment blocks and airflow, modern CAD visualization style, crisp labels",
  "caption":"When you make a 3D model of the facility, you find clashes before construction starts.","alt":"3D model of the floor plan of a facility"},

 # ---- fact-check educational pack (2026-07) ----
 {"slug":"seeds-germination","n":1,"sec":5,"model":FC,"ext":"jpg","ar":"16:9","res":"2k",
  "prompt":"(factcheck) seedling roots drink under humidity dome in rockwool+coco",
  "caption":"The roots continue to absorb the water. A humidity dome decreases the quantity of water that the air removes from the leaves. This effect does not show that the seedling absorbs water through its leaves.","alt":"Seedling in rockwool and coco in a humidity dome"},
 {"slug":"harvest-dry-trim-cure","n":4,"sec":4,"model":FC,"ext":"jpg","ar":"16:9","res":"2k",
  "prompt":"(factcheck) water activity meter and moisture meter on dried flower",
  "caption":"The same moisture content can have different water activity values, from a dry value to a value with mold risk. Use aw (here approximately 0.61) to control the post-harvest procedure, and not only the moisture content.","alt":"Meters for water activity and moisture, with dried buds"},
 {"slug":"mould-risk","n":3,"sec":2,"model":FC,"ext":"jpg","ar":"16:9","res":"2k",
  "prompt":"(factcheck) cola room RH vs inside microclimate",
  "caption":"The room sensor can show a safe value, but the inner part of a cola with a high density is wetter. Bud rot starts in this inner part.","alt":"Diagram of a cola: outer part, and inner part with high humidity"},
 {"slug":"mould-risk","n":4,"sec":3,"model":FC,"ext":"jpg","ar":"16:9","res":"2k",
  "prompt":"(factcheck) late flower aisle climate meter",
  "caption":"Do the measurement in the aisle and at the height of the canopy. In the last part of flowering, the target is frequently approximately 45 to 55% RH, with strong airflow through the canopy.","alt":"Hygrometer and thermometer in a room in the last part of flowering"},
 {"slug":"under-canopy-lighting","n":1,"sec":2,"model":FC,"ext":"jpg","ar":"16:9","res":"2k",
  "prompt":"(factcheck) canopy spectrum filter green FR enriched",
  "caption":"Below the canopy, the fractions of blue and red are lower than above the canopy. The fractions of green and far-red are higher. The light does not have a high fraction of red.","alt":"Diagram of the LED spectrum above and below the canopy"},
 {"slug":"scaling-high-light","n":1,"sec":1,"model":CD,"ext":"svg","ar":"16:9","res":"1k",
  "prompt":"(factcheck) leaf vs canopy light curves",
  "caption":"The photosynthesis of one leaf can stop to increase at light saturation. But the flower yield of the whole canopy continues to increase with the light. With ambient CO₂, 800 µmol is not a PPFD limit for all rooms.","alt":"Graphs of leaf photosynthesis and canopy yield with PPFD"},
 {"slug":"lighting-fundamentals","n":1,"sec":3,"model":CD,"ext":"svg","ar":"16:9","res":"1k",
  "prompt":"(factcheck) leaf vs canopy light curves",
  "caption":"The targets of PPFD are for the canopy. The curve of gas exchange for one leaf does not give the limit of the yield of the room.","alt":"Graphs of the response to light: leaf and canopy"},
 {"slug":"coco-crop-steering","n":3,"sec":3,"model":CD,"ext":"svg","ar":"16:9","res":"1k",
  "prompt":"(factcheck) Caplan one drought vs daily drybacks",
  "caption":"One drought in the last stage of the crop is not the same test as the generative dryback cycles of each day. In a drought test, you select the time of the drought carefully.","alt":"Charts of the VWC for one drought and for dryback cycles each day"},
 {"slug":"coco-crop-steering","n":4,"sec":2,"model":CD,"ext":"svg","ar":"16:9","res":"1k",
  "prompt":"(factcheck) dryback percentage points",
  "caption":"Dryback is a quantity in percentage points: the VWC at the peak minus the VWC at the trough. It is not a percentage of the peak, unless you write that it is.","alt":"Dryback in percentage points and as a percentage of the peak"},
 {"slug":"rockwool-crop-steering","n":1,"sec":2,"model":CD,"ext":"svg","ar":"16:9","res":"1k",
  "prompt":"(factcheck) Caplan one drought vs daily drybacks",
  "caption":"Drybacks each day have a connection to a controlled water deficit. They are not a copy of one drought test in the last part of flowering.","alt":"Diagram of one drought and of drybacks each day"},
 {"slug":"one-steering-law","n":1,"sec":2,"model":CD,"ext":"svg","ar":"16:9","res":"1k",
  "prompt":"(factcheck) dryback percentage points",
  "caption":"Measure the dryback in percentage points. When the water content decreases from 78% to 58%, the dryback is 20 points.","alt":"Gauge that shows the dryback in points"},
 {"slug":"one-steering-law","n":2,"sec":4,"model":CD,"ext":"svg","ar":"16:9","res":"1k",
  "prompt":"(factcheck) Caplan vs daily drybacks",
  "caption":"One drought of some days in the last stage of the crop is not the same as dryback cycles each day for some weeks.","alt":"Diagram of a drought test and of drybacks each day"},
 {"slug":"irrigation-manual","n":2,"sec":2,"model":CD,"ext":"svg","ar":"16:9","res":"1k",
  "prompt":"(factcheck) veg vs gen dryback phases",
  "caption":"Vegetative steering: smaller drybacks, and the substrate stays wetter. Generative steering: larger controlled drybacks. Example: the VWC for each day of the crop.","alt":"Chart of VWC and dryback in vegetative and generative steering"},
 {"slug":"f2-crop-steering","n":2,"sec":2,"model":CD,"ext":"svg","ar":"16:9","res":"1k",
  "prompt":"(factcheck) veg vs gen dryback phases",
  "caption":"Automatic steering: the dryback in the two steering modes. Vegetative steering has smaller drybacks. Generative steering has larger controlled drybacks.","alt":"Chart of VWC and dryback in each crop phase"},
 {"slug":"water-quality","n":1,"sec":3,"model":CD,"ext":"svg","ar":"16:9","res":"1k",
  "prompt":"(factcheck) DO saturation vs temperature",
  "caption":"The saturation dissolved oxygen (DO) is approximately 9 mg/L at 20 °C and approximately 8 mg/L at 26 °C, and not 5 to 6 ppm and not 3 to 4 ppm. Continue to keep the water cool and to use aeration for the roots.","alt":"Curve of the saturation dissolved oxygen"},
 {"slug":"pppe","n":1,"sec":2,"model":CD,"ext":"svg","ar":"16:9","res":"1k",
  "prompt":"(factcheck) clean dirty two kit flow",
  "caption":"Two sets of PPE: one for cultivation, and a different set for post-harvest. Do not go into the dry room or the trim room in the coverall from the flowering room.","alt":"Diagram of two gowning flows in a facility"},
 {"slug":"pppe","n":2,"sec":4,"model":CD,"ext":"svg","ar":"16:9","res":"1k",
  "prompt":"(factcheck) log reduction table",
  "caption":"Log reduction: 1 log reduction is approximately 90%, 2 log reductions are approximately 99%, and 3 log reductions are approximately 99.9%. The value of 83% for 3 log reductions is incorrect.","alt":"Table of log reductions for hand hygiene"},

]

# Dropped AI diagram images (image-gen mangles labels; papers already have real SVG diagrams).
_SKIP = {("airflow-design", 2), ("smart-watering-vrwe", 1), ("signal-and-noise", 1),
         ("closed-loop", 1), ("plant-state-dashboard", 1), ("f2-crop-steering", 1),
         ("gmp-hash-lab", 2), ("facility-3d", 1)}
IMAGES = [im for im in IMAGES if (im["slug"], im["n"]) not in _SKIP]

GK = "grok_imagine"
IMAGES += [
 # ---- hash rosin pressing (photoreal; sec = 0-based section index) ----
 {"slug":"hash-rosin-pressing","n":1,"sec":0,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"macro frosty trichome-covered bud",
  "caption":"The raw material: each white &lsquo;crystal&rsquo; is a trichome, a stalk with a resin head. In the solventless method, you collect these heads and push the resin out of them.","alt":"Cannabis bud with many trichomes, at a high magnification"},
 {"slug":"hash-rosin-pressing","n":2,"sec":1,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"rosin flowing from press onto parchment",
  "caption":"The full procedure in one photo: warm plates, folded parchment, and rosin with a gold color that flows. The heat lets the resin flow. The pressure pushes the resin through the mesh. The mesh keeps the unwanted material in the bag.","alt":"Rosin with a gold color that flows from a press onto parchment"},
 {"slug":"hash-rosin-pressing","n":3,"sec":2,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"finished rosin jar and dab rig",
  "caption":"The end of the sequence of steps: a stable, finished concentrate and the dab rig. The dab rig changes the rosin into vapor. The steps before this step give protection to the rosin in this jar.","alt":"Jar of rosin next to a dab rig"},
 {"slug":"hash-rosin-pressing","n":4,"sec":3,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"micron bags loaded with hash",
  "caption":"Fill the micron bag: put 2 to 7 g of hash in a bag of nylon mesh with small holes. Fold the bag two times, and put it on new parchment. A bag with a smaller micron gives rosin with less unwanted material.","alt":"A person puts bubble hash in micron press bags"},
 {"slug":"hash-rosin-pressing","n":5,"sec":10,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"ice water hash washing vessel",
  "caption":"The wash: water that is almost frozen, light agitation, and a stack of micron bags below. Cold lets the trichome heads break from the plant with no damage to the heads.","alt":"Vessel for the ice-water wash of hash, with a paddle and bags"},
 {"slug":"hash-rosin-pressing","n":6,"sec":10,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"microplaned hash on freeze dryer trays",
  "caption":"Correct drying: hash that you cut with a microplane, in a thin layer on trays for the freeze dryer. In a vacuum, the water leaves the hash and the terpenes stay.","alt":"Bubble hash cut with a microplane, on trays of a freeze dryer"},
 {"slug":"hash-rosin-pressing","n":7,"sec":11,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"press plates with PID controller",
  "caption":"The important equipment: plates that are at the same temperature in all areas, and a PID that keeps the setpoint. Plates of low cost have changes of temperature and can burn the rosin. High precision makes a press at a low temperature possible.","alt":"Plates of a rosin press with a PID temperature controller"},
 {"slug":"hash-rosin-pressing","n":8,"sec":12,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"trichome heads under magnification",
  "caption":"Examine the material. With magnification, you can see the size of the heads and how many heads have no damage. You use this information to select the micron and the temperature.","alt":"Trichome heads that are not attached, with magnification"},
 {"slug":"hash-rosin-pressing","n":9,"sec":13,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"cold-cure badder jar",
  "caption":"Badder from a cold cure: keep the sealed rosin at 10 to 21 °C for days to weeks. The cure makes this soft, smooth texture, and the monoterpenes with a high rate of evaporation stay in the jar.","alt":"Jar of rosin badder from a cold cure"},
 {"slug":"hash-rosin-pressing","n":10,"sec":13,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"THCa diamonds in terp sauce",
  "caption":"Diamonds and sauce: crystals of THCa in the liquid sauce, which has many terpenes. Only THCa can crystallize into diamonds. After decarboxylation, the oil stays liquid.","alt":"THCa diamond crystals in sauce with a gold color"},
]

IMAGES += [
 # ---- ripening & harvest timing ----
 {"slug":"ripening-harvest-timing","n":1,"sec":3,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"mixed-maturity trichomes macro",
  "caption":"Trichomes at different stages on the calyx: most heads are cloudy, and the first heads become amber. The harvest window for flower starts.","alt":"Cannabis trichomes at a high magnification, with transparent, cloudy and amber resin heads together"},
 {"slug":"ripening-harvest-timing","n":2,"sec":4,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"loupe scoping marked cola",
  "caption":"The reading of the trichomes: use a loupe of 30 to 60x on a position with a mark at mid-cola, in white light. Do this at an interval of two days.","alt":"Grower who examines a cannabis bud with a loupe at a position with a mark"},
 {"slug":"ripening-harvest-timing","n":3,"sec":7,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"late-flower fade with hygrometer",
  "caption":"The last two weeks: the fade occurs, the colas have a high density, and the hygrometer shows if you can continue to wait.","alt":"Room with cannabis in ripening, with leaves in the fade and a hygrometer for the control of humidity"},
 {"slug":"ripening-harvest-timing","n":4,"sec":9,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"whole plants hung in dry room",
  "caption":"Correct harvest day: whole plants hung on the line with space between them, in a dry room. The measurements show 15 to 16 °C and 60% RH. A tag is on each stem.","alt":"Whole plants of cannabis, hung with space between them, in a dark dry room"},
 # ---- transplanting ----
 {"slug":"transplanting","n":1,"sec":4,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"root-bound ball slide-out test",
  "caption":"The root ball test shows a root-bound root ball. The root mat of circling roots shows that the transplant is after the correct time.","alt":"A person moves a root-bound cannabis root ball with circling roots out of a black pot"},
 {"slug":"transplanting","n":2,"sec":5,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"container size ladder lineup",
  "caption":"The sequence of containers: each step is approximately two to four times the volume of the previous container.","alt":"Row of pots, each larger than the previous pot, with cannabis plants at different growth stages"},
 {"slug":"transplanting","n":3,"sec":7,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"lowering root ball into coco",
  "caption":"When you remove the plant from the pot, hold the root ball. Do not hold the stem. Put your fingers across the medium. Hold the root ball all the time while you lower it into the new container.","alt":"Hands in gloves put a cannabis root ball in a larger container of coco"},
 {"slug":"transplanting","n":4,"sec":8,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"block seated onto rockwool slab",
  "caption":"Block on slab: put the block on the slab. All of its bottom must touch the slab. Then stop the irrigation. Thus the roots go into the slab (rooting-in).","alt":"A person puts a rockwool block with a young plant on a slab with plastic film in a greenhouse"},
 # ---- veg management ----
 {"slug":"veg-management","n":1,"sec":3,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"veg room rows under LED",
  "caption":"A room in the vegetative stage. Each plant must fill its canopy area, and the canopy area sets the number of days of the vegetative stage.","alt":"Rows of cannabis plants in the vegetative stage on benches, with LED lighting, in an indoor grow room"},
 {"slug":"veg-management","n":2,"sec":6,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"topped plant two leaders macro",
  "caption":"Two equal leaders one week after the topping. Add the days of the recovery to the days of the vegetative stage before you do the topping.","alt":"Cannabis plant after topping, with two new leaders at the top node"},
 {"slug":"veg-management","n":3,"sec":7,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"trellis net over level canopy",
  "caption":"Install the net when the plants are short, before the stretch. The net holds the plants while the stretch occurs. It is not a correction after the stretch.","alt":"Trellis net above a level cannabis canopy in vegetative growth"},
 {"slug":"veg-management","n":4,"sec":10,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"white roots at pot walls",
  "caption":"The pre-flip check: white roots at the walls of the pot, and a night dryback that is stable.","alt":"White cannabis roots in good condition on the outer surface of a root ball of coco coir"},
 # ---- mother plants ----
 {"slug":"mother-plants","n":1,"sec":0,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"mother room wide shot",
  "caption":"A mother room for production: stock plants with flat tops on benches. Each plant has a label, and each tool is in its position.","alt":"Indoor cannabis mother room with rows of stock plants with flat tops on benches that you can move"},
 {"slug":"mother-plants","n":2,"sec":5,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"pruned mother scaffold frame",
  "caption":"The frame of a mother plant: scaffolds of wood below, and a level canopy of vertical shoots that you can harvest above.","alt":"Cannabis mother plant after pruning, with a frame of scaffolds of wood and a flat top of vertical shoots"},
 {"slug":"mother-plants","n":3,"sec":9,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"snips in bleach between plants",
  "caption":"To prevent HpLVd infection, use a new blade or a sanitized blade for each plant, each time. The blade is the primary method by which HpLVd moves from one plant to the next plant.","alt":"Hands in gloves put a pruning blade in a bleach solution near a cannabis mother plant"},
 {"slug":"mother-plants","n":4,"sec":11,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"clone tray beside mother succession",
  "caption":"The mother plant that you replace continues to supply cuttings. The replacement plant, which has a test result, becomes larger.","alt":"Tray of cannabis clones with roots near a large mother plant. The clones are the replacement plants."},
 # ---- genetics & pheno hunting ----
 {"slug":"genetics-phenohunting","n":1,"sec":6,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"tagged pheno-hunt cohort in veg",
  "caption":"A group of plants in a phenotype hunt, in the vegetative stage: one batch, with the same pots and the same feed. Give each plant a permanent ID before you make a selection.","alt":"Rows of young cannabis plants with tags, in the same pots, with LED light"},
 {"slug":"genetics-phenohunting","n":2,"sec":7,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"two colas side-by-side scoring",
  "caption":"Make the selection with a scoring table that you write before the selection. Compare the structure, the density and the ripeness of the plants side by side. Do not use your memory.","alt":"Two cannabis colas with labels, side by side, near a sheet for scores"},
 {"slug":"genetics-phenohunting","n":3,"sec":9,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"two mothers plus backup cuttings",
  "caption":"Redundancy: two mother plants with labels and a tray of backup cuttings with roots. These items keep the clone safe.","alt":"Two cannabis mother plants with labels, and a tray of cuttings with roots in front"},
 {"slug":"genetics-phenohunting","n":4,"sec":11,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"pollen collection vials",
  "caption":"Pollen collection: collect the pollen above paper, dry it, put it through a sieve, and keep it cold in vials with labels. Pollen is a risk to the facility, thus control it at all times.","alt":"Cannabis pollen on paper near a sieve and vials with labels"},
 # ---- temp, humidity & VPD ----
 {"slug":"temp-humidity-vpd","n":1,"sec":0,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"canopy-height aspirated sensor",
  "caption":"The important value is the value that you measure here: at the height of the canopy, in the air around the plants.","alt":"Indoor cannabis canopy with LED light, and a climate sensor at the height of the canopy"},
 {"slug":"temp-humidity-vpd","n":2,"sec":9,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"night condensation on duct",
  "caption":"At lights-off, with no dehumidification: the temperature of the room decreases in the direction of the dew point of the air. The surfaces with the lowest temperatures become colder than the dew point first.","alt":"Drops of condensation on a metal duct and a wall in a dark grow room at night"},
 {"slug":"temp-humidity-vpd","n":3,"sec":10,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"IR thermometer on leaf",
  "caption":"The change with the lowest cost that makes the VPD measurement better: measure the temperature of the leaf, and do not use an estimate.","alt":"IR thermometer for the temperature of the surface of a cannabis leaf"},
 {"slug":"temp-humidity-vpd","n":4,"sec":11,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"dehumidifier in grow aisle",
  "caption":"Almost all the irrigation water goes into the air of the room because the plants transpire the water as vapor. Select the size of the dehumidifier for the volume of irrigation water each day. Do not select it for the volume of the room.","alt":"Dehumidifier with a drain hose between rows of cannabis plants in a grow room"},
 # ---- lab testing & COAs ----
 {"slug":"lab-testing-coas","n":1,"sec":3,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"COA beside labelled jars",
  "caption":"The COA is with the batch. The COA stays with the jars of the batch that it gives information about.","alt":"Hands in gloves with a printed COA near jars with labels of dried cannabis flower"},
 {"slug":"lab-testing-coas","n":2,"sec":5,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"HPLC autosampler loading",
  "caption":"Potency test with HPLC: the extract moves through a column in a liquid at a temperature near room temperature. Thus the acid cannabinoids and the neutral cannabinoids go to the detector at different times and make two different peaks.","alt":"Technician who puts amber vials in the autosampler of an HPLC, with a chromatogram on a screen"},
 {"slug":"lab-testing-coas","n":3,"sec":7,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"increment sampling into jar",
  "caption":"Collect many small samples and not a grab sample. Collect the small samples from different containers and positions. Make a composite sample and record the data.","alt":"Hands in gloves that put small samples of flower from many bags in one sample jar with a label"},
 {"slug":"lab-testing-coas","n":4,"sec":8,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"petri plate vs qPCR",
  "caption":"Two methods for the microbial test: colonies on a culture plate, and copies of DNA that qPCR counts. The same batch can have a satisfactory result with one method and an unsatisfactory result with the other method.","alt":"Petri dish with mold colonies in front of a qPCR instrument, with amplification curves on a screen"},
 # ---- unit economics ----
 {"slug":"unit-economics","n":1,"sec":5,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"HPS vs LED split frame",
  "caption":"The same crop with two generations of fixtures. The installed watts are not the same, thus the g/W metric changes.","alt":"Two cannabis flowering rooms side by side: one room with orange HPS light, and one room with LED light that is white and magenta"},
 {"slug":"unit-economics","n":2,"sec":8,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"trim room hand labour",
  "caption":"The largest cost in the list of costs is labor. Hand trimming uses scissors and not electricity.","alt":"Personnel at stainless steel benches in a clean trim room, with hand trimming of dried cannabis flower"},
 {"slug":"unit-economics","n":3,"sec":9,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"empty room mid-turnaround",
  "caption":"Turn time is the number of days when the room has no revenue. These days occur again in each cycle.","alt":"Clean cannabis grow room with no plants and bare benches, in the turn time between crops"},
 {"slug":"unit-economics","n":4,"sec":7,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"harvest weigh-in spreadsheet",
  "caption":"The primary metric is one division. Divide all the dollars of the year by all the grams of the year.","alt":"Dried cannabis flower on a scale, near a clipboard, a calculator and a spreadsheet"},
 # ---- compliance & track-trace ----
 {"slug":"compliance-track-trace","n":1,"sec":3,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"operator reading licence clipboard",
  "caption":"A license is not only a certificate on the wall. It gives the activities, the conditions and the dates of renewal. All personnel must know them.","alt":"Grower who reads a printed license on a clipboard in a corridor of the facility"},
 {"slug":"compliance-track-trace","n":2,"sec":6,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"barcode tag on plant stem",
  "caption":"Each plant has a tag with a UID. The tag connects the plant in the room to its record in the ledger.","alt":"Hands in gloves that attach a barcode tag to the stem of a cannabis plant"},
 {"slug":"compliance-track-trace","n":3,"sec":8,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"logbook entry at bench",
  "caption":"Contemporaneous means that you make the record at the time of the work and in the area of the work. You do not make the record after the work.","alt":"Hand in a glove that writes in a logbook on a stainless steel bench near an EC meter"},
 {"slug":"compliance-track-trace","n":4,"sec":11,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"witnessed waste weigh-out",
  "caption":"Destruction is an event with weights and witnesses. The waste stays in the chain of custody until you complete the record of the destruction.","alt":"Two persons weigh a sealed bag of waste on a floor scale, and one person signs a form"},
 # ---- HVAC & dehumidification ----
 {"slug":"hvac-dehumidification","n":1,"sec":0,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"rooftop climate plant",
  "caption":"The other half of the system is the climate system. It removes the heat and the water from the room.","alt":"Packaged units (RTU) on a roof, with insulated ducts, for an indoor cultivation building"},
 {"slug":"hvac-dehumidification","n":2,"sec":4,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"ceiling dehu over canopy",
  "caption":"The quantity of water that goes in is equal to the quantity of water that you must remove. The dehumidifier removes the irrigation water that goes into the air.","alt":"Dehumidifier on the ceiling, with a condensate drain pipe, above a flowering cannabis canopy"},
 {"slug":"hvac-dehumidification","n":3,"sec":8,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"lights-off condensation spike",
  "caption":"The humidity spike at lights-off: the water in the air is the same, but the air is colder. As a result, the room goes into the conditions for mold each night.","alt":"Dark grow room at lights-off, with condensation on a cold duct above flowers with a high density"},
 {"slug":"hvac-dehumidification","n":4,"sec":11,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"N+1 dehu bank",
  "caption":"N+1 redundancy: two units supply the load at night, and you install one more unit. If one unit stops, for example on a Saturday night, the remaining units supply the load, and there is no problem.","alt":"Three dehumidifier units of the same type, with a drain manifold for all of them"},
 # ---- cannabinoids & terpenes ----
 {"slug":"cannabinoids-terpenes","n":1,"sec":2,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"bract trichomes extreme macro",
  "caption":"Capitate-stalked trichomes at a high magnification. Each head has a storage cavity with a wall. The cavity contains the resin, which has cannabinoid acids and terpenes.","alt":"Photo of transparent stalked trichomes on a cannabis bract, at a high magnification"},
 {"slug":"cannabinoids-terpenes","n":2,"sec":7,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"dark cool drying room",
  "caption":"Dry the flower slowly in a cold, dark room. In a warm room, the monoterpenes evaporate from the flower first.","alt":"Dark, cool drying room with cannabis plants that hang on lines"},
 {"slug":"cannabinoids-terpenes","n":3,"sec":10,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"amber jars dark storage",
  "caption":"Storage: keep the flower cool, in darkness and sealed, and write the date on the jar. These steps prevent the damage that light and oxygen cause.","alt":"Amber jars of cannabis flower in a dark cabinet"},
 {"slug":"cannabinoids-terpenes","n":4,"sec":12,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"HPLC vials and COA",
  "caption":"The COA is the record of your procedures. It gives the acids and the neutral cannabinoids, and the terpene panel. The ratios show the history of the storage.","alt":"Laboratory bench with HPLC vials and a certificate of analysis"},
 # ---- energy & sustainability ----
 {"slug":"energy-sustainability","n":1,"sec":5,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"HPS-to-LED retrofit aisle",
  "caption":"A retrofit in progress: rows of HPS fixtures and new LED bars. The LED bars supply the same photons with approximately 40% less power. They also give less heat for the HVAC to remove.","alt":"Cannabis flowering room with HPS fixtures on one side and LED bars on the other side, in a lighting retrofit"},
 {"slug":"energy-sustainability","n":2,"sec":7,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"staged plant room units",
  "caption":"A climate system in stages: some smaller units give a capacity that agrees with the load of the room. This method is better than one unit that is too large, which starts and stops frequently. Hot-gas reheat replaces the coils of electric resistance.","alt":"Equipment room with two HVAC dehumidification units in stages, and condensate drain lines"},
 {"slug":"energy-sustainability","n":3,"sec":9,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"condensate reclaim corner",
  "caption":"Reuse of condensate: the water from the coil of the dehumidifier is almost distilled water. The water flows through a filter and a UV stage. Then you add minerals to it. Thus the plants use the water again, and it does not go to the drain.","alt":"Condensate line of a dehumidifier to a tank for collection, through a filter and a UV sterilizer"},
 {"slug":"energy-sustainability","n":4,"sec":12,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"CT clamps submetering panel",
  "caption":"Metering: CT submeters on each end use change the one number each month from the utility into data for each room and each system. The energy data show faults before the crop shows them.","alt":"Electrical panel that is open, with CT clamps and an energy submeter, near a tablet that shows a dashboard"},
 # ---- plant biology ----
 {"slug":"plant-biology","n":1,"sec":4,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"bract and stigmas macro",
  "caption":"Bracts on a female flower, with two stigmas on each bract. The photo shows the one flower of the diagram.","alt":"Photo of cannabis bracts with white stigmas, at a high magnification"},
 {"slug":"plant-biology","n":2,"sec":5,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"trichomes photomicrograph",
  "caption":"Capitate-stalked trichomes with magnification: heads that are transparent, milky and amber, on their stalks.","alt":"Stalked cannabis trichomes, in a photo made with a microscope"},
 {"slug":"plant-biology","n":3,"sec":9,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"female pre-flower at node",
  "caption":"A female pre-flower at a node. Use a loupe to do this check. The diagram of sex determination shows the same check.","alt":"Female cannabis pre-flower with white stigmas at a node of the stem"},
 {"slug":"plant-biology","n":4,"sec":12,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"healthy white root ball",
  "caption":"Roots in good condition below the substrate: bright white roots with many branches at transplant.","alt":"White cannabis roots in good condition around coco coir substrate"},
]

def by_slug():
    d = {}
    for im in IMAGES:
        d.setdefault(im["slug"], []).append(im)
    return d
