# -*- coding: utf-8 -*-
"""Image manifest. Drives gen_images.py (generation) AND build.py (embedding).
Each entry: slug, n (per-paper index), sec (0-based section to append the photo to,
clamped), model, ar, res, prompt, caption, alt. File = img/<slug>-<n>.jpg."""

MODEL_LABEL = {
    "nano_banana_2": "Nano Banana 2",
    "gpt_image_2": "GPT Image 2 (OpenAI)",
    "cinematic_studio_2_5": "Cinema Studio",
    "factcheck_pack": "Fact-check pack",
    "code_diagram": "Educational diagram",
    "grok_imagine": "Grok Imagine",
}

# NB = photoreal practical, GPT = labelled/diagram, CIN = epic/cinematic hero
# FC = fact-check educational pack (photo or code diagram)
NB, GPT, CIN, FC, CD = "nano_banana_2", "gpt_image_2", "cinematic_studio_2_5", "factcheck_pack", "code_diagram"

IMAGES = [
 # ---- tissue culture (photoreal step series; sec indices AFTER evidence panel insert) ----
 {"slug":"tissue-culture","n":1,"sec":6,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"still-air box TC workstation","caption":"Step — lab setup: a still-air box, alcohol, tools and culture jars. You need clean air, sterile tools and a warm lit shelf — not a hospital lab.","alt":"Home tissue culture still-air box workstation"},
 {"slug":"tissue-culture","n":2,"sec":7,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"aseptic tool sterilisation","caption":"Step — aseptic technique: flame or alcohol-wipe tools every time. Most beginner failures are contamination from hands, breath or dirty instruments.","alt":"Gloved hands sterilising TC tools"},
 {"slug":"tissue-culture","n":3,"sec":8,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"pouring agar media into jars","caption":"Step — make and sterilise medium: pour warm agar-based medium into vessels after autoclaving. Sugar + salts + hormones is the plant’s sealed-jar diet.","alt":"Pouring tissue culture medium into jars"},
 {"slug":"tissue-culture","n":4,"sec":5,"model":FC,"ext":"jpg","ar":"16:9","res":"2k",
  "prompt":"(factcheck) meristem vs HpLVd","caption":"Why meristem works: Hop Latent Viroid rides vascular tissue and often cannot reach the undifferentiated dome you excise.","alt":"Annotated meristem cutaway with HpLVd"},
 {"slug":"tissue-culture","n":5,"sec":9,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"healthy cannabis mother plant","caption":"Stage 0 — condition the donor: pick a vigorous, true-to-type mother and clean it up for 1–2 weeks before you cut. Garbage in, garbage out.","alt":"Healthy vegetative cannabis mother plant"},
 {"slug":"tissue-culture","n":6,"sec":10,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"cutting nodal explant","caption":"Stage I — cut a nodal explant: for first runs, a ~1 cm stem piece with one bud is the most forgiving starting piece.","alt":"Cutting a cannabis nodal explant with scalpel"},
 {"slug":"tissue-culture","n":7,"sec":10,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"surface sterilise explant bleach","caption":"Stage I — surface-sterilise: dilute bleach (or kit sterilant) kills microbes on the outside without cooking the tissue if timing is right.","alt":"Explant in sterilant solution"},
 {"slug":"tissue-culture","n":8,"sec":11,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"plating explant on agar","caption":"Initiation — plate the explant: set the sterile piece onto fresh medium and seal the vessel. Now it must wake up without contamination.","alt":"Placing explant on agar in culture jar"},
 {"slug":"tissue-culture","n":9,"sec":11,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"initiation culture shelf","caption":"Initiation — culture room: ~25 °C, long days of soft light, and daily eyes on every jar for the first weeks.","alt":"Tissue culture jars on growth shelf"},
 {"slug":"tissue-culture","n":10,"sec":12,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"meristem excision under microscope","caption":"Cleanup — meristem dissection: under a stereo microscope, cut only the tiny dome. This is the step that actually leaves most systemic disease behind.","alt":"Meristem excision under microscope"},
 {"slug":"tissue-culture","n":11,"sec":13,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"RT-qPCR sample prep","caption":"Indexing — prove it: a healthy-looking plant is not clean until an RT-qPCR (or equivalent lab test) says so. Send tissue; do not skip this.","alt":"Leaf tissue sample ready for viroid lab test"},
 {"slug":"tissue-culture","n":12,"sec":14,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"multiplication shoots in jars","caption":"Stage II — multiplication: cytokinin media push multiple shoots so one clean line becomes many vessels.","alt":"Multiple cannabis shoots multiplying in TC jars"},
 {"slug":"tissue-culture","n":13,"sec":14,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"hyperhydricity glassy shoots","caption":"Watch for hyperhydricity: glassy, waterlogged shoots that look lush but root and harden poorly. Cut hormone or humidity, not hope.","alt":"Hyperhydric glassy tissue culture shoots"},
 {"slug":"tissue-culture","n":14,"sec":15,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"in vitro rooting","caption":"Stage III — rooting: auxin media (or a simpler ex-vitro rooting path) turns a shoot into a plant with white roots.","alt":"Tissue culture shoot rooting in agar"},
 {"slug":"tissue-culture","n":15,"sec":16,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"acclimatisation under dome","caption":"Stage IV — acclimatisation: slowly lower humidity and raise light. Rushing weaning kills more plantlets than almost any other step.","alt":"TC plantlet hardening under humidity dome"},
 {"slug":"tissue-culture","n":16,"sec":17,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"clean mother stock plant","caption":"Re-establish the clean mother: veg her under long days in a scrubbed space, then take ordinary cuttings from a tested line.","alt":"Young clean cannabis mother from tissue culture"},
 {"slug":"tissue-culture","n":17,"sec":19,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"contamination vs clean jar","caption":"Troubleshooting — contamination: fuzzy mould or cloudy bacterial slime means that vessel is dead. Compare against a clean jar and throw out without opening if possible.","alt":"Contaminated tissue culture jar next to clean jar"},
 {"slug":"tissue-culture","n":18,"sec":4,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"workflow overview bench",
  "caption":"The whole pipeline on one bench: clean workspace, media jars, culture vessels and a donor plant. Stages 0 through a hardened mother follow this order.","alt":"Tissue culture workflow overview on lab bench"},


 # ---- coco & crop steering ----
 {"slug":"coco-crop-steering","n":1,"sec":2,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic close-up in a commercial cannabis grow: a rectangular open-top coco coir grow bag (a printed white coir grow bag, about one gallon) sitting on a bench with a healthy cannabis plant growing out of the open top; a flat white rectangular three-prong capacitance substrate sensor (thin polished steel needles, white body, thin black cable with a cylindrical ferrite bead) inserted into the coir at an angle; thin white 4mm drip-irrigation lines arch over the bag with drip stakes pushed into the coir surface; bright greenhouse lighting, sharp documentary detail. NOT a fabric pot, NOT a terracotta pot, NOT a handheld dial meter.",
  "caption":"A real root-zone capacitance probe and drip stakes in an open-top coir grow bag, the hardware behind reading and steering.","alt":"Capacitance sensor and drippers in a coir grow bag"},
 {"slug":"coco-crop-steering","n":2,"sec":4,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic close-up: white pressure-compensating drip-emitter stakes fed by thin 4mm lines releasing water onto the surface of a rectangular open-top coco coir grow bag (printed white coir bag, about one gallon) with a cannabis plant growing from the open top, glistening wet patch spreading across the coir, greenhouse grow setting, ultra sharp detail. NOT a fabric pot, NOT a terracotta pot.",
  "caption":"A timed irrigation shot wetting the coir in an open-top bag, small pulses refill the root zone in stages.","alt":"Drip irrigation onto a coir grow bag"},

 # ---- grow-room systems ----
 {"slug":"grow-room-systems","n":1,"sec":0,"model":CIN,"ar":"16:9","res":"2k",
  "prompt":"Epic cinematic wide shot of a pristine indoor cannabis grow room at peak flower, uniform canopy of healthy plants under powerful LED bar lights, visible airflow, clean white walls, atmospheric haze, symmetrical composition, photoreal, high-end facility",
  "caption":"The room as one system: light, climate, airflow and water balanced over a uniform canopy.","alt":"Pristine indoor grow room under LED"},
 {"slug":"grow-room-systems","n":2,"sec":4,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic: close-up of a digital climate sensor and controller unit mounted among cannabis plants in a grow room, reading temperature and humidity, LED light glow, condensation-free, crisp detail",
  "caption":"Climate sensing at canopy height, the inputs that drive the whole coupled system.","alt":"Climate sensor among plants"},

 # ---- airflow design ----
 {"slug":"airflow-design","n":1,"sec":6,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic: oscillating wall fans and clip fans positioned around a cannabis canopy, leaves gently fluttering in the breeze, motion in the foliage, indoor grow room under LED, dynamic, sharp",
  "caption":"Fans placed to move air through the canopy, every leaf should gently flutter.","alt":"Fans creating airflow over canopy"},
 {"slug":"airflow-design","n":2,"sec":2,"model":GPT,"ar":"16:9","res":"1k",
  "prompt":"Clean labelled scientific cross-section diagram of a single leaf showing the boundary layer of still air, arrows of moving air thinning it, CO2 entering and water vapour leaving, minimalist white background, crisp vector style with clear small labels",
  "caption":"The leaf boundary layer and how moving air thins it (labelled schematic).","alt":"Leaf boundary layer diagram"},

 # ---- mould risk ----
 {"slug":"mould-risk","n":1,"sec":3,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic macro: a dense cannabis flower bud with the early grey fuzzy rot of botrytis starting deep inside, a yellowing leaf pulling away, dramatic detail, slightly clinical documentary lighting, sharp focus on the affected cola",
  "caption":"Bud rot (Botrytis) starting inside a dense cola, caught early during scouting.","alt":"Botrytis bud rot close-up"},
 {"slug":"mould-risk","n":2,"sec":5,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic: a grower in nitrile gloves inspecting cannabis buds with a bright LED loupe light during late flower scouting, focused close inspection, grow room background softly blurred, documentary realism",
  "caption":"Daily scouting in late flower, five minutes with a light catches rot before it spreads.","alt":"Scouting buds for mould"},

 # ---- root zone TEROS-12 ----
 {"slug":"root-zone-teros12","n":1,"sec":0,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic product macro on a clean light-grey surface: a professional research-grade volumetric water content sensor, a flat white rectangular epoxy probe body about 9 cm long with three thin parallel polished stainless-steel needle prongs about 5 cm long extending from one end, and a thin black signal cable with a small black cylindrical ferrite choke bead near it; soft even studio lighting, crisp scientific product photography, ultra detailed. NOT a handheld dial meter, no round gauge, no screen.",
  "caption":"A research-grade capacitance probe: white body, three fine prongs, ferrite-beaded cable, not a cheap dial meter.","alt":"Capacitance root-zone sensor probe"},
 {"slug":"root-zone-teros12","n":2,"sec":2,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic close-up in a commercial cannabis grow: a research-grade capacitance substrate sensor (white-and-black rectangular body with thin polished steel prongs and a thin black cable with a cylindrical ferrite bead) inserted at an angle into an open-top one-gallon coco coir grow bag, thin white 4mm drip-irrigation lines arching over the bag with drip stakes, green cannabis stems and foliage rising above, a small irrigation controller unit with a screen on the floor in the foreground, bright even greenhouse lighting, documentary realism, sharp focus",
  "caption":"The real-world install: a capacitance probe seated in a coir grow bag, drip lines overhead, wired to a controller.","alt":"Capacitance sensor installed in a coir grow bag with drip lines"},

 # ---- smart watering VRWE ----
 {"slug":"smart-watering-vrwe","n":1,"sec":0,"model":GPT,"ar":"16:9","res":"1k",
  "prompt":"Clean modern infographic-style illustration: multiple sensor signals (moisture, EC, temperature, light) flowing as arrows into a glowing central 'brain' node that outputs a single watering decision, minimalist tech aesthetic, soft greens and greys, clear small labels",
  "caption":"Sensor fusion as a 'watering brain', many noisy signals into one confident decision.","alt":"Sensor fusion brain illustration"},

 # ---- signal & noise ----
 {"slug":"signal-and-noise","n":1,"sec":3,"model":GPT,"ar":"16:9","res":"1k",
  "prompt":"Clean data-visualization style image: a noisy jittery sensor time-series line with statistical control limit bands, one clear point breaking out past the band highlighted as a real 'signal', minimalist chart, white background, crisp labels",
  "caption":"Control limits separate real signal (the breakout point) from meaningless noise.","alt":"Control chart signal vs noise"},

 # ---- closed loop ----
 {"slug":"closed-loop","n":1,"sec":2,"model":GPT,"ar":"16:9","res":"1k",
  "prompt":"Clean labelled control-loop diagram: levers (light, climate, water) feeding a plant, sensors reading plant state, feedback arrow returning to a controller and back to the levers, circular flow, minimalist, white background, small clear labels",
  "caption":"The closed loop: act, measure plant state, compare, adjust, round and round.","alt":"Closed-loop control diagram"},

 # ---- plant-state dashboard ----
 {"slug":"plant-state-dashboard","n":1,"sec":0,"model":GPT,"ar":"16:9","res":"1k",
  "prompt":"Clean modern dashboard UI mockup on a dark screen showing plant-state indicators (transpiration, stress, growth mode) as clear gauges and a canopy diagram instead of raw numbers, professional product design, crisp legible labels",
  "caption":"A dashboard that shows plant state, not just raw sensor numbers.","alt":"Plant-state dashboard mockup"},

 # ---- f2 crop steering ----
 {"slug":"f2-crop-steering","n":1,"sec":3,"model":GPT,"ar":"16:9","res":"1k",
  "prompt":"Clean infographic board: the daily irrigation cycle split into four phases P0 P1 P2 P3 along a 24-hour timeline with a root-zone moisture curve rising and falling, minimalist, white background, clear labels",
  "caption":"The P0–P3 daily cycle as one board, dry, refill, maintain, dry.","alt":"P0-P3 daily cycle board"},

 # ---- irrigation manual ----
 {"slug":"irrigation-manual","n":1,"sec":2,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic: a tidy fertigation hardware setup, a pump, mixing tank, manifold and rows of drip lines feeding cannabis plants, clean tubing, professional installation, grow room, sharp technical detail",
  "caption":"A clean fertigation install, pump, tank, manifold and dripper lines.","alt":"Fertigation irrigation hardware"},

 # ---- cloning ----
 {"slug":"cloning","n":1,"sec":4,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic: fresh cannabis cuttings standing in rockwool cubes inside a clear humidity dome propagator, tiny white roots just emerging, water droplets on the dome, soft propagation lighting, macro detail",
  "caption":"Cuttings in rockwool under a humidity dome, the first white roots emerging.","alt":"Cannabis clones in humidity dome"},
 {"slug":"cloning","n":2,"sec":3,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic close-up: a freshly prepared cannabis cutting being dipped into a small pot of clear rooting gel, gloved hand holding the green stem, clean propagation bench with rockwool cubes and a humidity dome behind, soft propagation light, shallow depth of field, detailed",
  "caption":"Dipping a fresh cutting in rooting gel before it goes into a rockwool cube.","alt":"Cannabis cutting dipped in rooting gel"},

 # ---- nutrient mixing athena ----
 {"slug":"nutrient-mixing-athena","n":1,"sec":4,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic: a 50 litre plastic tank of nutrient solution being mixed with a paint-mixer paddle on a cordless drill creating a vortex, white mineral salt powder dissolving, hot water steam, clean grow-room utility area, sharp detail",
  "caption":"A full bag going into a 50 L tank, paddle on a drill, hot water, mixed to clear.","alt":"Mixing a nutrient stock tank with a drill paddle"},

 # ---- light acclimation ----
 {"slug":"light-acclimation","n":1,"sec":3,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic: a light meter / PAR sensor held over a healthy cannabis canopy under bright LED bar lights, reading on the meter, intense even lighting, grow room, crisp detail",
  "caption":"Measuring PPFD at the canopy, you ramp light to a number, not by eye.","alt":"PAR meter over canopy"},
 {"slug":"light-acclimation","n":2,"sec":2,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic macro: cannabis fan leaves showing light bleaching, pale white-yellow tips on the topmost leaves closest to the lamp while lower leaves stay deep green, documentary clarity, sharp",
  "caption":"Light bleaching: pale tops nearest the lamp when intensity outran the plant's capacity.","alt":"Light-bleached cannabis tops"},

 # ---- defoliation & training ----
 {"slug":"defoliation-training","n":1,"sec":3,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic top-down: a cannabis plant trained flat across a horizontal trellis net (SCROG), even canopy of shoot tips poking through the squares, lush green, grow-room lighting, sharp detail",
  "caption":"A SCROG net spreads the canopy flat so every site gets equal light.","alt":"SCROG trellis canopy from above"},
 {"slug":"defoliation-training","n":2,"sec":4,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic: a defoliated and lollipopped cannabis plant in early flower, lower growth stripped to bare stem, open airy structure with clear bud sites up top, clean grow room, documentary realism",
  "caption":"Lollipopped and defoliated, energy and airflow pushed to the productive top sites.","alt":"Lollipopped cannabis plant"},

 # ---- IPM SOP ----
 {"slug":"ipm-sop","n":1,"sec":4,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic: a yellow sticky trap among cannabis plants with a few fungus gnats stuck to it, and a grower's hand placing it, scouting context, grow room, sharp macro detail",
  "caption":"A yellow sticky card, cheap early-warning scouting that turns hunches into counts.","alt":"Yellow sticky pest trap in canopy"},
 {"slug":"ipm-sop","n":2,"sec":2,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic macro: a sachet of predatory mites being sprinkled onto a cannabis leaf as biological control, tiny beneficial insects visible, soft natural light, documentary detail",
  "caption":"Releasing predatory mites, biocontrol that lives in the canopy and hunts pests.","alt":"Releasing predatory mites"},

 # ---- harvest / dry / trim / cure ----
 {"slug":"harvest-dry-trim-cure","n":1,"sec":1,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic extreme macro: cannabis trichomes on a flower at harvest maturity, milky-cloudy heads with a few amber, viewed through a jeweller's loupe clarity, glistening resin, ultra sharp, scientific",
  "caption":"Trichomes at harvest: mostly cloudy with a touch of amber, the maturity signal.","alt":"Cannabis trichomes macro"},
 {"slug":"harvest-dry-trim-cure","n":2,"sec":4,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic: whole cannabis branches hung upside down in a clean climate-controlled drying room, even spacing, soft low light, hygrometer on the wall, documentary facility photography",
  "caption":"A controlled dry: branches hung in a cool, dark, airflowed room near 60% humidity.","alt":"Cannabis drying room"},
 {"slug":"harvest-dry-trim-cure","n":3,"sec":6,"model":NB,"ar":"16:9","res":"2k",
  "prompt":"Photorealistic: cured cannabis flower in clear glass mason jars with a small hygrometer inside reading about 60 percent, being burped, clean shelf, warm soft light, premium detail",
  "caption":"Curing in sealed glass with a hygrometer, burping to hold the right water activity.","alt":"Curing cannabis in glass jars"},

 # ---- GMP hash lab ----
 {"slug":"gmp-hash-lab","n":1,"sec":0,"model":CIN,"ar":"16:9","res":"2k",
  "prompt":"Epic cinematic: a gowned technician in full cleanroom suit and gloves working stainless-steel solventless hash-wash equipment in a spotless GMP cleanroom, dramatic clean lighting, reflective surfaces, premium pharmaceutical facility, photoreal",
  "caption":"GMP processing: gowning and stainless steel in a controlled cleanroom.","alt":"Technician in GMP hash cleanroom"},
 {"slug":"gmp-hash-lab","n":2,"sec":3,"model":GPT,"ar":"16:9","res":"1k",
  "prompt":"Clean labelled facility floor-plan diagram showing cleanroom zoning by grade, one-directional material and personnel flow arrows, airlocks and gowning rooms, minimalist top-down schematic, white background, clear small labels",
  "caption":"Zoned material and personnel flow, clean shells nested by cleanroom grade.","alt":"GMP facility zoning diagram"},

 # ---- facility 3D ----
 {"slug":"facility-3d","n":1,"sec":0,"model":GPT,"ar":"16:9","res":"1k",
  "prompt":"Clean 3D architectural render: a top-down/isometric model of a cannabis grow facility floor plan with labelled rooms (veg, flower, dry, trim), equipment blocks and airflow, modern CAD visualization style, crisp labels",
  "caption":"Modelling the facility in 3D catches clashes before construction starts.","alt":"3D facility floor-plan render"},

 # ---- fact-check educational pack (2026-07) ----
 {"slug":"seeds-germination","n":1,"sec":5,"model":FC,"ext":"jpg","ar":"16:9","res":"2k",
  "prompt":"(factcheck) seedling roots drink under humidity dome in rockwool+coco",
  "caption":"Roots still take the water. A humidity dome cuts evaporative demand — it does not mean the seedling drinks through its leaves.","alt":"Seedling in rockwool and coco under humidity dome"},
 {"slug":"harvest-dry-trim-cure","n":4,"sec":4,"model":FC,"ext":"jpg","ar":"16:9","res":"2k",
  "prompt":"(factcheck) water activity meter and moisture meter on dried flower",
  "caption":"Same bulk moisture reading can span dry-to-mouldy water activity. Steer post-harvest with aw (here ~0.61) not a cheap moisture % alone.","alt":"Water activity and moisture meters with dried buds"},
 {"slug":"mould-risk","n":3,"sec":2,"model":FC,"ext":"jpg","ar":"16:9","res":"2k",
  "prompt":"(factcheck) cola room RH vs inside microclimate",
  "caption":"Room air can read safe while the dense cola interior stays wetter — where bud rot starts.","alt":"Cannabis cola exterior vs humid interior cutaway"},
 {"slug":"mould-risk","n":4,"sec":3,"model":FC,"ext":"jpg","ar":"16:9","res":"2k",
  "prompt":"(factcheck) late flower aisle climate meter",
  "caption":"Measure in the aisle and at canopy height. Late flower often targets roughly 45–55% RH with strong through-canopy air.","alt":"Thermo-hygrometer in late flower room"},
 {"slug":"under-canopy-lighting","n":1,"sec":2,"model":FC,"ext":"jpg","ar":"16:9","res":"2k",
  "prompt":"(factcheck) canopy spectrum filter green FR enriched",
  "caption":"Under the canopy, blue and red are depleted; green and far-red are relatively enriched — not a “red-rich” understory.","alt":"Above vs under canopy LED spectrum comparison"},
 {"slug":"scaling-high-light","n":1,"sec":1,"model":CD,"ext":"svg","ar":"16:9","res":"1k",
  "prompt":"(factcheck) leaf vs canopy light curves",
  "caption":"Leaf photosynthesis can plateau while whole-canopy flower yield still rises with light — ambient CO₂ is not a hard 800 µmol wall.","alt":"Leaf Anet vs canopy yield vs PPFD graphs"},
 {"slug":"lighting-fundamentals","n":1,"sec":3,"model":CD,"ext":"svg","ar":"16:9","res":"1k",
  "prompt":"(factcheck) leaf vs canopy light curves",
  "caption":"Intensity targets are canopy-scale. A single leaf gas-exchange curve is not the whole room’s yield ceiling.","alt":"Leaf vs canopy light response graphs"},
 {"slug":"coco-crop-steering","n":3,"sec":3,"model":CD,"ext":"svg","ar":"16:9","res":"1k",
  "prompt":"(factcheck) Caplan one drought vs daily drybacks",
  "caption":"A single carefully timed late drought is not the same experiment as daily generative dryback sawteeth.","alt":"Single drought vs daily dryback VWC traces"},
 {"slug":"coco-crop-steering","n":4,"sec":2,"model":CD,"ext":"svg","ar":"16:9","res":"1k",
  "prompt":"(factcheck) dryback percentage points",
  "caption":"Dryback is percentage points (peak minus trough), not “percent of peak” unless you say so.","alt":"Dryback points vs percent of peak"},
 {"slug":"rockwool-crop-steering","n":1,"sec":2,"model":CD,"ext":"svg","ar":"16:9","res":"1k",
  "prompt":"(factcheck) Caplan one drought vs daily drybacks",
  "caption":"Daily drybacks are a related idea to controlled deficit — not a copy of one late-flower drought trial.","alt":"Single drought vs daily dryback comparison"},
 {"slug":"one-steering-law","n":1,"sec":2,"model":CD,"ext":"svg","ar":"16:9","res":"1k",
  "prompt":"(factcheck) dryback percentage points",
  "caption":"Count dryback in percentage points: 78% down to 58% is 20 points.","alt":"Dryback points explanation gauge"},
 {"slug":"one-steering-law","n":2,"sec":4,"model":CD,"ext":"svg","ar":"16:9","res":"1k",
  "prompt":"(factcheck) Caplan vs daily drybacks",
  "caption":"One multi-day late drought ≠ multi-week daily steering pulses.","alt":"Drought study vs daily drybacks"},
 {"slug":"irrigation-manual","n":2,"sec":2,"model":CD,"ext":"svg","ar":"16:9","res":"1k",
  "prompt":"(factcheck) veg vs gen dryback phases",
  "caption":"Vegetative: smaller drybacks, stay wetter. Generative: larger controlled drybacks. Example VWC vs crop day.","alt":"Veg vs generative dryback VWC chart"},
 {"slug":"f2-crop-steering","n":2,"sec":2,"model":CD,"ext":"svg","ar":"16:9","res":"1k",
  "prompt":"(factcheck) veg vs gen dryback phases",
  "caption":"Phase polarity for autonomous steering: veg smaller drybacks, generative larger controlled drybacks.","alt":"Crop phase VWC dryback chart"},
 {"slug":"water-quality","n":1,"sec":3,"model":CD,"ext":"svg","ar":"16:9","res":"1k",
  "prompt":"(factcheck) DO saturation vs temperature",
  "caption":"Air-saturated DO is roughly ~9 mg/L at 20 °C and ~8 mg/L at 26 °C — not 5–6 / 3–4 ppm. Still chill and aerate for roots.","alt":"Dissolved oxygen saturation curve"},
 {"slug":"pppe","n":1,"sec":2,"model":CD,"ext":"svg","ar":"16:9","res":"1k",
  "prompt":"(factcheck) clean dirty two kit flow",
  "caption":"Two kits: cultivation gowning and a separate post-harvest gown-in. Flower coveralls do not walk into dry/trim.","alt":"Facility two-track gowning flow"},
 {"slug":"pppe","n":2,"sec":4,"model":CD,"ext":"svg","ar":"16:9","res":"1k",
  "prompt":"(factcheck) log reduction table",
  "caption":"Log reduction: 1 log ≈ 90%, 2 log ≈ 99%, 3 log ≈ 99.9%. Mapping 3 log to 83% is wrong.","alt":"Hand hygiene log reduction table"},

]

# Dropped AI diagram images (image-gen mangles labels; papers already have real SVG diagrams).
_SKIP = {("airflow-design", 2), ("smart-watering-vrwe", 1), ("signal-and-noise", 1),
         ("closed-loop", 1), ("plant-state-dashboard", 1), ("f2-crop-steering", 1),
         ("gmp-hash-lab", 2), ("facility-3d", 1)}
IMAGES = [im for im in IMAGES if (im["slug"], im["n"]) not in _SKIP]

GK = "grok_imagine"
IMAGES += [
 # ---- hash rosin pressing (photoreal; sec = 0-based section index) ----
 {"slug":"hash-rosin-pressing","n":1,"sec":0,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"macro frosty trichome-covered bud",
  "caption":"The raw material: every frosty &lsquo;crystal&rsquo; is a trichome — a stalk holding a resin head. All of solventless is collecting these heads and squeezing them.","alt":"Macro of cannabis bud covered in trichomes"},
 {"slug":"hash-rosin-pressing","n":2,"sec":1,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"rosin flowing from press onto parchment",
  "caption":"The whole process in one frame: heated plates, folded parchment, and golden rosin flowing — heat to melt, pressure to move, mesh to clean.","alt":"Golden rosin flowing from a press onto parchment"},
 {"slug":"hash-rosin-pressing","n":3,"sec":2,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"finished rosin jar and dab rig",
  "caption":"Where the pipeline ends: a stable, finished concentrate and the rig that vaporises it. Everything upstream protects what's in this jar.","alt":"Jar of rosin next to a dab rig"},
 {"slug":"hash-rosin-pressing","n":4,"sec":3,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"micron bags loaded with hash",
  "caption":"Loading the micron bag: 2–7 g of hash in a fine nylon mesh, folded twice, over fresh parchment. The mesh size is the purity gate.","alt":"Filling micron press bags with bubble hash"},
 {"slug":"hash-rosin-pressing","n":5,"sec":10,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"ice water hash washing vessel",
  "caption":"The wash: near-freezing water, gentle agitation, and a stack of mesh bags below. Cold keeps the heads brittle so they snap off intact.","alt":"Ice-water hash washing vessel with paddle and bags"},
 {"slug":"hash-rosin-pressing","n":6,"sec":10,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"microplaned hash on freeze dryer trays",
  "caption":"Drying done right: microplaned hash spread thin on trays for the freeze-dryer — water leaves under vacuum, terpenes stay.","alt":"Microplaned bubble hash on freeze dryer trays"},
 {"slug":"hash-rosin-pressing","n":7,"sec":11,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"press plates with PID controller",
  "caption":"The hardware that matters: even plates and a PID holding the setpoint. Cheap plates swing and scorch; accuracy is what buys low-temp pressing.","alt":"Rosin press plates with PID temperature controller"},
 {"slug":"hash-rosin-pressing","n":8,"sec":12,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"trichome heads under magnification",
  "caption":"Read the material: under magnification you can see head size and how many are intact — that read picks your micron and your temperature.","alt":"Loose trichome heads under magnification"},
 {"slug":"hash-rosin-pressing","n":9,"sec":13,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"cold-cure badder jar",
  "caption":"Cold-cure badder: days to weeks sealed at 10–21 °C sets this creamy texture while the volatile terpenes stay in the jar.","alt":"Jar of whipped cold-cure rosin badder"},
 {"slug":"hash-rosin-pressing","n":10,"sec":13,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"THCa diamonds in terp sauce",
  "caption":"Diamonds and sauce: THCa crystallised out of solution, sitting in the terpene fraction. Only undecarbed THCa will ever do this.","alt":"THCa diamond crystals in golden terpene sauce"},
]

IMAGES += [
 # ---- ripening & harvest timing ----
 {"slug":"ripening-harvest-timing","n":1,"sec":3,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"mixed-maturity trichomes macro",
  "caption":"A mixed trichome population on the calyx: cloudy dominant, first amber creeping in — the flower window opening.","alt":"Macro photo of cannabis trichomes showing clear, cloudy and amber resin heads together"},
 {"slug":"ripening-harvest-timing","n":2,"sec":4,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"loupe scoping marked cola",
  "caption":"The read: 30–60x on a marked mid-cola spot, in white light, every two days.","alt":"Grower inspecting a cannabis bud with a jeweller's loupe at a marked scoping spot"},
 {"slug":"ripening-harvest-timing","n":3,"sec":7,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"late-flower fade with hygrometer",
  "caption":"The last fortnight: the fade underway, dense colas, and the hygrometer that decides whether waiting stays affordable.","alt":"Ripening cannabis room with fading leaves and a hygrometer showing humidity control"},
 {"slug":"ripening-harvest-timing","n":4,"sec":9,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"whole plants hung in dry room",
  "caption":"Chop day done right: whole plants spaced on the line in a verified 15–16 °C / 60% RH dry room, tags on every stem.","alt":"Whole cannabis plants hung with spacing in a dark drying room"},
 # ---- transplanting ----
 {"slug":"transplanting","n":1,"sec":4,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"root-bound ball slide-out test",
  "caption":"The slide-out test showing a root-bound ball: the circling mat means this move is already late.","alt":"Root-bound cannabis root ball with circling roots being removed from a black pot"},
 {"slug":"transplanting","n":2,"sec":5,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"container size ladder lineup",
  "caption":"The container ladder in the flesh: each step roughly two to four times the volume of the last.","alt":"Row of increasingly larger pots with cannabis plants at progressive growth stages"},
 {"slug":"transplanting","n":3,"sec":7,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"lowering root ball into coco",
  "caption":"De-pot by the ball, never the stem: fingers splayed across the media, ball supported the whole way down.","alt":"Gloved hands transplanting a cannabis root ball into a larger container of coco"},
 {"slug":"transplanting","n":4,"sec":8,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"block seated onto rockwool slab",
  "caption":"Block onto slab: full base contact first, then hold irrigation so roots dive down and root-in.","alt":"Rockwool block with young plant being placed onto a wrapped slab in a greenhouse"},
 # ---- veg management ----
 {"slug":"veg-management","n":1,"sec":3,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"veg room rows under LED",
  "caption":"A veg room mid-build: the canopy share each plant must fill is the whole schedule.","alt":"Rows of vegetative cannabis plants on benches under LED lighting in an indoor grow room"},
 {"slug":"veg-management","n":2,"sec":6,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"topped plant two leaders macro",
  "caption":"Two even leaders a week after the cut — recovery time that was planned, not discovered.","alt":"Close-up of a topped cannabis plant with two new leader shoots growing from the top node"},
 {"slug":"veg-management","n":3,"sec":7,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"trellis net over level canopy",
  "caption":"Net on while the plants are short: the trellis receives the stretch instead of rescuing it.","alt":"Trellis netting installed over a level cannabis canopy in vegetative growth"},
 {"slug":"veg-management","n":4,"sec":10,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"white roots at pot walls",
  "caption":"The pre-flip report card: white roots at the walls and a predictable overnight dryback.","alt":"Healthy white cannabis roots covering the outside of a coco coir root ball"},
 # ---- mother plants ----
 {"slug":"mother-plants","n":1,"sec":0,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"mother room wide shot",
  "caption":"A production mother room: flat-topped stock plants on benches, every plant labelled, every tool stationed.","alt":"Indoor cannabis mother room with rows of flat-topped stock plants on rolling benches"},
 {"slug":"mother-plants","n":2,"sec":5,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"pruned mother scaffold frame",
  "caption":"The frame in the flesh: woody scaffolds below, a level hedge of harvestable shoots above.","alt":"Pruned cannabis mother plant with woody scaffold frame and flat top of upright shoots"},
 {"slug":"mother-plants","n":3,"sec":9,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"snips in bleach between plants",
  "caption":"The whole HpLVd defence in one frame: sanitise or swap the blade between plants, every time.","alt":"Gloved hands sanitising pruning snips in bleach solution next to a cannabis mother plant"},
 {"slug":"mother-plants","n":4,"sec":11,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"clone tray beside mother succession",
  "caption":"Succession in progress: the tested candidate builds out while the incumbent still serves.","alt":"Tray of rooted cannabis clones beside a large mother plant during succession"},
 # ---- genetics & pheno hunting ----
 {"slug":"genetics-phenohunting","n":1,"sec":6,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"tagged pheno-hunt cohort in veg",
  "caption":"A hunt cohort in veg: one batch, identical pots and feed, and a permanent ID on every plant before anyone has a favourite.","alt":"Rows of tagged young cannabis plants in identical pots under LED light"},
 {"slug":"genetics-phenohunting","n":2,"sec":7,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"two colas side-by-side scoring",
  "caption":"Selection is comparison against a written rubric — structure, density and finish judged side by side, not from memory.","alt":"Two labelled cannabis colas compared side by side next to a scoring sheet"},
 {"slug":"genetics-phenohunting","n":3,"sec":9,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"two mothers plus backup cuttings",
  "caption":"Redundancy in practice: two labelled mothers and a tray of rooted backups — what keeping a cut actually looks like.","alt":"Two labelled cannabis mother plants with a tray of rooted cuttings in front"},
 {"slug":"genetics-phenohunting","n":4,"sec":11,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"pollen collection vials",
  "caption":"Pollen collection: caught over paper, dried, sieved and stored cold in labelled vials — and treated as a containment problem the whole time.","alt":"Cannabis pollen being collected on paper next to a sieve and labelled vials"},
 # ---- temp, humidity & VPD ----
 {"slug":"temp-humidity-vpd","n":1,"sec":0,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"canopy-height aspirated sensor",
  "caption":"The number that matters is measured here — at canopy height, in the air the plants actually occupy.","alt":"Indoor cannabis canopy under LED light with a climate sensor hanging at canopy height"},
 {"slug":"temp-humidity-vpd","n":2,"sec":9,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"night condensation on duct",
  "caption":"Lights-off, no dehumidification: the room cooled toward its dew point and the coldest surfaces crossed it first.","alt":"Condensation droplets on a metal duct and wall inside a dark grow room at night"},
 {"slug":"temp-humidity-vpd","n":3,"sec":10,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"IR thermometer on leaf",
  "caption":"The cheapest VPD upgrade there is: a real leaf temperature instead of an assumption.","alt":"Infrared thermometer measuring leaf surface temperature of a cannabis leaf"},
 {"slug":"temp-humidity-vpd","n":4,"sec":11,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"dehumidifier in grow aisle",
  "caption":"Transpiration returns almost every irrigated litre to the room air — the dehumidifier is sized against the watering schedule, not the room volume.","alt":"Dehumidifier with drain hose running between rows of cannabis plants in a grow room"},
 # ---- lab testing & COAs ----
 {"slug":"lab-testing-coas","n":1,"sec":3,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"COA beside labelled jars",
  "caption":"The certificate meets the batch: the release paperwork travels with the jars it claims to describe.","alt":"Gloved hands holding a printed lab certificate next to labelled jars of dried cannabis flower"},
 {"slug":"lab-testing-coas","n":2,"sec":5,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"HPLC autosampler loading",
  "caption":"Potency on an HPLC: the extract runs cool, so the acid and neutral cannabinoids reach the detector as separate peaks.","alt":"Lab technician loading amber vials into an HPLC autosampler with a chromatogram on screen"},
 {"slug":"lab-testing-coas","n":3,"sec":7,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"increment sampling into jar",
  "caption":"Increments, not a grab: a defensible batch sample is pulled from many containers and positions, then documented.","alt":"Gloved hands combining flower increments from multiple bags into one labelled sample jar"},
 {"slug":"lab-testing-coas","n":4,"sec":8,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"petri plate vs qPCR",
  "caption":"Two ways to ask the microbial question: colonies that grow on a plate versus DNA copies counted by qPCR — the same batch can pass one and fail the other.","alt":"Petri dish with mould colonies in front of a qPCR instrument showing amplification curves"},
 # ---- unit economics ----
 {"slug":"unit-economics","n":1,"sec":5,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"HPS vs LED split frame",
  "caption":"Same crop, two fixture generations — the watts changed underneath the metric.","alt":"Side-by-side view of a cannabis flowering room under orange HPS lighting and another under white-magenta LED lighting"},
 {"slug":"unit-economics","n":2,"sec":8,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"trim room hand labour",
  "caption":"The biggest cost line in the stack works with scissors, not electrons.","alt":"Workers hand-trimming dried cannabis flower at stainless steel benches in a clean trim room"},
 {"slug":"unit-economics","n":3,"sec":9,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"empty room mid-turnaround",
  "caption":"Turn time: the days the room earns nothing, multiplied by every cycle.","alt":"Cleaned empty cannabis grow room with bare benches during reset between crops"},
 {"slug":"unit-economics","n":4,"sec":7,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"harvest weigh-in spreadsheet",
  "caption":"The scoreboard is a division: every dollar of the year over every gram across this scale.","alt":"Dried cannabis flower being weighed on a scale beside a clipboard, calculator and spreadsheet"},
 # ---- compliance & track-trace ----
 {"slug":"compliance-track-trace","n":1,"sec":3,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"operator reading licence clipboard",
  "caption":"The licence is a working document, not a wall trophy: activities, conditions and renewal dates that the whole crew should know.","alt":"Grower reading a printed licence document on a clipboard in a facility corridor"},
 {"slug":"compliance-track-trace","n":2,"sec":6,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"barcode tag on plant stem",
  "caption":"Identity is physical: the tag on the plant is the bridge between the thing in the room and its record in the ledger.","alt":"Gloved hands fixing a barcode plant tag to a cannabis plant stem"},
 {"slug":"compliance-track-trace","n":3,"sec":8,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"logbook entry at bench",
  "caption":"Contemporaneous means at the bench, at the time: the record is made where the work happens, not reconstructed later.","alt":"Gloved hand writing in a bound logbook on a stainless bench beside an EC meter"},
 {"slug":"compliance-track-trace","n":4,"sec":11,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"witnessed waste weigh-out",
  "caption":"Destruction is an event with weights and witnesses: waste stays inside the custody chain until the record closes it out.","alt":"Two workers weighing a sealed waste bag on a floor scale while one signs a form"},
 # ---- HVAC & dehumidification ----
 {"slug":"hvac-dehumidification","n":1,"sec":0,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"rooftop climate plant",
  "caption":"The other half of the machine: the climate plant that hauls every watt and every litre back out of the room.","alt":"Rooftop packaged HVAC units and insulated ducting serving an indoor cultivation building"},
 {"slug":"hvac-dehumidification","n":2,"sec":4,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"ceiling dehu over canopy",
  "caption":"Water in equals water to remove: the dehumidifier is the return path for the irrigation schedule.","alt":"Ceiling-mounted dehumidifier with plumbed condensate drain above a flowering cannabis canopy"},
 {"slug":"hvac-dehumidification","n":3,"sec":8,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"lights-off condensation spike",
  "caption":"The lights-off spike: same grams of water, colder air — the room walks toward the mould window every night.","alt":"Dark grow room at lights-off with condensation forming on a cold duct above dense flowers"},
 {"slug":"hvac-dehumidification","n":4,"sec":11,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"N+1 dehu bank",
  "caption":"N+1 in the flesh: two units carry the night, the third exists so a Saturday-night failure stays boring.","alt":"Three identical dehumidifier units installed in parallel with shared drain manifold"},
 # ---- cannabinoids & terpenes ----
 {"slug":"cannabinoids-terpenes","n":1,"sec":2,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"bract trichomes extreme macro",
  "caption":"Capitate-stalked trichomes at macro scale — every head is a sealed sac of cannabinoid acids and terpenes.","alt":"Macro photo of clear stalked trichomes covering a cannabis bract"},
 {"slug":"cannabinoids-terpenes","n":2,"sec":7,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"dark cool drying room",
  "caption":"Cold, slow and dark: drying is vapour-pressure management — the monoterpenes leave a warm room first.","alt":"Dark cool drying room with cannabis plants hanging on lines"},
 {"slug":"cannabinoids-terpenes","n":3,"sec":10,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"amber jars dark storage",
  "caption":"Dark, cool, sealed, dated — the entire storage playbook against light and oxygen.","alt":"Amber jars of cannabis flower stored in a dark cabinet"},
 {"slug":"cannabinoids-terpenes","n":4,"sec":12,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"HPLC vials and COA",
  "caption":"The COA is the receipt: acid and neutral forms, terpene panel, and the storage history hiding in the ratios.","alt":"Lab bench with HPLC vials and a certificate of analysis"},
 # ---- energy & sustainability ----
 {"slug":"energy-sustainability","n":1,"sec":5,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"HPS-to-LED retrofit aisle",
  "caption":"The retrofit in progress: HPS rows against new LED bars delivering the same photons at ~40% less power — and less heat for the HVAC to remove.","alt":"Cannabis flower room with HPS fixtures on one side and LED bars on the other during a lighting retrofit"},
 {"slug":"energy-sustainability","n":2,"sec":7,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"staged plant room units",
  "caption":"Staged climate plant: multiple smaller units tracking the room's swinging load beat one oversized unit short-cycling — and hot-gas reheat replaces resistance coils.","alt":"Plant room with two staged HVAC dehumidification units and condensate drain lines"},
 {"slug":"energy-sustainability","n":3,"sec":9,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"condensate reclaim corner",
  "caption":"Condensate reclaim: near-distilled water off the dehu coil passes a filter and UV stage before re-mineralisation — paid-for water going back to work instead of down the drain.","alt":"Dehumidifier condensate line feeding a collection tank through a filter and UV steriliser"},
 {"slug":"energy-sustainability","n":4,"sec":12,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"CT clamps submetering panel",
  "caption":"Submetering in practice: CT clamps per end-use turn one monthly utility number into per-room, per-system signals — the meter finds faults before the crop shows them.","alt":"Open electrical panel with CT clamps and an energy submeter beside a dashboard tablet"},
 # ---- plant biology ----
 {"slug":"plant-biology","n":1,"sec":4,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"bract and stigmas macro",
  "caption":"Bracts and paired stigmas on a live flower — the single-flower unit from the diagram, in the flesh.","alt":"Macro photo of cannabis bracts with white stigmas"},
 {"slug":"plant-biology","n":2,"sec":5,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"trichomes photomicrograph",
  "caption":"Capitate-stalked trichomes under magnification — clear, milky and amber heads on their stalks.","alt":"Microscope view of stalked cannabis trichomes"},
 {"slug":"plant-biology","n":3,"sec":9,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"female pre-flower at node",
  "caption":"A female pre-flower at the node — the loupe check from the sexing diagram on a real plant.","alt":"Female cannabis pre-flower with white stigmas at a stem node"},
 {"slug":"plant-biology","n":4,"sec":12,"model":GK,"ar":"16:9","res":"2k",
  "prompt":"healthy white root ball",
  "caption":"What healthy looks like below ground: bright white, densely branching roots at transplant.","alt":"Healthy white cannabis roots around coco coir substrate"},
]

def by_slug():
    d = {}
    for im in IMAGES:
        d.setdefault(im["slug"], []).append(im)
    return d
