# -*- coding: utf-8 -*-
"""Auto-interlinking: concept phrase -> paper slug. The build links the first mention
of each concept in body prose to the matching paper (never self, never in headings/code/
existing links). Curated to distinctive multi-word phrases to avoid noise/mis-links."""

# slug -> phrases that should link to it (case-insensitive, whole-word)
LINK_PHRASES = {
    "auckland-ipm-blueprint": ["Auckland medicinal IPM", "medicinal-cannabis input gate", "approved-input register", "rice root aphid", "Septoria leaf spot"],
    "tissue-culture": ["tissue culture", "micropropagation", "meristem culture", "meristem", "hop latent viroid", "HpLVd", "clean stock",
                       "explant preparation", "subculture cycle", "totipotency", "hyperhydricity disorder", "PGR ratio", "cytokinin",
                       "endophyte contamination", "in vitro propagation", "aseptic technique", "disease indexing"],
    "cannabis-tissue-culture-playbook": ["tissue culture playbook", "cannabis tissue culture, start to finish", "start-to-finish cannabis tissue culture"],
    "cannabis-tissue-culture-sop": ["tissue culture SOP", "AliExpress laminar", "laminar-flow hood from China", "F-01", "F-12", "aseptic procedure"],
    "coco-crop-steering": ["crop steering", "coco coir", "dryback", "field capacity", "generative steering", "vegetative steering",
                           "substrate EC", "EC ratio", "generative mode", "vegetative mode", "morning dryback"],
    "deep-water-culture": ["deep water culture", "DWC", "RDWC", "recirculating deep water culture", "water culture", "dissolved oxygen",
                           "oxidation-reduction potential", "nanobubble", "nanobubbles", "air stone", "control bucket",
                           "Pythium root rot", "DWC reservoir"],
    "rockwool-crop-steering": ["rockwool crop steering", "recovery floor", "stone wool", "preferential flow", "channeling",
                               "dryback percentage", "WC%", "rockwool block saturation", "rockwool block"],
    "slab-irrigation-strategy": ["slab irrigation", "block-on-slab", "rooting-in", "block on slab", "drain slits", "matric suction"],
    "one-steering-law": ["one steering law", "the steering law", "steering law"],
    "under-canopy-lighting": ["under-canopy lighting", "subcanopy lighting", "inter-canopy lighting", "intracanopy lighting", "photobleaching", "SCL", "ICL"],
    "grow-room-systems": ["grow room as one", "coupled system", "daily light integral", "DLI",
                          "limiting factor", "Liebig's law", "lever and setpoint"],
    "airflow-design": ["airflow design", "boundary layer", "air velocity", "leaf boundary",
                       "horizontal airflow fan", "vertical airflow fan", "HAF fan", "VAF fan",
                       "under-canopy fan", "oscillating wall fan", "air sock", "perforated poly tube",
                       "destratification fan", "racetrack loop", "fan placement"],
    "co2-enrichment": ["CO2 enrichment", "CO2 supplementation", "carbon dioxide enrichment", "CO2 injection",
                       "dark respiration", "CO2 compensation point", "photorespiration", "sealed grow room"],
    "mould-risk": ["bud rot", "botrytis", "powdery mildew", "mould risk", "water activity",
                   "Pythium infection", "grey mould", "Aw value"],
    "root-zone-teros12": ["root-zone sensor", "capacitance sensor", "capacitance probe", "volumetric water content",
                          "pore-water EC", "permittivity", "TEROS-12", "TEROS 12",
                          "VWC", "bulk EC measurement", "Hilhorst model", "SDI-12 protocol",
                          "substrate-specific calibration", "volume of influence", "dielectric soil sensor",
                          "TEROS sensor", "safe headroom estimate"],
    "smart-watering-vrwe": ["smart watering", "sensor fusion", "VRWE", "watering brain",
                            "water balance tracking", "background drip baseline", "transpiration proxy",
                            "virtual root-zone estimator", "safe headroom"],
    "signal-and-noise": ["signal and noise", "control limits", "statistical process control", "sensor noise",
                         "signal-to-noise ratio", "SNR", "aliasing artifact", "Nyquist rule",
                         "moving average filter", "EWMA filter", "median filter",
                         "common-cause variation", "special-cause variation", "sensor drift",
                         "coefficient of variation", "tampering effect"],
    "closed-loop": ["closed loop", "closed-loop control", "feedback loop", "setpoint",
                    "dead-band", "hunting oscillation", "C1D1", "closed-loop extraction"],
    "plant-state-dashboard": ["plant-state dashboard", "plant state", "telemetry",
                              "calm dashboard", "named condition", "inference layer",
                              "leading indicator", "lagging indicator", "plant stress level"],
    "f2-crop-steering": ["P0–P3", "P0-P3", "irrigation phases", "daily irrigation cycle",
                         "P0 dryback", "pH/EC gate", "blocked dripper", "fail-safe irrigation"],
    "irrigation-manual": ["irrigation system", "fertigation", "drip emitters", "drip lines",
                          "solenoid valve", "runoff collection", "dripper line"],
    "cloning": ["taking cuttings", "rooting hormone", "humidity dome", "clone", "cutting",
                "auxin", "IBA", "air embolism", "hardening off", "culling clones", "rockwool clone cube"],
    "nutrient-mixing-athena": ["stock tank", "stock solution", "Athena Pro Line", "nutrient mixing", "pore-water", "electrical conductivity",
                               "two-part nutrient", "mineral salt nutrient", "nutrient precipitate", "grams per litre"],
    "light-acclimation": ["light acclimation", "photoinhibition", "light bleaching", "PPFD ramp", "PPFD",
                          "reactive oxygen species", "chloroplast density", "acclimation period"],
    "defoliation-training": ["defoliation", "plant training", "lollipopping", "low-stress training", "SCROG", "trellis",
                             "fan leaves", "topping", "FIM technique", "apical dominance", "larf removal",
                             "LST"],
    "ipm-sop": ["integrated pest management", "IPM", "scouting", "biological control", "action threshold",
                "foliar spray", "drench application", "REI interval", "withholding period",
                "preventative biocontrol", "parasitoid wasp", "Bti application", "Btk application",
                "entomopathogenic nematodes", "sticky trap monitoring", "tank mix"],
    "harvest-dry-trim-cure": ["harvest", "drying", "curing", "trimming", "trichome",
                              "post-harvest processing", "moisture content", "wet weight",
                              "dry-to-wet ratio", "bucking", "wet trim", "dry trim",
                              "stem-snap test", "ASTM D8197", "sugar leaves", "burping jars"],
    "gmp-hash-lab": ["GMP", "cleanroom", "good manufacturing practice", "hash lab",
                     "cleanroom grade", "ISO 14644", "pressure cascade", "MACO",
                     "DQ/IQ/OQ/PQ", "PIC/S", "ICH Q9", "environmental monitoring",
                     "validation protocol", "quality management system", "QRM"],
    "hash-rosin-pressing": ["hash rosin", "rosin press", "bubble hash", "dry sift", "live rosin",
                            "solventless", "full-melt", "micron bag", "cold cure", "THCa diamonds", "rosin pressing"],
    "facility-3d": ["3D model", "facility design", "floor plan",
                    "digital twin", "Three.js", "glTF model", "PTZ camera", "FOV cone", "draw call count"],
    "daily-checks": ["daily checks", "daily check", "pause point", "killer item", "pencil-whipping",
                     "action limit", "self-completing",
                     "read-do checklist", "do-confirm checklist", "implementation intention", "auto-tick check"],
    "seeds-germination": ["germination", "seedling", "feminised seeds", "autoflower", "popping seeds",
                          "taproot emergence", "cotyledon", "true leaves emergence", "seed coat", "imbibition",
                          "damping-off disease", "germination rate", "viable seed", "radicle emergence"],
    "lighting-fundamentals": ["light spectrum", "photoperiod", "grow lights", "umol/J", "PAR",
                              "PPF", "far-red light", "UV-B light", "inverse-square law",
                              "light uniformity", "PAR map", "PPFD map", "shade avoidance",
                              "PAR meter", "Kelvin color temperature", "umol/m2/s"],
    "substrates-overview": ["rockwool", "living soil", "hydroponics", "air-filled porosity", "growing media",
                            "CEC", "cation exchange capacity", "pre-buffering coco", "inert medium",
                            "total porosity", "water-holding capacity", "peat moss", "ROLS substrate",
                            "substrate buffering"],
    "water-quality": ["water quality", "reverse osmosis", "RO water", "alkalinity", "source water", "chloramine",
                      "RO membrane", "PPM water", "TDS meter", "water hardness", "free chlorine",
                      "CalMag supplement", "bicarbonate content", "build back minerals"],
    "ph-management": ["pH lockout", "pH pen", "pH up", "pH down",
                      "two-point calibration", "KCl storage", "probe drift", "buffer solution",
                      "buffering capacity", "bicarbonate alkalinity", "pH adjustment"],
    "nutrient-deficiencies": ["nutrient deficiency", "nutrient toxicity", "nutrient lockout", "mobile nutrients",
                              "chlorosis", "interveinal chlorosis", "leaf necrosis",
                              "macronutrient deficiency", "micronutrient deficiency", "immobile nutrients",
                              "nutrient burn", "the claw", "nitrogen toxicity",
                              "calcium deficiency", "magnesium deficiency"],
    "flowering-stages": ["flowering cycle", "the stretch", "bud set", "the flip", "12/12",
                         "pistil", "calyx", "cola", "bulking phase", "photoperiod plant", "ripening stage"],
    "pest-id": ["spider mites", "russet mites", "broad mites", "thrips", "fungus gnats", "aphids",
                "frass", "loupe inspection", "stippling damage", "honeydew excretion", "pest generation time"],
    "pppe": ["PPPE", "gowning", "de-gowning", "personal protective equipment", "biosecurity",
             "fomite", "cross-contamination", "hierarchy of controls",
             "bioaerosol", "PCBU", "exclusion zone", "airlock gowning procedure"],
    "ripening-harvest-timing": ["harvest window", "trichome maturity", "amber trichomes", "flushing",
                                "when to harvest", "staggered harvest", "the fade",
                                "pistil darkening", "ripening phase", "ripening", "flush period",
                                "trichome color change"],
    "transplanting": ["transplant shock", "potting up", "ready to transplant", "root ball",
                      "air pruning", "root-bound", "transplant-ready clone",
                      "transplant timing", "potting medium", "transplant stress"],
    "veg-management": ["vegetative management", "veg duration", "flip height", "flowering stretch",
                       "topping timing", "canopy levelling", "veg EC ramp",
                       "internode spacing", "apical dominance breaking", "spreading branches",
                       "vegetative stage EC", "veg room management"],
    "mother-plants": ["mother plant", "mother plants", "stock plant", "mother room",
                      "clone-from-clone", "dudding disease", "cutting factory"],
    "genetics-phenohunting": ["pheno hunt", "phenotype hunt", "feminised seed", "keeper cut",
                              "chemotype", "strain name", "S1 seed",
                              "regular seed", "autoflower seed", "cannabis ruderalis", "keeper phenotype"],
    "temp-humidity-vpd": ["vapour pressure deficit", "VPD", "leaf VPD", "dew point", "relative humidity", "night humidity",
                          "plant transpiration rate", "kPa VPD", "transpiration rate"],
    "lab-testing-coas": ["certificate of analysis", "COA", "total THC", "potency testing", "HPLC", "lab testing",
                         "OOS result", "out of specification", "residual solvent"],
    "unit-economics": ["cost per gram", "grams per watt", "unit economics", "cycles per year",
                       "break-even", "blended price", "hand-trim labour"],
    "compliance-track-trace": ["seed-to-sale", "batch genealogy", "quality agreement", "mock recall",
                               "inventory reconciliation", "GACP", "deviation log", "chain of custody",
                               "CAPA system", "corrective and preventive action", "change control",
                               "good documentation practice", "ALCOA", "batch record",
                               "OOS investigation", "responsible person", "SOP register"],
    "hvac-dehumidification": ["sensible and latent", "dehumidifier sizing", "lights-off humidity spike",
                              "climate plant", "hot-gas reheat", "condensate", "N+1 redundancy",
                              "sensible heat load", "latent heat load", "dehumidification load", "latent load"],
    "cannabinoids-terpenes": ["cannabinoids", "terpenes", "decarboxylation", "CBN", "entourage effect", "THCA",
                              "terpene profile", "cannabinoid profile", "terpene content"],
    "energy-sustainability": ["kWh per gram", "lighting efficacy", "double dividend", "demand charges",
                              "heat-recovery dehumidification", "condensate reuse", "submetering", "energy benchmarking"],
    "plant-biology": ["plant biology", "life cycle", "phytochrome", "critical night length",
                      "source-sink", "axillary bud", "hermaphroditism", "silver thiosulfate",
                      "florigen", "mass flow nutrient uptake", "transpiration stream", "hermie"],
    "scaling-high-light": ["light saturation", "high-intensity cannabis lighting", "scaling to high PPFD",
                           "canopy light intensity", "high-light scaling"],
}

# Flat (phrase, slug) list, longest phrase first so multi-word wins over substrings.
def phrase_list():
    pairs = [(p, slug) for slug, ph in LINK_PHRASES.items() for p in ph]
    pairs.sort(key=lambda x: len(x[0]), reverse=True)
    return pairs
