# -*- coding: utf-8 -*-
"""Parse the Phase-3 workflow output into build artifacts:
  data/refs_gen.py        REFS_ADD dict (all new citations)
  data/glossary_gen.py    GLOSSARY_ADD list (new terms only)
  _gen/<slug>.json        per-paper outline + ref_ids for the authoring agents
"""
import json, os, re, sys

OUT = r"C:\Users\OEM\AppData\Local\Temp\claude\C--Github\88d48e04-5811-43de-a2d7-078d94466ad8\tasks\w2ptz550q.output"
HERE = os.path.dirname(__file__)
GEN = os.path.join(HERE, "_gen")
os.makedirs(GEN, exist_ok=True)

raw = json.load(open(OUT, encoding="utf-8"))
arr = raw["result"] if isinstance(raw, dict) and "result" in raw else raw

import data.glossary as GLEX
existing_terms = {g["term"].strip().lower() for g in GLEX.GLOSSARY}

refs_add = {}            # id -> {cite,url,peer}
gloss_add = {}           # term_lower -> {term,defn,tags}
manifest = []            # for build/nav wiring

def slugify(s):
    return re.sub(r"[^a-z0-9]+", "-", (s or "").lower()).strip("-")

for paper in arr:
    slug = paper["slug"]
    d = paper.get("data") or {}
    outline = d.get("outline") or {}
    refs = d.get("refs") or []
    ref_ids = []
    for r in refs:
        rid = r.get("id") or slugify(r.get("cite", ""))[:40]
        rid = slugify(rid) or ("ref-" + str(len(refs_add)))
        if rid not in refs_add:
            refs_add[rid] = {"cite": r.get("cite", "").strip(),
                             "url": r.get("url", "").strip(),
                             "peer": bool(r.get("peer", False))}
        if rid not in ref_ids:
            ref_ids.append(rid)
    # glossary
    for g in outline.get("glossary", []):
        t = (g.get("term") or "").strip()
        if not t:
            continue
        tl = t.lower()
        if tl in existing_terms or tl in gloss_add:
            continue
        gloss_add[tl] = {"term": t, "defn": (g.get("defn") or "").strip(), "tags": ["precision"] if paper["kind"] != "research" else ["reference"]}
    # per-paper outline file
    rec = {
        "slug": slug, "title": paper["title"], "eyebrow": paper["eyebrow"], "kind": paper["kind"],
        "sub": outline.get("sub", ""), "reading_min": outline.get("reading_min", 14),
        "related": outline.get("related", []),
        "ref_ids": ref_ids,
        "ref_lookup": {rid: refs_add[rid]["cite"] for rid in ref_ids},
        "sections": outline.get("sections", []),
    }
    json.dump(rec, open(os.path.join(GEN, slug + ".json"), "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    manifest.append({"slug": slug, "title": paper["title"], "eyebrow": paper["eyebrow"],
                     "kind": paper["kind"], "sections": len(rec["sections"]), "refs": len(ref_ids)})

# write refs_gen.py
with open(os.path.join(HERE, "data", "refs_gen.py"), "w", encoding="utf-8") as f:
    f.write("# -*- coding: utf-8 -*-\n# AUTO-GENERATED by parse_phase3.py, Phase-3 citations.\nREFS_ADD = {\n")
    for rid, r in refs_add.items():
        cite = r["cite"].replace("\\", "\\\\").replace('"', '\\"')
        url = r["url"].replace('"', '\\"')
        f.write('    "%s": {"cite": "%s", "url": "%s", "peer": %s},\n' % (rid, cite, url, r["peer"]))
    f.write("}\n")

# write glossary_gen.py
with open(os.path.join(HERE, "data", "glossary_gen.py"), "w", encoding="utf-8") as f:
    f.write("# -*- coding: utf-8 -*-\n# AUTO-GENERATED by parse_phase3.py, Phase-3 glossary terms.\nGLOSSARY_ADD = [\n")
    for g in gloss_add.values():
        term = g["term"].replace("\\", "\\\\").replace('"', '\\"')
        defn = g["defn"].replace("\\", "\\\\").replace('"', '\\"')
        f.write('    {"term": "%s", "defn": "%s", "tags": %r},\n' % (term, defn, g["tags"]))
    f.write("]\n")

print("papers parsed:", len(manifest))
print("new refs:", len(refs_add), "| new glossary terms:", len(gloss_add))
for m in manifest:
    print("  %-22s %-12s sections=%-2d refs=%d" % (m["slug"], m["kind"], m["sections"], m["refs"]))
